### ISSUE TITLE
FIDO keys compatibility (WebAuth)

### ISSUE THREAD

**Issue by ArnyminerZ** [GrapheneOS/os-issue-tracker#1021]
Hi, I'm currently using Bitwarden for managing my account, and I'm using a FIDO key for 2FA.
The issue is that I don't think GrapheneOS is compatible with WebAuth, which seems strange to me with a privacy-focused OS like this one.
It this correct? Is GrapheneOS compatible with WebAuth?

**Comment by thestinger** [comment]
That's not correct. GrapheneOS works fine with FIDO2. Most apps implement it via a Play services API. It's currently disabled in Vanadium due to an issue with the upstream Chromium code for the Play services FIDO2 API. It doesn't work with the modern Trichrome builds due an upstream bug. This isn't an issue for most other Chromium-based browsers since they use the older build targets due to not providing the WebView so they don't need the split into 3 apps (browser, WebView, library).

**Comment by thestinger** [comment]
https://play.google.com/store/apps/details?id=de.cotech.hw.fido.browser is an example of a non-Play implementation of FIDO2. It works fine. Play services implementation does partially work via sandboxed Google Play. We can put some effort into making it fully work.

**Comment by ArnyminerZ** [comment]
Okey, anyway logged in using email verification code. However, will keep that FIDO Browser just in case. Thanks.

**Comment by zDEFz** [comment]
> That's not correct. GrapheneOS works fine with FIDO2. Most apps implement it via a Play services API. It's currently disabled in Vanadium due to an issue with the upstream Chromium code for the Play services FIDO2 API. It doesn't work with the modern Trichrome builds due an upstream bug. This isn't an issue for most other Chromium-based browsers since they use the older build targets due to not providing the WebView so they don't need the split into 3 apps (browser, WebView, library).

Pixel 7a, latest GrapheneOS.
Installed play services through the Apps drawer in GrapheneOS, tried FIDO browser and when I'm on nextcloud and wanting to use my Yubikey it just crashes. What can I to use it? I know the Yubikey Authenticator works, but it is kinda not of what I wanted to use it for. My case is: Getting a keepassxc database with my yubikey through nextcloud.
