### ISSUE TITLE
Location not working

### ISSUE THREAD

**Issue by ElastfeKek** [GrapheneOS/os-issue-tracker#1035]
Regardless if I use play services or with it disabled, location does not work on my device. I tried through organic maps and Google maps but nothing shows up when it searches for location.
Device: Pixel 4a

**Comment by thestinger** [comment]
Please ask for support in our Matrix room. Location works fine.

**Comment by thestinger** [comment]
Make sure to read https://grapheneos.org/usage#sandboxed-google-play-configuration. Apps using the Play services geolocation are rerouted to the OS by default. GrapheneOS doesn't use a network-based location service itself, and likely never will, so it requires having a GNSS signal. You'll need to ask for support in our Matrix room rather than the issue tracker. Location works fine on the Pixel 4a. If you don't have a GNSS signal, that's the problem. You can use the Play services network location service if you choose for indoor location detection, or you can wait for our offline "network" location service to be available.

**Comment by jann-0** [comment]
@ElastfeKek Location works fine for me. I have a 4a here. Consider joining the matrix rooms as given here https://grapheneos.org/contact where we can help you troubleshoot.
