### ISSUE TITLE
Translation of Graphene-OS and -Apps?

### ISSUE THREAD

**Issue by SebastianBerlin** [GrapheneOS/os-issue-tracker#1037]
Maybe I haven't seen this option: Is there a Function to translate the OS or its apps in different languages? That works in general good with volunteers and there are pretty good tools to localize that online. Even twitter had a long time translator team supported only by the community itself.

**Comment by thestinger** [comment]
We plan on making translation teams for languages with large GrapheneOS communities. These translation teams will be organized in an official Matrix room for each language. We'll start by translating all the standalone app projects including the ones not distributed outside GrapheneOS. It's much harder to properly maintain translations for the OS and work will need to be done in order to make that less invasive and easier to maintain. Keep in mind that we can't block releases with security updates, etc. based on waiting for translations and we can't be spending any time on translations during major version migrations. It's going to be fairly easy to do it for our standalone apps, but much harder for changes to AOSP projects.

**Comment by thestinger** [comment]
It's best to discuss this in our Public Development Matrix room.

https://grapheneos.org/contact#community

**Comment by fwuffyboi** [comment]
> We plan on making translation teams for languages with large GrapheneOS communities. These translation teams will be organized in an official Matrix room for each language. We'll start by translating all the standalone app projects including the ones not distributed outside GrapheneOS. It's much harder to properly maintain translations for the OS and work will need to be done in order to make that less invasive and easier to maintain. Keep in mind that we can't block releases with security updates, etc. based on waiting for translations and we can't be spending any time on translations during major version migrations. It's going to be fairly easy to do it for our standalone apps, but much harder for changes to AOSP projects.

has this changed, or is this still the case with the grapheneOS translations?

**Comment by twitchyisreal** [comment]
Is there a status on this?
