### ISSUE TITLE
Error encountered generating attestation

### ISSUE THREAD

**Issue by ZhuDaHai** [GrapheneOS/os-issue-tracker#1043]
Java.security.ProviderException: Failed to generate key pair

Auditor v 44
Graphene os build: sp1a.210812.016.C1.2022030801
Pixel 3

Paired and validated many times before. Both devices using auditor v.44

What's wrong?
How to fix?

**Comment by thestinger** [comment]
Moved to OS issue tracker since this is a confirmed OS bug.

**Comment by ZhuDaHai** [comment]
Thank you both for your quick responses!
I will wait for an os patch

**Comment by thestinger** [comment]
We've been unable to resolve this and there aren't people working on it since the devices lack maintainers. I think hardware attestation on the Pixel 3 and Pixel 3 XL is not going to be supported anymore. The only way that will change is if developers step up to maintain these devices.

**Comment by thestinger** [comment]
We're not going to track issues in end-of-life devices on this issue tracker.

**Comment by ZhuDaHai** [comment]
> We've been unable to resolve this and there aren't people working on it since the devices lack maintainers. I think hardware attestation on the Pixel 3 and Pixel 3 XL is not going to be supported anymore. The only way that will change is if developers step up to maintain these devices.

So. You pushed a release with a known bug onto an end-of-life device that broke OS validation and now there is no one to fix it. 
In short, you have left me exposed.
If it's an end-of-life device, why are you still pushing updates? Just to break it and force people to newer phones?
So either I'm missing something here, or GrapheneOS is just a toy with no real security or intent on security and should not be relied upon by anyone.
What a joke

**Comment by thestinger** [comment]
No, that's not what happened at all.

Pixel 3 and Pixel 3 XL have been end-of-life since after October 2021. They do not have full security updates available and are very insecure and unsafe to use at this point regardless of what you use on it. GrapheneOS has continued providing extended support releases providing all of the AOSP and GrapheneOS updates for them along with other updates where we can, such as providing updated kernels based on the Pixel 3a kernel tree.

March update brought the 2nd quarterly release of Android 12, which is referred to as Android 12.1 or 12L. The first quarterly platform release went fine for these devices. There was no reason to expect that hardware attestation was going to break. Verified boot is still working perfectly fine.

We were not aware of any issue when we moved the release from the Beta channel to the Stable channel because no one reported any issue to us beforehand. It was reported by you after we had moved it to the Stable channel, at which point it was too late to avoid most people updating to it. We also made the decision that it's far better to provide as much of the March security update as is available for these end-of-life devices than keeping hardware attestation via Auditor working.

Verified boot is still working fine. Only Auditor is broken since hardware attestation isn't working anymore. As much as we'd like to fix it, we've put a bunch of hours into it already with no success and we can't afford to dedicate weeks to resolving a non-critical issue on an insecure, end-of-life device we're trying to discourage people from using.

I don't see how this makes GrapheneOS into a toy. We could have not provided security updates after October 2021 when Google stopped releasing them. I think you should be happy we provided as much of the security updates as we could after that point. We still plan on continuing to provide security updates until the next major release of the OS. If we didn't have the Auditor app, no one even would have noticed that this keystore feature broke. It's only because we have our Auditor app that you noticed this. You wouldn't have elsewhere.

You're forced to update to a newer phone to have a secure device due to the Pixel 3 being end-of-life. It's not our Auditor app no longer working after we shipped the March security update creating a pressing need for you to get a Pixel 6 as a replacement with a minimum of 5 years of support instead of the 3 years of the Pixel 3 which ended last year.

**Comment by ZhuDaHai** [comment]
So, you're saying one of the reasons grapheneOS is so secure is because of the attestation, but now that it's broke it really didn't matter?  seriously?
No one, not even the coder, tested the Auditor App, one of the more significant security features of GrapheneOS, before pushing the release? seriously? Sounds like not even minimal testing is being done.
Again, its a toy. 
And I'm not going to shell out hundreds of dollar on a new phone (I can't afford it), for a OS that doesn't even do basic regression testing against its own apps on the phones they purportedly support. 
Again, its a toy - the developers aren't even taking it seriously.
You should have just stopped with the security updates last year instead of killing base functionality through lack of basic due-diligence. 
Yes.It's.a.toy - and you're still pushing broken releases like its a toy

**Comment by thestinger** [comment]
Pixel 3 and Pixel 3 XL are end-of-life. Shipping the monthly AOSP security updates and additional GrapheneOS updates including Vanadium updates is the best we can do, but their security patch level is stuck at 2021-11-01 forever and they're increasingly insecure.

Hardware-based attestation is a nice feature but it's increasingly less useful on these end-of-life devices especially since there are unpatched secure element security bugs which have been disclosed for months already.

Auditor is just one feature of GrapheneOS, and can be used on the stock OS with somewhat weaker security properties due to the OS not being as hardened. It's a nice feature but it doesn't make up for not having security updates at all. Auditor isn't part of what makes GrapheneOS secure but rather is a way to detect signs of compromises after the fact. We're going to choose shipping security updates over having hardware-based attestation working.

Since these are end-of-life devices, we cannot put a ton of resources into trying to fix the issue as we would for devices that are still fully supported. These phones are over 3 years old and people have gotten a lot of use out of them already unless they made the unwise choice of buying older than current generation devices, which we strongly recommend against.

We've marked the Pixel 3 and Pixel 3 XL as legacy for months (since after October 2021) and we do not claim to provide full support for them anymore. We do what we can. It would have been an option to make an Android 12 branch of GrapheneOS instead of moving them to 12.1, but we don't have the resources to maintain 2 different branches of the OS. If we would have known about the regression before pushing it to Beta, we would have invested time in fixing it and delayed the release, but there's no reason to think we would have figured it out and we would have had to decide if we wanted to drop support for them completely or somehow get resources to maintain a 12 branch for them which wouldn't have realistically happened.

It's entirely possible that someone will figure out how to resolve the issue. What you're doing is just taking more development resources away from the project and demotivating anyone from working on the Pixel 3 and Pixel 3 XL.

**Comment by thestinger** [comment]
This will be resolved in the next release.
