### ISSUE TITLE
implementation of smart charging and fast charging toggles for battery protection

### ISSUE THREAD

**Issue by noirge** [GrapheneOS/os-issue-tracker#1089]
I would appreciate an implementation as you can find it in iodé rom. There you have the possibility to stop fast charging in the settings to protect the battery. In addition you're able to set a maximum charging level.
![1](https://user-images.githubusercontent.com/102553691/160477741-6b5342fa-0381-4189-a9d6-8ad6ca2b0037.png)
![2](https://user-images.githubusercontent.com/102553691/160477744-67814feb-2478-4638-8139-4e27de25381c.jpg)

**Comment by flawedworld** [comment]
We aren't going to add support for this. The firmware already deals with this. The effects of fast charging are going to have minimal impact and by the time they will be noticeable you will be on new hardware anyway.

**Comment by noirge** [comment]
Good to know. Thanks for answering. At the end it will become a decision between privacy or protecting nature.

**Comment by thestinger** [comment]
No one forces you to use the included charger or another charger with fast charging. You can plug it into a computer or a standard USB charger.

**Comment by noirge** [comment]
Yes, I know. I would like to hold the battery between 30% and 80% which is cool when using the phone for navigation f.e. I have an app which vibrates when I reached my maximum oder minimum and I can stop charging manually. For me it just would be an improvement if it just stops charging though. But I understand if there is no further interest!

**Comment by Zanthed** [comment]
The battery controller and firmware already do this.

**Comment by noirge** [comment]
Ah okay. I didn't know. In my Samsung Tablet you can choose if you want use the stop at 80%. Thanks for the information.

**Comment by odlg** [comment]
I agree that the firmware controls how fast the battery is charged, but to make li-ion batteries last longer it is often advised to only charge it to like 80% for daily use. Is that possible?

**Comment by flawedworld** [comment]
No. And this is not necessary.

**Comment by Zanthed** [comment]
The battery controller and firmware handle charging rates and maximum charge already.

**Comment by nikolayandr** [comment]
Hi, I have developed an application https://play.google.com/store/apps/details?id=com.makeworldbetter.fastchargetoggle which allows to toggle fast/super fast/wireless fast charging using notifications/widgets/application but unfortunately it works only on 11/12 Androids, looks like Samsung made the property used to toggle fast charging as private. I would appreciate If you could leave a comment here https://forum.developer.samsung.com/t/are-adaptive-fast-charging-super-fast-charging-wireless-fast-charging-available-forwriting/23335 to show to Samsung developers you are also interested in getting answer from Samsung developers how to toggle fast charging in Android 13

**Comment by thestinger** [comment]
@nikolayandr  This is not appropriate for this issue tracker.

**Comment by Morpheus0x** [comment]
Yes, the firmware controls the charging rate and protects the battery from over/under charging, but other than that, the full capacity of the battery is used. However, as @odlg mentioned, it is advisable for optimal battery life to not let it go below 30% and above 80%. On new phones, that is plenty to last you at least a day and as it gets older the user could increase the usable range.

The Pixel 4 only got 3 years of software support, but hopefully later Pixels get longer support. And just because I know I will be switching to a newer phone after support ends, whoever I give the phone to should still be able to enjoy moderate battery life.

I understand that supporting custom changes to AOSP is hard, but I think in this case many people would appreciate this feature.
