### ISSUE TITLE
Cant open tor

### ISSUE THREAD

**Issue by LutraLutris** [GrapheneOS/os-issue-tracker#1104]
Cant open the tor browser after the newest update.

Ive got a pixle 5 and tried downloading the tor APK and aurora store but nothing works. I was able to open it once I had restarted the phone but as soon as I closed the app it stops working again.

**Comment by thestinger** [comment]
It's a Tor Browser issue rather than a GrapheneOS issue. You should try clearing the app data and doing it over again. There's an issue filed on their tracker which you can probably find. I can't look for it right now. It occurs on other operating systems and the consistency of the crash happening varies. It doesn't happen on old releases and will hopefully be resolved soon.
