### ISSUE TITLE
unauthorized icmp4 web access attemts

### ISSUE THREAD

**Issue by lossposs** [GrapheneOS/os-issue-tracker#1160]
question regarding some connection attempts logged by netguard firewall. did anybody using netguard ever notice unauthorized icmp4 type 3 connections by unnamed apps? it doesn't show the app's name or any uid and no option to block that connection. host names have my location in them. anybody knows what is this and how to block it? it is quiet concerning

**Comment by thestinger** [comment]
This is a support question rather than a bug report and should be done via our Matrix room. It's very unlikely that this is an issue with the OS and you're making odd assumptions about what's happening.

**Comment by lossposs** [comment]
> 

matrix graphene os room suggested to reboot with no explanation. what exactly is odd in my assumption if you dont mind?

**Comment by thestinger** [comment]
You're assuming that something is wrong when there isn't an indication of that. You aren't providing any of the information which would be needed to know what's happening. It's also not clear if the Destination unreachable errors you're reporting are inbound or outbound traffic. Those aren't being sent by an app. They indicate that there were errors attempting to connect to a destination in either direction. It's not a bug report, but rather a support issue, since you're asking a question about something completely normal. You aren't providing the details that would be needed to explain what's happening though.

**Comment by lossposs** [comment]
ok got it, sorry i don't have proper knowledge. tried to google things out myself and wasn't satisfied with results, after the matrix graphene chat here was my last hope to find answer. so if its normal can you please link me some helpfull source to learn more  regarding the question in subject?
