### ISSUE TITLE
[GmsCompat] Play Store not available in system language

### ISSUE THREAD

**Issue by heuwerk** [GrapheneOS/os-issue-tracker#1172]
Since the Play Store is only updated via the "Apps" app, the Play Store on my device is only displayed in English.
Previously, I received the notification that the Play Store wants to update itself and has set itself to the system language (german).
If more information is needed, I will be happy to provide it.

- Device: Google Pixel 5 w/ GrapheneOS 12
- Build-No: SP2A.220505.002.2022050301
- GmsCompat installed in second user profile
- System language set to German
- Google account registered and used in Germany

**Comment by thestinger** [comment]
We need to implement support for split apk locales in the app repository client along with figuring out how to download the Play Store with multiple locales. The main reason this isn't currently available is because the Play Store is a split apk which we retrieve from a stock OS Pixel 4, and that Pixel 4 is set to English (US) so we only obtain that part of the locale split. You can see this in https://apps.grapheneos.org/packages/com.android.vending/83021810/. The first step would be figuring out how to download all the splits and perhaps just having the app repository client always install all of them initially.

**Comment by thestinger** [comment]
This is filed as https://github.com/GrapheneOS/apps.grapheneos.org/issues/6.
