### ISSUE TITLE
Way to get hash of a file (like f-droid) before installing it?

### ISSUE THREAD

**Issue by ddevz** [GrapheneOS/os-issue-tracker#1191]
In order to install things like f-droid, you download the f-droid apk and install it.
However, I see no way to get the hash of the file to confirm its validity before installing.

Obviously one could be downloaded from f-droid... but you shouldn't install f-droid till you confirm the hash! :)
If there is not a way to get the hash, I would like to propose it as a new feature.

Possible alternatives:
- A alternative would be to add it as one of the apps that could be installed from the "apps" app.  
      However you may not want to do that if you consider inclusion in the apps app as some kind of "seal of security approval".
- Another alternative could be to add a way to check the pgp signature of a file, (f-droid currently publishes a pgp signature, not a hash, but either would work since you could verify the pgp signature on another machine then compute the hash on that machine to determine the hash)

**Comment by thestinger** [comment]
PGP is a terrible way to do signing/verification and makes no sense for Android apps since it's not possible to install an apk unless it has a valid signature. It doesn't make any sense to verify an apk with a detached signature using an inferior approach instead of the standard signature, which is always verified by the package manager.

It's not our responsibility to deal with F-Droid not understanding the Android platform or having a good approach to security. We provide our own app repository as part of GrapheneOS with a proper metadata / package security model (unlike F-Droid) and that includes being able to bootstrap getting apps from the Play Store without a break in the chain of trust.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/211 is already filed for showing the public key fingerprint for the initial install of an app before it's pinned.

https://github.com/GrapheneOS/os-issue-tracker/issues/989 is filed about providing a database of pins for the official signing key fingerprints of many apps mapping app id to a valid signing key fingerprint, with proper support for the key rotation feature for keys authorized by that signing key. Most apps on F-Droid would be considered to have invalid signatures and would trigger the warning message since F-Droid is wrongly reusing developer app ids for their own builds. That's not going to be good experience for F-Droid users.

**Comment by ddevz** [comment]
That covers it, thanks.  
(note: i did search the list of issues but i searched on "hash")
