### ISSUE TITLE
Sensor Off Security Equivalent w/o DEV

### ISSUE THREAD

**Issue by Kenny606** [GrapheneOS/os-issue-tracker#1203]
I just had a feature request for your consideration. Something I thought would be of interest from a security perspective given that is the focus of Graphene and why I use it.

I personally love the "Sensors Off" feature in Development options.
It's easily toggled, so I basically keep on at all times unless I need temporary access to my camera or sensors or mic, I just consider it one more level of security.
I can also keep it on without interfering with phone calls, speaker or otherwise. And somehow it doesn't even interfere with Signal calls I guess Android classifies them as phone calls. (Though I haven't tested that on Graphene yet.) 
All while every other app regardless of permissions are prevented from using those no matter what permissions I've granted them, camera is shut off mic returns dead air, sensors are nullified.

That said I don't like keeping Dev Options on necessarily, but I prefer the feature over the risk of keeping DEV options open.

I was just wondering whether it was possible to offer this or an equivalent function outside of DEV Options?
And possibly improve upon it by offering Graphene users the option on what they want it locking down, just the camera, or camera and mic etc.

How secure the option is and how hard it is for apps to bypass I have no idea but combined with Graphene's security I'm guessing it works pretty well.

Thanks for all your hard work.

Kenneth

**Comment by thestinger** [comment]
We can implement a Sensors quick tile similar to the ones for Camera and Microphone in the future, but it won't be the same as the Sensors Off feature which was not designed in a way that makes sense anymore. Ideally our Sensors permission would also have the same kind of indicator and history support as the Camera and Microphone permissions.

We do want to add something like this but I'm going to close this issue because it's not really the approach we want.

For Camera and Microphone, there are standard toggles for those already which work better than this feature with better app compatibility and semantics.
