### ISSUE TITLE
Feature Request: Android Auto Invasive Privilege Switch 

### ISSUE THREAD

**Issue by kkl1974** [GrapheneOS/os-issue-tracker#1209]
Hi 

I am aware that Android Auto app requires escalation of extensive & invasive privileges for USB use with in car infotainments systems, would it be possible to add a button similar to the privileged esim switch to allow my GrapheneOS phone and head unit to communicate? 

Thanks

**Comment by Zanthed** [comment]
I don't think we want to do this. Android Auto for phone screens is deprecated and being phased out.

https://www.theverge.com/2022/6/3/23153100/android-auto-app-phone-screens-discontinued

https://www.xda-developers.com/android-auto-for-phone-screens-killed/

**Comment by kkl1974** [comment]
That's fine, although I wasn't asking about using the phone screens version, I was asking for the necessary components and permissions in the form of a toggle switch to allow head unit communication. (just like e-sim)

My phone and head unit do partially recognise each other already, but I am given an error on both and Android auto fails to start. 

If you guys don't think its worth it then I understand, but for me this is the last feature that Graphene can't use but the stock rom can that hasn't been fixed and doesn't have a workaround.

**Comment by Andragor** [comment]
Hi, I concur with @kkl1974 that a Permission Switch for Android Auto is the last feature I really miss with GrapheneOS. Anything else works really good, but I regularly use my phone with Android Auto/Apple CarPlay on my car so that I have an up to date navigation system. If you could make this work, that would be really awesome. Like @kkl1974 I don't need the App Android Auto, but the permission so the car itself can connect with the phone.
