### ISSUE TITLE
When GmsCompat is installed, a ghost application appears

### ISSUE THREAD

**Issue by S1BIOSE** [GrapheneOS/os-issue-tracker#1216]
I don't know if ghost app is appropriate, but when GmsCompat is installed, an app appears on the home screen from time to time. It says "Pending..." and I don't know what it is. I delete it and it reappears later.

Is GrapheneOS a problem? Do you have the same behavior?

**Comment by thestinger** [comment]
Sounds like it's trying to install AR services and this is a normal OS feature for atomic installations. We don't plan to do anything about this. You can allow it to install AR services and then remove it, and it won't try to install it again. Alternatively allow it to install and disable it.

**Comment by S1BIOSE** [comment]
I have already tested this and it does not appear. It connects via bluetooth but the cursor does not appear. If I plug it in usb-c the cursor does not appear. It's really weird, I searched in the settings but I really don't

**Comment by thestinger** [comment]
Or just allow it since it's just a sub-component of Play services and isn't doing any harm. Play Store is just quite insistent on installing AR services.

**Comment by thestinger** [comment]
@S1BIOSE I think you replied on the wrong issue.

**Comment by S1BIOSE** [comment]
ok, thanks for the explanation. Wouldn't it be better to add it in the "Graphene App" dependencies ?

**Comment by thestinger** [comment]
It's optional so it's not really a dependency and it seems fine to leave Google Play Games, AR services, VR services, etc. to the Play Store since they'll rarely have changes that break with the compatibility layer. We could eventually handle those updates but we don't currently want to.

**Comment by Zanthed** [comment]
You can just install it and disable the app.

**Comment by Zanthed** [comment]
This should be fixed in the next release.

**Comment by Poryhack** [comment]
What is the current expected behavior for Play Services for AR? I ask because I am (still) getting the nag to install it. I haven't installed it previously and always decline when it tries to install. Do I need to install and then uninstall like thestinger said earlier or should that no longer be necessary?

I think others would agree that the ideal behavior here would be to prevent the auto-install without requiring the user to do anything. Also, it shouldn't show up on the pending downloads and "not installed" apps screens in the Play Store.

All that is assuming Play Services for AR is not necessary/recommended for a basic sandboxed Play Services setup. If it is, the setup guide for sandboxed Play Services should be amended to mention it.

I'd be happy to create a new issue for this or update the docs myself but first I wanted to verify the expected behavior and confirm that it isn't just me with this issue.

**Comment by thestinger** [comment]
You have an app such as Google Camera which uses AR services and is triggering Play Store to install it. This is fully expected and intended behavior of Google Play. AR services are essentially a Play services component distributed as a separate app. I don't really understand trying to out of the way to avoid installing it.

> I think others would agree that the ideal behavior here would be to prevent the auto-install without requiring the user to do anything. Also, it shouldn't show up on the pending downloads and "not installed" apps screens in the Play Store.

It cannot be installed without user consent. That doesn't happen.

**Comment by thestinger** [comment]
We don't need an issue opened about standard Google Play behavior which is working properly on GrapheneOS and all happens without it having absolutely any special privileges or access. They're regular sandboxed apps. You have granted the request install permission to the Play Store so it can request that you install an app which is what it's doing. It's not wrongly doing it either. It's requesting that you install it because you have apps installed which require it like Google Camera.

**Comment by Poryhack** [comment]
Thanks for the information, I was not aware Google Camera that dependency. I didn't mean to imply that it was being installed without consent, just that the install request was happening without solicitation (or so I thought at the time).

Now that I understand what's happening I agree 100% no issue is necessary. I do suspect however that others have encountered this same situation and been confused as I was. Would you agree that a short note about dependencies on the grapheneos.org "usage" page would be helpful for new users? I'd be happy to submit a PR to that effect for review.
