### ISSUE TITLE
Implement Color Calibration in Display Setting

### ISSUE THREAD

**Issue by H3arn** [GrapheneOS/os-issue-tracker#1238]
Hello. A few months ago, I noticed the screen white balance is yellowish, say, with yellow/green tints, affecting the display effect. But the shipped display settings only have 4 selections for color saturation which is doesn't help at all. 

Such problem, a confirmed color calibration issue, seems to be **prevalent** among some Pixel, especially 4/4XL/4a/4a5g/5/5a/6. But Google never provided support for custom color calibration while this is common in other OEMs like Samsung and Sony. 

Thus I was wondering if color calibration could be added to the display settings to let users adjust the color profile to their taste. That would be definitely helpful to improve users' screen experience. 

Thanks a lot.

**Comment by flawedworld** [comment]
This isn't really within scope of the project and would likely involve significant work to implement.

**Comment by therealmarv** [comment]
I have the same problem with Pixel 7 Pro.

I'm confident a rudimentary fixed solution could be implemented in the "Settings -> Accessibility -> Colour and motion -> Colour correction" with adding a new option which reduces only green values by around -15%. Pixel phones are color calibrated but on a low color temperature (6300K?) which gives this yellow / green look (because of increased green it looks yellowish). Especially skin colors are affected.

I could fix the colors on a Pixel phone by rooting it and installing CF.lumen. Details [here in this reddit post](https://www.reddit.com/r/GooglePixel/comments/yc31fu/comment/ivbx1jq/). I'm not very happy to need to root it. Samsung, Xiaomis phones don't need root for this functionality.

I agree this should be a basic implementation for all Android.
