### ISSUE TITLE
The Clock application disabling screen timeout should be optional

### ISSUE THREAD

**Issue by TheMCNerd2017** [GrapheneOS/os-issue-tracker#1245]
I just found out that the built-in Clock application prevents screen timeout from triggering when doing certain actions, like using the stopwatch. This behavior should be made optional, as it can cause screen burn-in if the user leaves their device unattended while not knowing that screen timeout has been disabled by the Clock application.

**Comment by r3g-5z** [comment]
I don't think this is worth spending development time on. It's very normal for stopwatch apps to hold a wake lock because it's assumed you're watching the time when using a stopwatch. That's mainly the purpose of a stopwatch. It's also intended for it to hold a wake lock when your alarm is going off. Both of these cases exist on stock OS (Google Clock) and iOS.

If there's other places it's holding a wake lock in that it shouldn't then that can be dealt with (e.g. holding a wake lock in the main page for no reason), but a wake lock when it's being used as a stop watch and when your alarm is going off is very normal and it would be strange to not want it to hold a wake lock in those situations. You also aren't going to have burn in just because you left the stop watch on for an extra 10 minutes.

I grepped for `FLAG_KEEP_SCREEN_ON` and I only found it in 4 places that I would expect it to be there: Screensaver, Stopwatch, Alarm, and ExpiredTimers (timer going off). These don't seem unusual and would be very expected.
