### ISSUE TITLE
More privacy to the lockscreen

### ISSUE THREAD

**Issue by onkq** [GrapheneOS/os-issue-tracker#1261]
My first issue here.

I've noticed that you can pull down the "notification drawer" or quick drawer section all the way down when pulled from the very top and view unnecessary information that should only be displayed by from an unlocked state, this will include media player (playable), VPN you're connected to, every quick setting tile, Wi-Fi name and connected Bluetooth device's battery in some cases. Some of the settings can also be turned on and off.

**The first three attempts shows the expected behavior!**

https://user-images.githubusercontent.com/84337276/174489414-e68ffef3-5393-482b-9291-47c26c6e76e5.mp4

Device: Pixel 6

**Comment by thestinger** [comment]
This is working as intended and we restricted the sensitive tiles.

**Comment by onkq** [comment]
Yes this is working behavior. My asking is more privacy. Is this something that can actually be put as an option? I imagine it to be a simple change

**Comment by thestinger** [comment]
If it's simple someone should be able to quickly implement https://github.com/GrapheneOS/os-issue-tracker/issues/205 and no one has done that.

We're not really looking for more feature requests but rather contributions to the project, and especially help with maintenance / porting. There will be a moratorium on new features soon due to the approach of Android 13 where we have to prepare for it and port to it.
