### ISSUE TITLE
Suggestion: lock to prevent apps from getting closed

### ISSUE THREAD

**Issue by opensourcefan2** [GrapheneOS/os-issue-tracker#1277]
Since GrapheneOS doenst have play services (and most users dont want to install them) some apps cant notify me when a new message arrives, when the app is closed. I suggest a lock (I believe Samsung or Huawei has this feature) to prevent specific apps from getting closed. Espeacially when I use the "close all apps" feature.

**Comment by thestinger** [comment]
Apps can implement push without Play services, and GrapheneOS supports sandboxed Google Play. Your proposal isn't valid since that's not how Android software works. If apps don't choose to run in the background, they don't run in the background. The OS doesn't force them not to stay running. They can run a foreground service visible to the user and remain running. You're essentially asking that we change how apps are implemented. You're asking the wrong people. You need to ask the app developers to implement push with or without Play services, not us.

https://grapheneos.org/faq#notifications
https://grapheneos.org/features#sandboxed-google-play

**Comment by opensourcefan2** [comment]
Ok, but why does the app notify me when its opened in the background but not when closed? Also, why should I use GrapheneOS when I plan to use play services. Even on the official site it states that this isnt how the OS is planned to be used.

**Comment by thestinger** [comment]
> Ok, but why does the app notify me when its opened in the background but not when closed?

That's how the app developer chooses to implement. It has nothing to do with GrapheneOS. They choose to implement their own push in the foreground and don't do that in the background. They only use FCM in the background. Entirely their choice, and it is up to them to implement it another way. You're misinterpreting what's happening and your proposal is incompatible with how this actually works.

> Also, why should I use GrapheneOS when I plan to use play services.

I suggest reading https://grapheneos.org/features which explains the substantial privacy and security benefits of GrapheneOS over AOSP or the stock OS. Not including Google apps and services out-of-the-box is a minor point on that page. Sandboxed Google Play compatibility feature is one of the major features provided by GrapheneOS.

> Even on the official site it states that this isnt how the OS is planned to be used.

It absolutely does not say that. We support users using the apps of their choice while maintaining their privacy and security through improvements to app sandboxing, the permission model and many other areas. The baseline we're starting from (AOSP 12.1, soon AOSP 13) already provides a strong foundation.

**Comment by thestinger** [comment]
Signal, FairEmail and WhatsApp are 3 examples of apps with support for using their own push implementation in the background. This is up to the apps to implement and there is no way for GrapheneOS to provide it. You're misunderstood the issue and your proposed solution therefore isn't valid because that's not the problem or how apps work. The app you're talking about is just choosing to only provide background push via FCM. If FCM isn't present, it doesn't do it. The issue is not the app not being able to run in the background. It can run in the background. It could implement background push on their own using a foreground service. If it doesn't, that's an app issue, not an OS issue. GrapheneOS fully supports apps which do background push with or without Play services. You can test for yourself and see that it all works fine. There is nothing we need to add for this. It's an app feature.
