### ISSUE TITLE
Secondary profile gesture Navigation in notifications 

### ISSUE THREAD

**Issue by Chromatros** [GrapheneOS/os-issue-tracker#1280]
It does not work at all in secondary profiles. No matter what app. Newpipe, Spotify.....

**Comment by thestinger** [comment]
Not clear what you mean by gesture navigation in notifications. You'll need to make it clearer what's wrong.

**Comment by Chromatros** [comment]
Compare newpipe notifications gesture Navigation in owner profile and secondary. You can't even close it. Not next track or last track

**Comment by thestinger** [comment]
@Chromatros That happens with NewPipe and certain other media applications on the stock OS and AOSP too. It doesn't happen with Vanadium, so clearly there is a way for apps to do this which works in secondary users. I'm not sure if it's an OS issue or an app issue but it only impacts certain apps and occurs with AOSP / stock OS so it's for those apps or AOSP to resolve rather than us. We can't track every upstream AOSP and app issue here. Since it's not specific to GrapheneOS it belongs on other issue trackers.
