### ISSUE TITLE
Turning on the flashlight when long pressing the power button

### ISSUE THREAD

**Issue by deadbeef2000** [GrapheneOS/os-issue-tracker#1301]
I've also seen this feature on other ROMs and I'd love to see it here!
This option is only useful when the screen is off, otherwise this should show the power menu.

**Comment by thestinger** [comment]
We're not adding this. It wouldn't be a good fit for the gesture on GrapheneOS.

**Comment by js-on** [comment]
Why do you reject this feature so vehemently? It would really save time and be easy to use if you just had to press the power button for a long time to turn on the flashlight when the display is off. No interaction with the display (power button, swipe down, activate flashlight) and without looking.
I use this feature every day on my old phone.
What's so much against it from your side? In what way would it affect the rest of the functionality of GrapheneOS?

No attack at this point, I just want to understand what speaks against it and tempts you to reject all requests.

**Comment by thestinger** [comment]
We aren't adding such a niche feature for something that's already easy to do it. There are far better ways to use long press.

**Comment by Broeckelmann** [comment]
Well if you don't like the long press for flash, how about a settings menu where you can set long press behaviour for buttons?
It's a fairly common option in many ROMs and would be very useful for many people in my opinion. 🙂

**Comment by firefoxlover** [comment]
> We aren't adding such a niche feature for something that's already easy to do it. There are far better ways to use long press.

no its not, when pressing the power button when the screen is off, it just turns on the display and then show the reboot menu. The long press is unused, the flashlight only turns on when the screen is off.

This is not a niche features, as everyone with LineageOS has this. We are stuck with GrapheneOS features as there are no XPosed modules (battery limiter, better volume control, microg, f-droid privileged,...) so of course we request that.

**Comment by thestinger** [comment]
It's an extremely niche feature. You can tap the screen or power button and turn it on from the quick settings menu. How often do you need the flashlight for it to be a good use of a long press button? Other operating systems doing something doesn't mean it makes sense for us.

> microg

GrapheneOS has the sandboxed Google Play compatibility layer approach which offers dramatically more compatibility and robustness while using the same app sandboxing for Google Play as the apps using it via the Google Play libraries / SDK.

> f-droid privileged

This is obsolete and heavily bypasses how the app installation security model is supposed to work. Apps don't need privileged access to do fully automatic updates. F-Droid is simply outdated and not using modern package management APIs, which is both why it can't do automatic updates without that approach which is invalid for it, since it uses multiple sources of apps, not only first party.

> If you need the menu, you have to use your phone to turn on the flashlight. If you have the long press, the phone is the flashlight. This is so useful for quickly turning it on.

We would rather use it for something like duress functionality fitting the focus instead of a niche shortcut for something already quite easy to do.

**Comment by firefoxlover** [comment]
@thestinger The reasons make sense. I dont want to annoy, as I am not the one with experience in Android coding.

**Comment by dalz** [comment]
Since nobody has given any good argument in favor of the gesture, I'll say that I used it often on my previous phone. It's very helpful when you only have one free hand, wear gloves or have wet hands (at least one of which happens to me almost every day). Plus, I've asked my family and they all have (on their stock vendor roms) a way of turning on the flashlight without using the touch screen (long pressing the power button or shaking the device).

But I guess I could still buy a real flashlight :upside_down_face:

**Comment by thestinger** [comment]
We've explained that we aren't adding it. It's not available in the stock Pixel OS. It's not the kind of thing we would do with long pressing power rather than something more useful. Other people doing it isn't a reason for us to do it.
