### ISSUE TITLE
WebDAV Cloud files integrated in GrapheneOS settings.

### ISSUE THREAD

**Issue by guilpaoff** [GrapheneOS/os-issue-tracker#1306]
Hello,

It would be convenient and more secure to have a parameter in GrapheneOS dedicated to webdav account management. This would allow not having to install a third party application to have basic information like contacts and calendar synchronized with an external account.

Thanks

**Comment by ASerbinski** [comment]
A "parameter"? There would still have to be some kind of program in the back for such a "parameter" to do something, which means either developing or even better, INCLUDING some webdav program, such as DAVx5, which is pretty much the universal go-to for webdav on Android.

In my opinion, this would be better handled by facilitating the installation rather than just including it, which should be done through the "apps" portal.

**Comment by Zanthed** [comment]
We don't want to integrate anything and have no plans to integrate anything like that. We do not want to expand what the base OS has beyond what we already have.

We plan to expand our app store to include some 3rd-party apps hardened and maintained better by us, but that's not a high priority right now.
