### ISSUE TITLE
USDevice: Access Denied

### ISSUE THREAD

**Issue by burdges** [GrapheneOS/os-issue-tracker#1323]
I've likely missed something somewhere, but attempts to join the matrix rooms always fail, so..

Any idea what the web usb installer error "Error: Failed to execute 'open' on 'USBDevice': Access denied." means?

Also, there is no explanation of these ota_update files in the command line installer.  Am I supposed to install those first to fix the base version?  Or afterwards?  Or not at all?

It's maybe worth mentioning them in the online instructions.

**Comment by burdges** [comment]
It's just slow joining the matrix room, but works eventually..

chromium installe as an ubuntu snap cannot do web usb

**Comment by thestinger** [comment]
Ubuntu breaks WebUSB with their Snap and they only offer a broken way to enable it by granting the application administrative access to USB which is more than it would have without the Snap.

Compare to using Chromium-based browsers in Android where the OS provides the USB device selection dialog which is used by the browser instead of their own selection dialog, and provides case-by-case access.

**Comment by Ayoahha** [comment]
Hey guys... I'm facing  the same issue. Trying to install graphene os on my pixel 6 via webUSB.
Everything was fine except that it was veeeeery long after the flash.
And i restarted (not sure if it was finished!)
Got the same error message now : "Error: Failed to execute 'open' on 'USBDevice': Access denied."

Btw : via command line, fastboot does not see ANY device. Is it normal ?

Is there any solution ?
I'm completely lost at this point...

**Comment by Zanthed** [comment]
@Ayoahha Please ask for support in our Matrix community, https://grapheneos.org/contact#community

The issue tracker isn't meant for support.

**Comment by burdges** [comment]
I asked here because joining matrix appeared to fail.  It succeeded like 30 min later though.
