### ISSUE TITLE
Remove DSU Loader From Developer Options

### ISSUE THREAD

**Issue by GitHubNevin** [GrapheneOS/os-issue-tracker#1327]
I suggest that this is removed because GrapheneOS does not support DSU (from what I understand)

After attempting to reboot into the DSU, there is a warning on every boot stating that the OS is corrupt and can not be trusted, to proceed you must click the power button

This will happen every time you reboot the phone and to my understanding there is no way to fix this other than factory resetting the device

My suggestion is to either remove, gray out, or add a warning to this feature

I know people may comment that since this feature is in developer options, it should be ignored but this feature literally corrupts the OS or at least makes the OS believe that it may be corrupted

#363 also suggests this

**Comment by Zanthed** [comment]
Really the same thing as #363

**Comment by Zanthed** [comment]
Bumping and creating duplicate issues is not going to change our priorities and we ask that you don't do that.

This is a developer option. It's already known that developer options can and will brick the OS so this just further deprioritises this. We have far more important things to do.

**Comment by Zanthed** [comment]
You're not going to control or change our priorities. Furthermore you are currently misusing our issue tracker by bumping other issues and repeatedly trying to comment here when you're told this is a duplicate issue and we're not going to prioritise this just because you bricked the OS by going into developer options.

If you continue to misuse the issue tracker you will be banned across the organisation.
