### ISSUE TITLE
Camera Shifting In Dark

### ISSUE THREAD

**Issue by seniorm0ment** [GrapheneOS/os-issue-tracker#1337]
Encountering issues with the camera after one of the recent updates.
when in the dark, the camera shifts left and right and the image is always capturing blurry.

Tested on stock camera app, and snapchat same issue. Front and rear.
No issues in daylight.

**Comment by thestinger** [comment]
On which device?

**Comment by seniorm0ment** [comment]
Apologies, Pixel 6 Pro

**Comment by ph00lt0** [comment]
Similar issue on PIxel 4a

**Comment by thestinger** [comment]
Not possible to replicate.

**Comment by thestinger** [comment]
@seniorm0ment The description of shifting left and right sounds like it switching between the main and telephoto lens. If you're in the range of 4x to 7x zoom it could be deciding to switch to the telephoto lens and back. It decides whether it should be used at 4x or above based on light level. It only uses it at exactly 4x in very good lightning, otherwise it raises it higher. The level changes dynamically and could explain what you're seeing. If that's what's happened, it's intended, and it matches Google Camera.

**Comment by thestinger** [comment]
> snapchat same issue

Need clarification on whether you mean the issue also occurs in Snapchat.

**Comment by seniorm0ment** [comment]
The same exact issue occurs with Snapchat's camera. Aka it's not limited to the stock camera app.

Anyways I am not touching any zoom buttons, it's just sitting there shifting back and forth. I don't see it changing view like that. It's almost like it's shifting like a cm to the left then right then back and forth.

**Comment by thestinger** [comment]
Zoom in to 1.1x and see if it still happens. The 3 cameras are right next to each other and it shifts left/right when switching between them. If it shifts even for the front camera, there's no explanation like that one.

You're probably going to need to do a factory reset or install the stock OS to check if the issue still occurs. We can't replicate it on any device.

**Comment by seniorm0ment** [comment]
Not sure what's going on, but i notice the camera just seems to be almost making everything look a little tipsy as if you were drunk. Hard to explain.
I mean I guess I understand what you're saying, what I fail to understand is why this is all of a sudden a new issue as of one of the recent updates. Only started about a month ago I think. Never had issues, and doesn't have issues in daytime.
If what you say is the issue, that doesn't explain what changed that has caused the issue..?

**Comment by thestinger** [comment]
It's very unlikely that it was caused by an update. It could be a hardware issue. It could be a firmware or software bug, but it would have to be something tied to persistent state / configuration since it doesn't happen for other people, and there's hardly any persistent state / configuration for the camera at all. There's not really anything that could be a culprit.

**Comment by seniorm0ment** [comment]
Well @ph00lt0 stated he had a similar issue but i don't know he didn't provide much information. I don't think it's a hardware issue. It seems software/firmware related but I would really like to avoid a reset if possible.
Is there anything else I can test or provide info with?

**Comment by ph00lt0** [comment]
I don't know snapchat but I lately the camera has been very bad in dark environments unlike before. I'll try with gcam later and see if it makes a difference, but I am pretty sure it used to be better and less blurry. 
Not sure what you mean with shifting left and right?

**Comment by seniorm0ment** [comment]
It's hard to tell, but when you're pointing it in the dark it looks like it's shifting. It COULD just be it focusing in and out having trouble but idk. Either way something is wrong with dark environments, the photos do come out blurry for me too. So it is probably the same issue.
