### ISSUE TITLE
Implement Basic Call Recorder as system app

### ISSUE THREAD

**Issue by froman753** [GrapheneOS/os-issue-tracker#1339]
I know call recording has been a frequently requested issue without good implementation. I have stumbled upon this very basic app that would allow native call recording, but requires system app permissions.

I am wondering if it would be possible to add this to Graphene's Apps store to allow the users who want this feature to install it easily as a system app. There should be minimal updates to the app so maintenance should be fairly minimal. 

https://github.com/chenxiaolong/BCR

**Comment by thestinger** [comment]
That's not how that works and is not a possibility.

**Comment by froman753** [comment]
@thestinger so it's not at all possible to add this to the OS with system permissions?

**Comment by thestinger** [comment]
You can't give privileged permissions to an app not included in the OS.

We also aren't even going to consider giving privileged permissions to a third party app.

It's not happening and there's no point trying to ask for anything resembling doing what you're proposing.

**Comment by thestinger** [comment]
You're proposing we turn an untrusted third party app into a privileged component of GrapheneOS. Do you really think that's going to happen?

**Comment by Zanthed** [comment]
We are not doing this.

**Comment by Zanthed** [comment]
Every time there's something regarding call recording, I'm going to repeat what needs to be said:

If you want call recording so badly, then I suggest you start investing your own time and effort and research and development and maybe even paying someone to make a far better implementation that can be submitted to either upstream AOSP or to us and is willing to make any changes that we request.

We're not contract workers, we're not accepting bounties, we're not doing something just because you keep on pinging us about it. We're not integrating random things that seem to keep being proposed that are almost guaranteed far worse implementations that likely have security flaws in them.
