### ISSUE TITLE
USB-OTG and USB-C DAC-to-jack doesn't work on Pixel 3

### ISSUE THREAD

**Issue by lessneek** [GrapheneOS/os-issue-tracker#1361]
USB-OTG and USB-C DAC-to-jack don't work on Pixel 3 with GOS. It shows that it is charging a device. USB security is configured correctly. The same USB flash-drives and DAC-to-jack work flawlessly on Pixel 6 with the same version of GrapheneOS. What causes the problem? It is not the Pixel 3 phone problem, because I have tested it on two Pixel 3. Also the phone had CalyxOS previously installed and the issue was the same.

**Comment by thestinger** [comment]
3rd generation Pixels have been end-of-life since October 2021 and due to Android 13 being right around the corner we've discontinued everything other than basic maintenance. We'll only be taking issue reports for recent regressions for 3rd generation Pixels. Nothing new is going to be developed or improved for them at this point.

Please ask for help [on the discussion forum](https://discuss.grapheneos.org/) and provide more details on exactly what kind of device you're trying to use.

**Comment by thestinger** [comment]
3rd generation Pixels have been end-of-life since October 2021 and due to Android 13 being right around the corner we've discontinued everything other than basic maintenance. We'll only be taking issue reports for recent regressions for 3rd generation Pixels. Nothing new is going to be developed or improved for them at this point.

First, turn off developer options, check the USB peripheral security mode again and reboot.

If you're still having issues, please ask for help [on the discussion forum](https://discuss.grapheneos.org/) and provide more details on exactly what kind of USB devices you're trying to use.
