### ISSUE TITLE
Lastpass Crashes on Login

### ISSUE THREAD

**Issue by SB13X** [GrapheneOS/os-issue-tracker#1374]
Find Bug Report mentions of com.lastpass.lpandroid below:

[Lastpass Bug Report - Copy.txt](https://github.com/GrapheneOS/os-issue-tracker/files/9334206/Lastpass.Bug.Report.-.Copy.txt)

**Comment by thestinger** [comment]
Try turning off exec-based spawning.

**Comment by Neurotic8883** [comment]
I'm having the same issue, doesn't work with exec-based spawning on or off.

**Comment by w-lowe** [comment]
same issue, 
Pixel 3 XL
GrapheneOS - SP1A.210812.016.C2.202201800
Lastpass - 5.11.1.9690

**Comment by thestinger** [comment]
Please try with the exploit protection compatibility mode in the latest beta release. If enabling that works around the issue, it means it's a memory corruption bug in this app.

**Comment by T313C0mun1s7** [comment]
Why was this bug closed? It is still an issue. I just installed GrapheneOS today, 10/2/22 and enabled the three Google applications. Then added my Google account, and finally installed LastPass as my first real app as it is critical to me. It immediately crashes as soon as I entry my password. I see nothing in this ticket that indicates that it has been fixed. just three people other than myself reporting the issue.

**Comment by r3g-5z** [comment]
You were asked to try enabling the new exploit protection compatibility mode on the problematic app and see if that fixes it.

If that fixes it, it's not a GrapheneOS bug. It's an app bug that needs to be reported to them.

**Comment by T313C0mun1s7** [comment]
Ok, and nobody reported back that it fixed it. So why was the issue closed?

**Comment by r3g-5z** [comment]
It's been open for a month with no response, inactive issues get closed if there is no evidence it's a GrapheneOS bug. So if you want to be useful, consider testing what was asked above and reporting back instead of complaining about the issue being closed because there's a lack of evidence and signals that it's a GrapheneOS bug and not an app bug.

**Comment by r3g-5z** [comment]
Even if the exploit protection compatibility mode does not fix it, a crash log needs to be given to make this a valid and actionable issue. So since you admitted you have this issue yourself, why don't you help?

**Comment by T313C0mun1s7** [comment]
@r3g-5z Why are you getting aggressive and argumentative?  That is not helpful. Basic best practices would indicate that when you close an issue, the person doing so give the reason the issue was closed.  Also, the suggestion was given as a troubleshooting step, but without followup there is no reason to assume it was a fix. Finally, of you are going to make a suggestion like "try with the exploit protection compatibility mode" it is generally helpful to also indicate to the person how to find said feature.

**Comment by r3g-5z** [comment]
https://grapheneos.org/usage#bugs-uncovered-by-security-features

**Comment by T313C0mun1s7** [comment]
Thank you. That is an actual helpful response.

**Comment by CelestialStreamer** [comment]
I was able to get LastPass working by going to Settings -> Apps -> LastPass -> and enable "Exploit protection compatibility mode". I understand that this is a symptom of a bug in LastPass and that we'd need to let the developers of LastPass know about this bug in order for them to fix it.

**Comment by dudeitssm** [comment]
Thanks a lot @CelestialStreamer! Worked for me :+1:
