### ISSUE TITLE
No mobile data when connecting to a VPN

### ISSUE THREAD

**Issue by Carphedon** [GrapheneOS/os-issue-tracker#1411]
GrapheneOS TP1A.220624.014 on Pixel 5.

There seems to be a problem with mobile internet when connecting to a VPN. 

When the data connection switches to mobile the connection drops and the VPN keeps reconnecting. Removing the VPN or enabling WiFi enables the data connection again and the VPN connects. 

I have 2 pixel 5's with the same setup and they both have the same problem. 

Already tried:
- resetting internet settings 
- rebooting phone 
- remove and insert simcard 
- changing preferred network type

**Comment by broujos** [comment]
I have this same problem on a Pixel 6 Pro and a Pixel 6a. Using LogCat it seems that there is a network unreachable error when trying to use a VPN on the cellular network. I have tried prepaid sims for MVNOs on other carriers to rule out a carrier issue. I had to factory reset to get it working, but then after applying the next beta it recurred again.

Currently on TP1A.220624.021.A1.2022082301

**Comment by broujos** [comment]
Some information on what I have tried to help prove this is not a network issue (OP please confirm if you are also on Android 13. If you are not, I can delete my responses and create a new defect so as not to confuse your issue):

- Problem with ability to connect to VPN over mobile presented immediately following update to Android 13 on Pixel 6a.
- Rebooted and confirmed VPN over mobile did not work but VPN over WiFi did.
- Disabled kill switch and confirmed with kill switch off mobile data functioned.
- Reset WiFi, Bluetooth, and Network settings, confirmed mobile data, and re-established VPN profile. Unable to connect.
- Connected to WiFi and able to connect to VPN.
- Rebooted and confirmed VPN over mobile did not work but VPN over WiFi did.
- Swapped from eSIM to physical SIM. Loaded SIM in Pixel 6 Pro on Android 12 and confirmed VPN over mobile worked.
- Updated Pixel 6 Pro to Android 13 and VPN over mobile stopped.
- Rebooted and confirmed VPN over mobile did not work but VPN over WiFi did.
- Purchased prepaid SIM on an MVNO that rides a different carrier and confirmed on Pixel 6 Pro and Pixel 6a that VPN over mobile still does not work.
- Rebooted and confirmed VPN over mobile did not work but VPN over WiFi did.
- Removed and reinstalled VPN application and VPN profile on 6a. Confirmed VPN over mobile did not work but VPN over WiFi did.
- Rebooted and confirmed VPN over mobile did not work but VPN over WiFi did.
- Factory reset Pixel 6a and reinstalled VPN. VPN over mobile started working.
- Installed the next update for Android 13 and VPN over mobile stopped working, but VPN over WiFi still works.
- Rebooted and confirmed VPN over mobile did not work but VPN over WiFi did.

**Logcat output for both VPNs tested reports a network unreachable error with or without kill switch enabled.**

This has persisted for me across 2022082100, 2022082200, 2022082300, and 2022082301. Both Pixel 6a and Pixel 6 Pro list MP1.0 as the hardware version.

**Comment by 7ArxS2PrqAUF9Gom** [comment]
Same issue on Pixel 4a 5G, but I discovered that its the "Block Connections without VPN" toggle (in Android Network VPN settings) that does that. You must disable it, reboot your phone, and unlock it to get VPN to work over mobile data. 
Same issue on Pixel 4a 5G, but I discovered that its the "Block Connections without VPN" toggle (in Android Network VPN settings) that does that. You must disable it, reboot your phone, and unlock it to get VPN to work over mobile data. 

The issue is that without that feature enabled, phone makes unsecured connections after reboot until phone is unlocked.  It is normal for VPN to be disconnected until phone is unlocked after reboot, but "Block Connections without VPN" is what prevents unsecured connections until phone is unlocked.

The same issue happens for DNS-over-TLS private servers. If "Block Connections without VPN" is enabled, I can't connect to any DoT servers.

When testing, you need to make sure to reboot phone after switching "Block Connections without VPN" on and off. 
The issue is that without that feature enabled, phone makes unsecured connections after reboot until phone is unlocked.  It is normal for VPN to be disconnected until phone is unlocked after reboot, but "Block Connections without VPN" is what prevents unsecured connections until phone is unlocked.

The same issue happens for DNS-over-TLS private servers. If "Block Connections without VPN" is enabled, I can't connect to any DoT servers.

When testing, you need to make sure to reboot phone after switching "Block Connections without VPN" on and off.

**Comment by gsture** [comment]
> Same issue on Pixel 4a 5G, but I discovered that its the "Block Connections without VPN" toggle (in Android Network VPN settings) that does that. You must disable it, reboot your phone, and unlock it to get VPN to work over mobile data.
> 

For me this does not work. I have to remove the whole VPN before the mobile connection works as it should. 

Besides, connections should not be able to bypass the VPN so this toggle is kind of important.

**Comment by thestinger** [comment]
Don't have an indication of this being a GrapheneOS issue rather than a network issue with DNS or something else.

**Comment by gsture** [comment]
So after android 13 update you get multiple reports of vpn's not working and you automatically assume people are to stupid to try and solve network/dns related issues first? Have you even tried this yourself? I can guaranty you your mobile connection will not work when using some kind of vpn with "block connection without vpn" enabled. This toggle is bugged.

**Comment by thestinger** [comment]
We did a poll in the testing channel and it works fine for the vast majority of users.

**Comment by gsture** [comment]
> We did a poll in the testing channel and it works fine for the vast majority of users.

Ok thank you. Have to wait for more reports then.

**Comment by thestinger** [comment]
Please try various network configuration like disabling or enabling Private DNS, etc.

**Comment by thestinger** [comment]
With which carrier? T-Mobile or one of their MVNOs?

**Comment by gsture** [comment]
No KPN NL and Vodafone NL.

**Comment by broujos** [comment]
Please see the other issue I logged with all my troubleshooting steps. Note VPN worked fine prior to the update and then following the update immediately failed. On a factory reset it worked again. Rebooted and tested multiple times before I started setting up my phone and it consistently worked. Then the next update rolled out and it immediately stopped working.

I tried on T-Mobile and with a Tracphone SIM on AT&T's network and the problem persisted on both carriers.

**Comment by gsture** [comment]
> Provide device and carrier version which does not work:

Pixel 5 + kpn_nl-40000000623.44

**Comment by broujos** [comment]
Hell, if I have to, I will send you one of the two phones I have on GrapheneOS that have this problem... It is affecting my 6 Pro and my 6a. I have output from logcat that I can ship as well.

**Comment by broujos** [comment]
tmobile_us-40000000018.17

I'll get you the other one later today when I can get my hands back on the AT&T Tracphone SIM

**Comment by 7ArxS2PrqAUF9Gom** [comment]
Same issue
- Pixel 4a 5G - tmobile_us-40000000128.44

I think its DNS issue, but why on Android 13 and not Android 12? Why mobile data and not WiFi? 

I provided further findings here - https://discuss.grapheneos.org/d/561-after-update-to-13-vpn-is-broken-6a/8 

I would suggest to at least not enable "Block connections without VPN" by default, something GrapheneOS introduced.

Is there a way to force-update carrier settings to the latest?

**Comment by broujos** [comment]
Logcat shows Network Unreachable. I believe that the VPN app is not being exempted from the Kill Switch route restrictions...

**Comment by thestinger** [comment]
@7ArxS2PrqAUF9Gom We're not going to stop enabling it by default because 1% of users have an issue with VPN + mobile data.

**Comment by thestinger** [comment]
@broujos Have you tried the built-in OS VPN functionality? Since you're using an app, you can't assume that it's an OS issue rather than an app compatibility issue with Android 13. We heard people having issues with VPN apps on Android 13 stock OS. It does not appear to be a GrapheneOS specific issue.

**Comment by broujos** [comment]
@thestinger This is one on my actions out of a discussion on the Alpha/Beta testing channel on Matrix. Unfortunately, I don't believe that I have a service provider that hosts IPSec VPNs, so I will find one to confirm... I will also confirm (noting the carrier settings version at each step along with the VPN application used and the DNS settings used):

* The Pixel 6a that I have which has this problem does or does not have the problem when restored to stock.
* The problem does or does not occur when reflashed to GrapheneOS (Release 2022082100).
* The problem does or does not occur when installing a subsequent OTA.
* The problem does or does not occur when reflashed to GrapheneOS (Release 2022082400).
* The problem does or does not occur when installing a subsequent OTA.

At any step where the problem DOES occur following an OTA I will rollback, repeat the earlier steps, then sideload the OTA on which the problem was experienced to confirm that the problem is repeatable.

It is worth noting that I have 3 Pixels:
* 1 Pixel 6 Pro on Stock Android 13 (No Issues with VPN over mobile with killswitch enabled);
* 1 Pixel 6 Pro on Graphene 2022082400 (VPN fails over mobile with killswitch enabled);
* 1 Pixel 6a on Graphene 2022082400 (VPN fails over mobile with killswitch enabled)

I can also put my hands on a Pixel 5a 5G and a Pixel 4a 5G later today for testing purposes if it becomes necessary.

**Comment by squalus** [comment]
I hit this problem today after upgrading. The Mullvad VPN app no longer works when "Block connections without VPN" is enabled in the settings. To get it to work, I had to turn off "Block connections", connect to the VPN, and then turn it back on.

**Comment by gsture** [comment]
One more thing: If you use a vpn in work profile or use a vpn in both regular and work profile, then the "block connections without vpn" toggle for work profile works without causing trouble with mobile connection. It's only the toggle for main profile that has this behavior.

**Comment by broujos** [comment]
OK, so 2 Pixels that CANNOT connect to VPN by themselves over mobile internet. We'll call them Alice and Bob. If Alice hosts mobile internet over hotspot with the VPN killswitch off and Bob connects to her mobile hotspot over WiFi then Bob can connect to VPN but Alice still cannot. Even if they are the same VPN provider.

**Comment by thestinger** [comment]
This happens on the stock OS and AOSP too:

https://www.reddit.com/r/GooglePixel/comments/wpcy0n/psa_dont_upgrade_to_android_13_if_you_use/

It's not caused by GrapheneOS. We think it's caused by inbound traffic leaks being more thoroughly prevented in Android 13. It's very likely an issue with your carrier's network. Eventually your carrier will likely fix it once a lot of people are on Android 13. The number of people using Android 13 and using a VPN with blocking connections not through the VPN enabled is low, so whatever the cause, that's the reason it hasn't already been fixed as part of the Android 13 betas, etc.

**Comment by realbiz21** [comment]
I have the same issue.

I use OpenVPN for Android (de.blinkt.openvpn / 0.7.39)

What I see is that OpenVPN app log says "Network Unreachable". My VPN servers are specified by IP address, no DNS is involved. The servers are IPv4 addresses.

With a logcat shell, `ip add` shows that I have an IPv6 when Data is enabled (rmnet_data3), but no IPv4 address assigned.

`ip rule` shows routing table 1013 should be used. But that routing table has no IPv4 entries, only IPv6.

logcat does show some NAT64 errors:

```
W resolv  : (113, 3) Detected NAT64 prefix YYYY:[redacted]::/96
D ConnectivityService: NAT64 prefix changed on netId 113: operation=1, YYYY:[redacted]::/96
I Nat464Xlat: Starting clatd on rmnet_data3
E Nat464Xlat: Error starting clatd on rmnet_data3: java.io.IOException: no IPv6 addresses were available for clat: java.io.IOException: Unable to find global source address on rmnet_data3 for YYYY:[redacted]::
E Nat464Xlat: Invalid IPv6 address null
```
YYYY:[redacted]:: is an internet-routable IPv6 address given to my phone by the mobile carrier.

Also seen are some Netd errors:

```
I EthernetTracker: interfaceLinkStateChanged, iface: rmnet_data1, up: true
D ConnectivityService: Adding iface rmnet_data1 to network 113
E Netd    : no such netId 113
W ConnectivityService: Exception adding interface: android.os.ServiceSpecificException: Machine is not on the network (code 64)
E Netd    : no such netId 113
E Netd    : no such netId 113
```

I wonder if the issue is caused when the mobile provider only provides an IPv6 address and Android 13 has broken NAT64?

Maybe if we keep toggling airplane mode the mobile provider eventually assigns an IPv4 address and that's why it sometimes works?

**Comment by thestinger** [comment]
The issue is almost certainly that VPN lockdown is now blocking some part of the negotiation process needed for mobile data for certain users on certain carriers.

**Comment by gsture** [comment]
> I wonder if the issue is caused when the mobile provider only provides an IPv6 address and Android 13 has broken NAT64?
> 
> Maybe if we keep toggling airplane mode the mobile provider eventually assigns an IPv4 address and that's why it sometimes works?

Mate, you gave me an idea. I set the APN protocol to only IPV4 and guess what? It works! 

This is the solution for now. This toggle does not work with Ipv6.

**Comment by thestinger** [comment]
> This is the solution for now. This toggle does not work with Ipv6.

It does work with IPv6. It's a much more narrow carrier compatibility issue than that.

**Comment by gsture** [comment]
At least for me it doesn't so people could at least try this. Maybe it works for them as well.

**Comment by realbiz21** [comment]
@gsture Yes, changing APN to IPv4 works around the issue. Unfortunately my primary cellular provider is IPv6-only.

In any event, the GrapheneOS Twitter account seems to confirm it's a [NAT64 / clatd](https://twitter.com/GrapheneOS/status/1563412965591633920#m) issue, so I don't believe there's anything more we can do aside from waiting for a permanent fix from Google or a temporary revert/patch from GrapheneOS. There's nothing more I will add to this issue.

**Comment by gsture** [comment]
@realbiz21 I read the grapheneos Twitter but this statement is not correct: "We think this may only impact carriers with IPv6 only networks". As I said before it does not work for me and I am not on a Ipv6 only network (how else would I be able to change to IPv4 to work around the issue).

**Comment by thestinger** [comment]
@gsture That's what is meant by an IPv6 only network. By changing to an IPv4 APN you're switching to a different network without the issue.

**Comment by realbiz21** [comment]
In case it may help others, the workaround that I currently use until a solution is available (without temporarily disabling lockdown mode):

- In logcat, get the detected NAT64 prefix (`Detected NAT64 prefix YYYY:[redacted]::/96`)
- I created a duplicate (Open)VPN profile, called it [profile]-cellular
- I updated the host address from IPv4 to IPv6 with the NAT64 prefix
   - Before (IPv4): 1.2.3.4
   - After (IPv6): YYYY:[redacted]:0102:0304
- If I switch to Cellular Data, I activate the above cellular profile.
- When on WiFi, I disconnect from the cellular profile and use the original profile

From what I can tell to describe this issue based on my observations, `clatd` doesn't get network access, and without `clatd` there is no IPv4 route for VPN apps that are set to use IPv4 addresses. I'm unsure why it would affect some IPv6-only carriers and not others.

I use a private VPN that only has an IPv4 address and no DNS name. A commercial VPN with a DNS name likely works (thanks to DNS64 faking AAAA records from A records), though clatd might still be broken - just not noticeable.

**Comment by thestinger** [comment]
For the record, since misinformation is being spread about this topic:

This should be fully fixed in AOSP master and current GrapheneOS releases. It impacts all Android 13 operating systems. We tried some downstream fixes and backports much earlier but it only partially fixed it. Most users were able to work around it via setting IPv4/IPv6 or IPv4 for their APN configuration instead of IPv6 since it only impacted IPv4-via-IPv6 with a specific kind of carrier setup. This wasn't largely deployed by carriers which is why so few users had issues overall. Modern T-Mobile APNs were the main compatibility issues and most users could work around it.

**Comment by gsture** [comment]
I can confirm that this issue is fixed after this update, all is working fine now 👍

**Comment by hrrd** [comment]
since two weeks ago this problem occured for me too. until then i didn't had the problem. in my case i wanted to work around but for me ipv4 was already default and still doesn't work. Carrier is lycamobile.

**Comment by thestinger** [comment]
No, this issue was resolved a long time ago.

**Comment by thestinger** [comment]
If you have a new issue please open a thread on the forum asking for support. It's not this problem.
