### ISSUE TITLE
VPN Connection issue

### ISSUE THREAD

**Issue by Retr00ne** [GrapheneOS/os-issue-tracker#1416]
Pixel 6 with latest GrapheneOS beta latest NordVPN client has connection issues. Can't give you any technical details 
But it started with the switch to Android 13 beta.
At first I could not establish a connection at all but then  discovered that if you set the OS private DNS it would then connect and all was fine until a reboot. When I rebooted the VPN software would stop all connections until it was setup but could not connect again so the work around for me is to disable the VPN until OS has established a connection then restart it. Possible DNS problem?

**Comment by thestinger** [comment]
Doesn't seem like a GrapheneOS issue but rather a carrier / network issue such as a DNS issue as you said or something else.

**Comment by thestinger** [comment]
This happens on the stock OS and AOSP too:

https://www.reddit.com/r/GooglePixel/comments/wpcy0n/psa_dont_upgrade_to_android_13_if_you_use/

It's not caused by GrapheneOS. We think it's caused by inbound traffic leaks being more thoroughly prevented in Android 13. It's very likely an issue with your carrier's network. Eventually your carrier will likely fix it once a lot of people are on Android 13. The number of people using Android 13 and using a VPN with blocking connections not through the VPN enabled is low, so whatever the cause, that's the reason it hasn't already been fixed as part of the Android 13 betas, etc.
