### ISSUE TITLE
Failed reactivation esim

### ISSUE THREAD

**Issue by ndaelman-hu** [GrapheneOS/os-issue-tracker#1425]
On Google Pixel 6 pro, I activated an esim on the system ROM before flashing to Graphene OS. All worked fine, until I turned off the esim to (temporarily) fall back on the physical sim. Now, even with Google Play Services installed, I cannot reactivate the esim. There are 2 different types of behavior:

1. Privileged Esim On: the esim immediately turns off again after initiation.
2. Privileged Esim Off: the esim initiation keeps on running.

Can anybody recommend a workaround (apart from having to flash back to Google Android)? Many thanks!

**Comment by thestinger** [comment]
May be a sandboxed Google Play compatibility issue. If you can provide logs it may be possible to resolve it.

**Comment by ndaelman-hu** [comment]
I'm trying to export it as a bug report, but I'm unsure whether it lists anything about the esim (since it doesn't report as a bug). Is there another log?

**Comment by r3g-5z** [comment]
There needs to be logs provided or a clear method to reproduce this. Due to this not being a widespread issue (no one has upvoted this bug or confirmed this happens to them as well), was filed during GrapheneOS Android 12, no logs provided, and significant improvements to sandboxed Google Play have taken place we're going to assume this has fixed itself.

If this is still an issue, let us know but we need logs to do anything about this or a clear method to reproduce it.
