### ISSUE TITLE
No traffic on mobile data when VPN on

### ISSUE THREAD

**Issue by Wookworb** [GrapheneOS/os-issue-tracker#1428]
Whenever the phone switches to mobile data, no more data comes through. As soon as WLAN is available, the VPN (wireguard and Netguard tested) runs. Before the update to Android 13 everything worked and on a Pixel 4 with normal Android 13 it works without problem.

**Comment by Wookworb** [comment]
Saw #1412 an followed the hint.

**Comment by thestinger** [comment]
This happens on the stock OS and AOSP too:

https://www.reddit.com/r/GooglePixel/comments/wpcy0n/psa_dont_upgrade_to_android_13_if_you_use/

It's not caused by GrapheneOS. We think it's caused by inbound traffic leaks being more thoroughly prevented in Android 13. It's very likely an issue with your carrier's network. Eventually your carrier will likely fix it once a lot of people are on Android 13. The number of people using Android 13 and using a VPN with blocking connections not through the VPN enabled is low, so whatever the cause, that's the reason it hasn't already been fixed as part of the Android 13 betas, etc.
