### ISSUE TITLE
I am unable to connect my vpn through LTE with protonvpn or surfshark

### ISSUE THREAD

**Issue by grapheneuser** [GrapheneOS/os-issue-tracker#1443]
I am using a Pixel 4 and since the recent update, I've been having these problems

**Comment by thestinger** [comment]
Certain carriers have compatibility issues with the improved VPN lockdown on Android 13. This issue is not specific to GrapheneOS and occurs on the stock OS and AOSP too. Turn off VPN lockdown for connecting to mobile data and then turn it back on. It's being worked on, we've made numerous announcements about it and we can't track all AOSP issues on our issue tracker.

**Comment by grapheneuser** [comment]
You're amazing!

**Comment by grapheneuser** [comment]
Did not know you have twitter announcements thank you so much!

**Comment by thestinger** [comment]
Note that if you were trying to post on the forum, that's available here:

https://discuss.grapheneos.org/

The place you posted is the issue tracker for the forum for reporting bugs in it which is why I moved it here to the OS issue tracker.
