### ISSUE TITLE
No wireless or internet connection with new update

### ISSUE THREAD

**Issue by Injectionation** [GrapheneOS/os-issue-tracker#1452]
Build number: TP1A.220624.014.2022083000 Pixel 5a

Upon receiving this and the previous update, phone no longer connects to internet or wireless service upon first unlock. Phone will not regain connection until manually going to Network & Internet -> VPN ->Disable Always-on VPN -> Restart phone with the setting off.

Upon restart with Always-on VPN deactivated, connectivity will return, and VPN can be turned on again, but connection drops throughout the day randomly and never returns until performing the above process again.

**Comment by thestinger** [comment]
Android 13 causes a compatibility issue between VPN lockdown and mobile data with certain IPv6-only APN carrier configurations. It's not specific to GrapheneOS but rather than AOSP issue also impacting the stock OS.

We only track GrapheneOS specific issues and AOSP issues not occurring on the stock OS on this tracker.
