### ISSUE TITLE
Replace aosp calculator with opencalc

### ISSUE THREAD

**Issue by Umlaut512** [GrapheneOS/os-issue-tracker#1469]
Opencalc is more modern compared to stock calculator and has support for dark mode ,light mode and material you.Furthermore it is actively developed .The license is gpl v3 but the dev as agreed to relicense it under apache or gpl v2. If it is ok with you i think it would be wise to replace stock calc with it
https://github.com/Darkempire78/OpenCalc

**Comment by thestinger** [comment]
We expect a calculator to use rationals when possible and high precision decimal arithmetic when it isn't. It would be a downgrade from the current calculator otherwise.

3rd party apps are also rarely aligned with our goals. It's currently GPLv3 so we can't consider it for that reason alone. Android apps can't use GPLv2 without making exceptions because Apache 2 and GPLv2 are incompatible, like Apache 2 and GPLv3. Also, we'd prefer to avoid GPL as a whole.
