### ISSUE TITLE
Google Wallet with NFC not working

### ISSUE THREAD

**Issue by pawelsu8** [GrapheneOS/os-issue-tracker#1506]
Hi, I use a lot of profiles. In one profile "banking" I keep google wallet and Revolut applications. I tried to add a card from Revolut app to google wallet, but it failed - revolut was not redirecting me to google wallet. I tried to enter google wallet - when I pressed on the app icon, it displayed a white small rectangle with a loading circle. I stopped and restarted the app - still the same thing, only the loading circle displays. I disabled battery optimization for google wallet, revolut and the three google play apps downloaded from Graphene AppStore before installing Google wallet - to no avail, still a circle. I disabled the option to pause activity for these five apps - still no effect. I turned on the 39bit allocation mode in the settings of each app - still the same, it displays a loading circle. I restarted the phone - the problem still occurs. I uninstalled google wallet and then reinstalled - still the same, loading wheel. I tried adding a card via revolut app - still the same, revolut does not redirect me to google wallet app. I went into nfc settings and changed the default app to google wallet, then brought the phone close to the terminal - the google pay interface appeared on the phone. I exited the app and wanted to enter google wallet again - only the loading wheel appeared.
I switched to revolut and pressed the option "add card to google wallet" and nothing, zero response. I brought the phone close to the terminal again - the google wallet interface showed up. I pressed the option "add card manually " and then entered revolut card details. When I pressed the "save" button, it displayed a message saying that "a custom Android system has been installed on the phone or the system has been rooted. Google wallet will not work on this phone." I repeated the procedure and again received the same message. I stood at the self-service checkout for a good 30 minutes and ultimately did not pay for my purchases

**Comment by SB13X** [comment]
The issue tracker is not a place to seek support please re-direct your issues to discuss.grapheneos.org so that you can be advised appropriately as to whether your issues need to be placed here or if there are other explanations or options.

GrapheneOS does NOT work with NFC Payments via Google Pay/Google Wallet. To be able to pay by NFC using Googles app the OS must pass FULL SafetyNet compatibility checks. GrapheneOS passes BasicIntegrity but cannot pass the ctsProfileMatch element as our OS has not been whitelisted by Google.

To use NFC payments you should look for an alternative and as mentioned the forum at discuss.grapheneos.org would be the most appropriate resource to use for advice.
