### ISSUE TITLE
TLS Encrypted Client Hello

### ISSUE THREAD

**Issue by andrew-ld** [GrapheneOS/os-issue-tracker#1553]
for https://grapheneos.org/faq#private-dns-visited

- SNI stands for Server Name Indication
- ESNI stands for Encrypted Server Name Indication

SNI is the cause why the domain is leaked during initialization of a TLS connection since it is transmitted in plaintext and this greatly reduces the effectiveness of a secure DNS.

ESNI allows solving this problem by allowing to encrypt the server name that is sent to the TLS server during the connection initialization.

Currently, there are websites that have not implemented this feature, but fortunately enabling it client-side does not break compatibility with servers that do not support it.

My proposal is to enable this feature on the system browser (Vanadium) and if it is possible on the system TLS implementation (boringssl).

resources:
https://www.cloudflare.com/learning/ssl/what-is-encrypted-sni/
https://chromestatus.com/feature/6196703843581952
https://datatracker.ietf.org/doc/html/draft-ietf-tls-esni

**Comment by thestinger** [comment]
It's not standardized yet and is going to be implemented by Chromium so there's nothing for us to do. It's only deployed in practice by Cloudflare and it depends on having shared IPs for multiple hosts to mask which one is being used. IP address is still available so the only privacy it provides is masking the requested server name. It usually only servers to hide minor bits of information such as which subdomain is being used. It only hides the overall service being used when multiple different services are hosted with the same IP address. That's happening with IPv4 largely out of necessity due to IPv4 exhaustion. It's also associated with reduced privacy/security due to shared infrastructure between sites decrypting the connections such as Cloudflare. Possible to do reverse proxying without terminating TLS but that's not available via non-Enterprise Cloudflare and not the normal use case.
