### ISSUE TITLE
Emergency Information Photo/Avatar not being wiped/erased

### ISSUE THREAD

**Issue by GY8VSdYYzvL8-K6T** [GrapheneOS/os-issue-tracker#1557]
Erasing Emergency Information doesn't erase photo/avatar.

**Comment by r3g-5z** [comment]
This isn't a bug rather intentional design by AOSP in the EmergencyInfo app. When you pick a photo for your emergency info, you're actually picking a photo for your user profile (Settings -> System -> Multiple users). The same behaviour would be observed on stock OS if they didn't ship their own proprietary emergency info app (it uses your Google account's photo instead), and all other custom OS's that use the AOSP EmergencyInfo app.

If we decided to erase the photo, it would erase the user profile photo with it because that's what you're picking.

Not really something we want to spend time on since we would need to modify the EmergencyInfo app to separate the user profile photo into an emergency info photo. Upstream AOSP should deal with this themselves.
