### ISSUE TITLE
Android OpenOffice

### ISSUE THREAD

**Issue by gbkelley** [GrapheneOS/os-issue-tracker#1585]
Fails to open or create any docs when Dark Theme is active - hangs (sometimes)

When it does load, it freezes up soon after you start editing text, etc. requiring a full close.

Not playing nice with Android or GOS?

Working fine on Android 10.

**Comment by thestinger** [comment]
Not a GrapheneOS issue. This app has compatibility issues with modern Android due to serious bugs in the app and targeting newer Android versions than it actually supports.

OpenOffice is effectively abandoned and shouldn't be used. It was replaced by LibreOffice. OpenOffice is essentially a scam pretending to be the original project which is LibreOffice. Apache OpenOffice was the fork done afterwards not LibreOffice. Reminds me of what happened to GrapheneOS actually, except the base Apache OpenOffice isn't closed source.
