### ISSUE TITLE
Please re-enable old Quick Settings separate wifi/cell toggles

### ISSUE THREAD

**Issue by tw-hx** [GrapheneOS/os-issue-tracker#1615]
Hi GrapheneOS team,

[Mishaal Rahman of XDA](https://teddit.net/r/Android/comments/x0sv6u/wifi_and_mobile_data_toggles_in_android_13_a/) has successfully tested building Android 13 with the old Settings provider model re-enabled, which allows for separate Wifi and Cellular toggles in Quick Settings. The relevant code is a 2 line patch to [platform_frameworks_base](https://github.com/GrapheneOS/platform_frameworks_base/blob/bff944d05cd47d2b3b713565d3f00d512840d282/packages/SystemUI/src/com/android/systemui/qs/QSTileHost.java#L530).

Many thanks if this could be enabled in Android 13. Android 12 allowed users to opt-in to the old model via ADB; the code is unmaintained but as long as it works, the option is much appreciated.

As to why?

-    The new Internet tile doesn't obviously show connection state at a glance.
-    What used to take one tap to turn off/on now takes 2+ taps.
-    The popup it triggers is poorly designed upstream; if you toggle wifi, the whole popup expands and moves the toggles so it's not intuitive to use.
-    It's reasonable for a security-focused OS to show all active radios directly in the quick settings at a glance, which could be relevant to users' threat models.
-    Lots of people prefer having the Android <=11 tiles :).

There's two open source apps which somewhat work around this with severe limitations:

-    [Wifi QS](https://github.com/rostopira/wifi_qs) which adds a Wifi Toggle only. (Note: To have it show the SSID, manually allow "Always" location permission... this displays the green location warning light so often that it frequently makes all right-sided status bar icons disappear entirely!).
-    [Better Internet Tiles](https://github.com/CasperVerswijvelt/Better-Internet-Tiles) which does both, but requires root or Shizuku, which can both impact the GrapheneOS security model. Also, has Google tracking code (GMS and Firebase Crashlytics).

**Comment by thestinger** [comment]
> It's reasonable for a security-focused OS to show all active radios directly in the quick settings at a glance, which could be relevant to users' threat models.

That's not what this does.

**Comment by thestinger** [comment]
We aren't going to enable the old under the hood model. New toggles would have to be based on the new model, therefore this is not nearly as simple as you're making it out to be since the old ones are incredibly broken with the new model. This isn't what we're going to put significant development resources into. We've already closed this multiple times.

**Comment by OhSoGood** [comment]
Do you know that CalyxOS do it on Android 13? I guess we could get their patch or something equivalent ?

**Comment by thestinger** [comment]
We're aware of the patches for it in LineageOS and elsewhere. It's not planned for GrapheneOS due to it not fitting well into the newer model designed around dual SIM and beyond, potentially multiple Wi-Fi connections, other connections, etc. We spend our time on privacy/security work, not very low impact UI frills. It's literally just 1 extra press which provides more functionality.

Please don't bring up that project on our issue tracker due to their underhanded behavior and harassment towards our developers.

**Comment by OhSoGood** [comment]
Thanks for the quick clarification!

Le 06/12/2022 à 08:34, Daniel Micay a écrit :

**Comment by Filbuntu** [comment]
I know this was not a priority 2 years ago but could this feature request be reevaluated? New users really miss this feature. CalyxOS has reintroduced the tile in Quick Settings (QS). Could their work be used to implement in GrapheneOS and reduce work you?
Thanks a lot for your kind considerations!
