### ISSUE TITLE
Problems with some 2FA apps

### ISSUE THREAD

**Issue by minj** [GrapheneOS/os-issue-tracker#1642]
- Using Nitro FIDO U2F could authenticate against google and github ✅ 
- Bitwarden Webauthn flow ends in the app with "error has occurred" ❌
- Bitwarden TOTP works ✅ 
- Twitcaster claims webauthn not supported in WebView(?) ❌ 
- Twitcaster TOTP ends in Play Store page for the app of all places?! ❌

**Comment by Sn0whax** [comment]
Just to add- Aegis seems to ask twice (quickly) for biometrics then doesn't register fingerprint. You have to tap away from the prompt to scan fingerprint then tap "biometrics" then the corresponding fingerprint scan will work.

**Comment by Sn0whax** [comment]
Aegis appears to have fixed this (on their end, not a GOS issue) my comment may be discarded.

**Comment by nlambert** [comment]
@minj have you found any work arounds?

**Comment by flawedworld** [comment]
You need to install sandboxed Google Play in order to use apps which rely on Play Services to provide security key functionality.

**Comment by nlambert** [comment]
@flawedworld I don't think that's the issue

I have sandboxed google play and it does not work, just as described by op

I have also been reading and found the following: "[In the future, we can also support redirection for more APIs such as FIDO2 rather than only the geolocation service.](https://grapheneos.org/usage#sandboxed-google-play)"

**Comment by flawedworld** [comment]
@nlambert Yes, it works fine for me currently, I did it just now.

**Comment by flawedworld** [comment]
You need to have sandboxed Google Play installed for Bitwarden to work with FIDO keys.

**Comment by flawedworld** [comment]
> I have sandboxed google play and it does not work, just as described by op

We need logs to help here.

**Comment by flawedworld** [comment]
>I have also been reading and found the following: "[In the future, we can also support redirection for more APIs such as FIDO2 rather than only the geolocation service.](https://grapheneos.org/usage#sandboxed-google-play)"

Would mean we implement our own version of FIDO into the OS, which is not going to be a trivial task. For now users need to use sandboxed Google Play if an app implements it that way. It depends on the app.

**Comment by flawedworld** [comment]
@nlambert What kind of security key are you using? What device?

**Comment by nlambert** [comment]
> Would mean we implement our own version of FIDO into the OS, which is not going to be a trivial task. For now users need to use sandboxed Google Play if an app implements it that way. It depends on the app.

Gotcha!

> What kind of security key are you using? What device?

pixel 6a with a yubikey neo (with nfc) and I've also tried with the yubikey u2f fido (the blue ones) connecting them with a dongle (which could have caused the problem, so I tried a second dongle, and a second yubikey u2f)

I'll keep trying, I may be doing something wrong, but this has always worked on other devices.

For now my work around is to disable webauthn 2fa in my bitwarden account. Using TOTP as a workaround.

Does it matter if bitwarden and chrome are installed through the play store or aurora store? I tried both btw.

And for what it's worth I also read through the following recommendations of yours https://github.com/GrapheneOS/os-issue-tracker/issues/1273

**Comment by flawedworld** [comment]
>chrome 
Chrome is not needed.

Will get someone to look at this.

**Comment by nlambert** [comment]
I tried with Chrome and Firefox (same result) because with Vanadium nothing would happen: never any prompt to hold the key to the back of the device or to touch the button.

With Firefox and Chrome webauthn was active/working, but "error has occurred" appeared at the very end.

**Comment by flawedworld** [comment]
@nlambert Just to confirm, you have properly installed sandboxed Google Play? (i.e you have Play Store, GMS and GSF -- all 3 apps are installed?)

**Comment by nlambert** [comment]
![Screenshot_20230218-104728](https://user-images.githubusercontent.com/1281337/219875326-6a4a293d-0ad8-40db-af5f-736864054338.png)

Seems to be working well

**Comment by minj** [comment]
Fyi I got Bitwarden to work after a while and don't care about twitcaster much any more

**Comment by Opening-Button-8988** [comment]
Hello, 

Can someone confirm that the only way to use hardware security keys on GrapheneOS is to add the keys to your Google account?

I distinctly remember being able to use security keys on my phone without Google. Since when was this mandatory? If there's no workarounds for this, this really sucks. I want to have isolated profiles where I log into sensitive accounts such as Bitwarden, Tutanota, ProtonMail, etc., and having to have a Google account on that same profile and add my keys to that account is a privacy concern for me. I don't care that it's "sandboxed". I don't really see how Google is truly sandboxed if you're able to add security keys to your google account via Vanadium browser. And while I've heard from some sources that there isn't any privacy concern when using security keys, I've heard otherwise from other sources. Firefox has an option to anonymize your security key - I don't even know what that means or why they thought it was necessary.

Anyway, this really sucks and I would **really** like this see a proper workaround. We should be able to use security keys without being tied to Google.

**Comment by thestinger** [comment]
@Opening-Button-8988 

You only need your security keys on a Google account to use them for logging into a Google account. It's simply not true. Apps can use security keys on GrapheneOS the same way as elsewhere. There are apps using them on their own, but most apps use them via the Play services FIDO2 implementation. Any app can provide a similar FIDO2 implementation. I'm not sure why you keep talking about Google accounts when that's never required.

> Anyway, this really sucks and I would really like this see a proper workaround. We should be able to use security keys without being tied to Google. I use security keys for the same reason I use GrapheneOS, and GrapheneOS is designed to help you avoid Google.

Security keys do not require a Google account and have nothing to do with it. Security keys require an app to support them. Most apps choosing to use Play services for FIDO2 is not something new and not something GrapheneOS chooses.

>  I don't care that it's "sandboxed". I don't really see how Google is truly sandboxed if you're able to add security keys to your google account via Vanadium browser.

Not how it works at all and simply FUD.
