### ISSUE TITLE
Disable notifications by GmsCompat

### ISSUE THREAD

**Issue by fthiesse** [GrapheneOS/os-issue-tracker#1650]
Hi,

using GrapheneOS on Pixel 7 (latest version).

There's 2 notifications I'd like to disable/hide:
- GmsCompat permanently displays a note saying "Sandboxed Google Play is running"
- GmsCompat regularly (multiple times a day) displays a notification about a "google service for AR" app that wants to be installed.

How can I disable these? They aren't shown in the list of where regular apps appear.

**Comment by thestinger** [comment]
> GmsCompat permanently displays a note saying "Sandboxed Google Play is running"

It's a regular notification in a dedicated channel. You can long press it and disable the notification channel.

> GmsCompat regularly (multiple times a day) displays a notification about a "google service for AR" app that wants to be installed.

You have an app installed depending on AR services so the Play Store tries to install it. You really don't want to disable the notification used to show that the Play Store tried to install an app in the background and is waiting for you to either approve or deny the request. You'll end up with an indefinitely stalled Play Store if you ignore it. The easiest solution is installing the AR services dependency. You likely installed Google Camera or another app depending on it for some of their functionality and requesting that Play services installs it. AR services is essentially a component of Play services. In most cases, Play services downloads/updates those kinds of components within one of their sandboxed app data directories as dynamite modules, but AR services is separate seemingly so that the OS can have special integration which we don't provide.

> They aren't shown in the list of where regular apps appear.

It's shown if you toggle on showing system apps but you can also reach the same place via long pressing a notification and pressing the settings button. You can also toggle the channels right there instead of going to the full notification settings.

**Comment by thestinger** [comment]
Please use discuss.grapheneos.org for support questions instead of the issue tracker going forward.
