### ISSUE TITLE
[Feature Request] Require PIN to open selected apps

### ISSUE THREAD

**Issue by Techy444** [GrapheneOS/os-issue-tracker#1655]
Require a PIN when opening selected installed apps.

Thank you

P.S: Sorry if this is not the correct area to request features

**Comment by thestinger** [comment]
This isn't a planned feature because it doesn't fit into the security model in a proper way. You should use separate user profiles for apps you want to keep protected while using the device regularly. Secondary users each have their own encryption keys and are kept at rest when the user isn't logged in. Even after you unlock them, you can end session to put them back at rest. That's a meaningful, working approach to locking a single app or set of apps separately from the others. Doing it within a profile by simply requiring a PIN to access the app really doesn't work and it's misleading for users that apps pretend that's working without a complete implementation like the Molly app.

**Comment by Techy444** [comment]
> This isn't a planned feature because it doesn't fit into the security model in a proper way. You should use separate user profiles for apps you want to keep protected while using the device regularly. Secondary users each have their own encryption keys and are kept at rest when the user isn't logged in. Even after you unlock them, you can end session to put them back at rest. That's a meaningful, working approach to locking a single app or set of apps separately from the others. Doing it within a profile by simply requiring a PIN to access the app really doesn't work and it's misleading for users that apps pretend that's working without a complete implementation like the Molly app.

that makes complete sense, thank you for explaining that to me! Sorry i'm new to Graphene. I will look up instructions on how to do this.

Thanks again!

**Comment by thestinger** [comment]
Enable Multiple users in Settings -> System.

**Comment by Techy444** [comment]
> Enable Multiple users in Settings -> System.

thank you, set it up!

One question, on the new user profile (non owner) if I have facebook messenger installed and I receive a message while on the owner profile, is it supposed to send a notification to me while i'm using the owner profile? I have "send notifications to current user" checked off.

**Comment by thestinger** [comment]
Notifications are per-profile and GrapheneOS adds that toggle for forwarding them. To forward them, you need to checked in the profile you want to forward from and it will appear in all the others.

There's a chat bubble feature that's buggy and appears across profiles. That's an upstream Android issue with user profiles which started with Android 13 if I recall correctly.

**Comment by Techy444** [comment]
> Notifications are per-profile and GrapheneOS adds that toggle for forwarding them. To forward them, you need to checked in the profile you want to forward from and it will appear in all the others.
> 
> There's a chat bubble feature that's buggy and appears across profiles. That's an upstream Android issue with user profiles which started with Android 13 if I recall correctly.

okay, thank you very much!

**Comment by thestinger** [comment]
You could just turn off chat bubbles for now if that's the issue.
