### ISSUE TITLE
Toggle to disable proximity sensor for selected apps

### ISSUE THREAD

**Issue by popogomo** [GrapheneOS/os-issue-tracker#1695]
When using any messenger, for example, Signal, the proximity sensor turns on when listening to voice messages or using video chat in picture-in-picture mode.

As a result its impossible to navigate the phone during picture-in-picture calls or when listening to voice messages on the background as proximity sensor kicks in and turns off the screen every time it detects finger nearby (the sensor area is quite big in Pixel 7).

Revoking Sensor permissions from messengers doesn't help.

Is it possible to implement a dedicated toggle/permissions to disable proximity sensor for a specific app to fix the issue?

**Comment by firefoxlover** [comment]
Check if the permission "sensors" solves it. Under App settings, permissions, three dots top right menu, shows advanced view.

**Comment by esntngv** [comment]
I use Signal intensively and I was also very annoyed by the problem that every time I came near the proximity sensor, the speaker switches and the display goes off.

I removed access to "Sensors" in the app settings and now Signal no longer registers when I get close to the proximity sensor, nothing happens.

**Comment by esntngv** [comment]
@popogomo 
For me, the sensor also stops responding in Telegram and Whatsapp as soon as I deactivate "Sensors", it definitely can't be a general problem. I was therefore, as I said, also very annoyed until I changed it.

**Comment by thestinger** [comment]
Signal uses the OS call integration feature so the OS is handling it.

**Comment by thestinger** [comment]
Sensors does include proximity sensor. Apps handling screen rotation, etc. aren't reading the sensor data themselves but rather using OS features handling it for them.

**Comment by JSchimmelpfennig** [comment]
If I revoke the sensor access for the Signal app, the proximity sensor doesn't work anymore. I'm using a Pixel 6a. This is good for playing voice messages loud of when I'm on a phone call over Signal with my bluetooth headset, but for calls over the phone (not the loudspeaker) it would be good, if the sensor could be used.

**Comment by firefoxlover** [comment]
@JSchimmelpfennig then you should ask Signal about that. Its not graphenes task to fix that behavior and change permissions depending on headphone connection state. Permissions are for security and not comfort, apps themselves can detect that state and change their behavior, for example VLCs **awesome** plug-and-play / disconnect-and-stop feature.

**Comment by JSchimmelpfennig** [comment]
Thank you for answering my question! I didn't know that am I'm going to forward that to the signal developers.

**Comment by thestinger** [comment]
@popogomo Please stop pinging issues without adding any information, especially without reading the whole thread.

**Comment by thestinger** [comment]
Not able to reproduce any issues. Suggest reinstalling the app and disabling Sensors.

**Comment by meganjordan** [comment]
This issue is still active so I would like to add: 

Proximity sensor is useful specifically in non speakerphone non bluetooth phone calls. In no other situation is it useful. Yet, popular apps employ it in plenty of other situations. For many people, that means the majority of their interactions with proximity sensor based screen blackening are an inconvenience rather than an aid. Since so many apps have this bug/feature, an OS-side fix could be really useful for a lot of people, as it would fix this issue for potentially hundreds of apps at once.

For those of us who are willing to put up with the slight inconvenience of a lack of a proximity based display in those situations (maybe because I'm someone who never takes non speakerphone calls) it could be useful to literally just have a "disable proximity sensor" switch in the settings app. Even if such a switch disabled the proximity sensor for typical phone calls, the pros outweigh the cons for many people

As mentioned in previous comments, the Sensors permission for these apps does not impact this behavior, as the app receives proximity sensor data from the OS rather than by directly interfacing with the sensor. In Developer Options, one can disable the OS from interacting with any sensors whatsoever. This setting does actually address the problem. However it provides too many downsides, as it disables all sensors at once rather than allowing you to choose which sensors to disable. What people want is the ability to only disable the proximity sensor.

The current implementation means that in order to fix a bug that makes it impossible to tap the search bar on a web browser while on a speakerphone call, I must enable a setting which disallows me from using my microphone. You can understand how a lack of a microphone is an inconsiderable tradeoff for a prozimity sensor issue that primarily affects voice calls. 

All people are saying is this:

Feature request: Add a toggle in Developer Options which solely enables or disables the proximity sensor on the device on an OS-wide level.

**Comment by meganjordan** [comment]
> > As mentioned in previous comments, the Sensors permission for these apps does not impact this behavior, as the app receives proximity sensor data from the OS rather than by directly interfacing with the sensor. In Developer Options, one can disable the OS from interacting with any sensors whatsoever. This setting does actually address the problem. However it provides too many downsides, as it disables all sensors at once rather than allowing you to choose which sensors to disable. What people want is the ability to only disable the proximity sensor.
> 
> It does change this if apps are using the proximity sensor. Give an example where it doesn't work.


open a signal call. connect bluetooth headphones to it. disable sensors on signal. attempt to put finger near top of screen without screen turning black. it doesnt work.

**Comment by meganjordan** [comment]
> > Feature request: Add a toggle in Developer Options which solely enables or disables the proximity sensor on the device on an OS-wide level.
> 
> We won't be adding new developer options and we recommend against having developer options enabled for production usage.

It doesn't even have to be implemented as a Developer Option. That was my example because that was where the other working sensor toggle is. But early Android versions used to have this exact toggle in general settings under a subheading "Call settings". It doesn't seem unreasonable to do similar here.

**Comment by firefoxlover** [comment]
@meganjordan yes, this is really confusing and true.

Detecting if the phone has no cover may also be helpful for apps to track the behaviors of people. 

Example: spam SMS messages when a person is right about to go to sleep.
