### ISSUE TITLE
"Flashlight" is a not-existing but indexed setting

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#1712]
Pretty poor, in Android 12 you can activate the flashlight by long-pressing the power button when the screen is off. This is not possible and the setting is not existent, but shown.

**Comment by thestinger** [comment]
> in Android 12 you can activate the flashlight by long-pressing the power button when the screen is off

No, that's not a feature available in AOSP 12 or the Android 12 based stock Pixel OS. Similar to the other request (swapping button) this isn't a standard Android feature and never has been. We have no plans to add it since it's easy to pull down the quick settings to use it. It would be a waste of the long press binding to hard-wire it to this.
