### ISSUE TITLE
GrapheneOS webinstaller doesn't work

### ISSUE THREAD

**Issue by mollyuser** [GrapheneOS/os-issue-tracker#1717]
Hi, on the website grapheneos.org it says GrapheneOS is supporter for installation. But the web installer cannot detect the phone when connected to usb. Tried this several times, also with the help of a moderator. He also did not undrrstand what was wrong.

**Comment by mollyuser** [comment]
So from an GrapheneOS pixel to a google pixel, just to clarify. The webinstaller never detects the phone so grapheneOS is not supported as stated for installation.

**Comment by thestinger** [comment]
If your browser isn't detecting the other phone, that's not an issue with the web installer since that's not part of the web installer. You need to follow the instructions including booting the phone to fastboot phone and use a working cable. Avoid cables from other products since most aren't standards compliant. Please read the information on USB in the install guide and also in the GrapheneOS FAQ. If you disabled USB peripherals completely with our toggle for that, it's why it's not working. If you plugged in while the screen was locked or allowed the screen to lock during the install before it reconnected, that won't work with the default denial of USB peripherals while locked.

Please use our Matrix chat room or discussion forum for further support requests. The issue tracker isn't for support and this isn't a bug.

**Comment by mollyuser** [comment]
I ve brought this up in the GrapheneOS room and was helped by a moderator called matchboxbananasynergy, he also could not make this work. We ve tried al the above, original USB cable, allow USB peripherals, plug in the cable when device is unlocked. It just doesnt detect a device. I feel pretty stupid reporting these things, like no one in GOS room has a answer how to male this work. Maybe you should try this yourself before sating it works fine, because it does not work. I will try the GOS room once again for support.

**Comment by thestinger** [comment]
Our web installer works fine and what you're reporting is that the browser / OS doesn't see the USB device which is not a web installer issue. If the OS UI opens and doesn't show it, that fundamentally cannot be a web installer issue.

**Comment by mollyuser** [comment]
Sorry my bad, web installer works fine, just GrapheneOS doesnt support the web installer and should not have been between supported operating systems. Like i sayd, tried this multiple times, even with a moderator, it doesnt work. GrapheneOS doesnt support webinstaller and there is no way to install GrapheneOS from a GrapheneOS device. Just test it yourself and u will see.

**Comment by thestinger** [comment]
GrapheneOS supports it just fine. It's regularly tested. The lack of a bunch of free memory on a phone does lead to it not being great at flashing Android 13 to a Pixel 6 or Pixel 7 due to the required memory though.
