### ISSUE TITLE
Set custom servers...

### ISSUE THREAD

**Issue by helter-shelter** [GrapheneOS/os-issue-tracker#1730]
Hello,

Could you please add the options to set custom,
Connectivity Check Server,
NTP Servers,
and DNS servers,

We have these already running in production and would like to use them.

Thank you!!!

**Comment by thestinger** [comment]
You can already choose a DNS-over-TLS server.

You inherently get updates from GrapheneOS for the update client and app repository. It doesn't make much sense to replace the connectivity check servers or HTTPS time updates which simply make a GET request to the same infrastructure.

NTP isn't used due to lack of NTS support in the AOSP implementation.

Feature requests without a rationale will almost always be closed.

**Comment by helter-shelter** [comment]
Hello,

The DNS-over-TLS server can be overridden by the carrier DNS servers in tests. The rationale is that we need to get as much as possible talking to our infrastructure in-house as we are trying to move over about 300 corporate phones to GraphineOS (Would like to anyway) but it needs approval of our PCI auditors before we can proceed as they are deemed not secure enough if they are talking to an outside infrastructures for anything other than updates. I appreciate your reply and i guess we will just have to use CalyxOS or maybe LiniageOS as they both can support those options after speaking with the developers.

Thanks for your time anyway and happy holidays!

**Comment by thestinger** [comment]
> The DNS-over-TLS server can be overridden by the carrier DNS servers in tests

Network-provided DNS is only used for network setup including connecting to the DNS server.

@helter-shelter Okay, you're welcome to use highly insecure operating systems not providing proper security updates and misleading users about. Promoting them on our tracker in an attempt to coerce us is not okay.

**Comment by thestinger** [comment]
If you want to discuss it further you can contact @strcat:grapheneos.org on Matrix.

It is not correct that DNS-over-TLS is overridden by network DNS.

GrapheneOS does not use NTP.

Connectivity checks and HTTPS network time updates are both implemented by fetching an empty 204 response via HTTP(S) from the same infrastructure as our update servers. It could literally use the update servers.

If you want to instead use insecure operating systems without proper security updates, which certainly aren't hardened and which always use multiple Google services, go ahead. It's not clear what you want to achieve and I would suggest being rational instead but you do you.

**Comment by helter-shelter** [comment]
Hello,

We followed the process and requested some features in which you declined and closed the ticket. If you are not interested in adding the featured as requested I appreciate that and will move on. We would love to use GraphineOS in our project but you denied/closed the request. If you are interested in adding those features then by all means we will still use GraphineOS. I understand about the NTP part but would still need the others to point to our infrastructure.

Thanks for your time.

**Comment by thestinger** [comment]
If you want us to add a feature, you need to hold a conversation about it to explain why you need it and provide rational reasoning for it so that we understand the use case and consider how to fulfil that. If you instead to try promote insecure projects which mislead their users about security and are involved in abusive behavior, that comes across as coercion, not cooperation or requesting something. I also cannot understand why you would be fine with using an OS using multiple Google services with no opt-out but you aren't fine with using one that already provides controls over this functionality.

**Comment by thestinger** [comment]
@helter-shelter Contact at @strcat:grapheneos.org if you want to have a discussion about this. You don't seem aware of the full set of default connections used by AOSP-based operating systems or GrapheneOS, or particularly operating systems bundling additional services in the OS which you promoted as an alternative...
