### ISSUE TITLE
Remove fingerprint as an unlock method choice in UI

### ISSUE THREAD

**Issue by e-t-l** [GrapheneOS/os-issue-tracker#1741]
Humans are way too predictable when they choose to use biometric locks out of convenience despite being easily spoofable and completely insecure to the single most common hacking vector, thus drastically reducing the security of the device. A hypothetically secure element can't really compensate for a very poorly chosen unlock option. 

According to [this study](http://biometrics.cse.msu.edu/Publications/Fingerprint/CaoJain_HackingMobilePhonesUsing2DPrintedFingerprint_MSU-CSE-16-2.pdf) (which, it should be noticed, was published within a year of the [study](https://www.lancaster.ac.uk/staff/wangz3/publications/ndss_17.pdf) @Wonderfall cites), a significant number of users utilize fingerprint lock technology instead of a PIN or non-alphanumeric cryptography like a pattern lock. It also experimentally shows that this unlock method is inherently very vulnerable to spoofing. Additionally, [US courts have ruled](https://www.bloomberglaw.com/public/desktop/document/United_States_v_Barrera_No_19_CR_439_2019_BL_451168_ND_Ill_Nov_22?doc_id=XT0HLCP0000N) that law enforcement may compel, with thread of violence, any individual to unlock their phone using biometrics if that vector is present. While not all GrapheneOS users reside in the USA, this renders plain the very obvious fact that social engineering and, more broadly, _human vulnerability_ is the single most common attack vector exploited by hackers. There is absolutely nothing to stop a bad actor from compelling a user to unlock their phone biometrically, either through deception or violence (at the very least, a person cannot enter their PIN or pattern lock if they have been clubbed unconscious. The same security _cannot_ be offered by biometrics). Plenty of other studies have shown this in general.

The option to choose a biometric unlock method should just be removed from the UI to discourage users from using it, as they should use PIN or password instead (although it's worth noting that humans are very poor at remembering randomly generated passwords. Furthermore, humans are far too predictable at choosing memorable passwords, as studies have shown that a majority any given population uses [the same common, easily-guessable passwords](https://www.cnbc.com/2022/11/23/most-common-passwords-of-2022-make-sure-yours-isnt-on-the-list.html)).

**Comment by e-t-l** [comment]
Bonus: this should be very easy to integrate into GrapheneOS, as the basic code modifications have already been designed in [PR #49](https://github.com/GrapheneOS/platform_packages_apps_Settings/pull/49).

**Comment by thestinger** [comment]
There's no option to use biometric unlock as the primary unlock mechanism. It's only available as a secondary unlock mechanism. Users always have to set a PIN or passphrase as their primary unlock method before using it. Biometric unlock can only be used after the profile has **already** been unlocked and hasn't been logged out. If a profile is at rest (logged out, data inaccessible to OS due to encryption), it cannot be used. GrapheneOS already changed it so that it gets locked out after 5 failed attempts, and there's the standard lockdown feature to disable it another way. Rebooting or the end session feature for secondary users that we enable are even better options getting data back at rest. There's also a standard 48h timer from the last unlock via primary unlock method where biometric unlock is disabled, and we already have an issue about making this configurable:

https://github.com/GrapheneOS/os-issue-tracker/issues/14

We also have a feature about 2-factor secondary unlock, which we see as quite valuable to enable using a strong high entropy passphrase not depending on secure element throttling as the primary unlock method with fingerprint + PIN as a convenient secondary method without the caveats of fingerprint unlock and also which can't simply be shoulder surfed:

https://github.com/GrapheneOS/os-issue-tracker/issues/28

We won't be removing secondary unlock support but rather building on it. This has little to do with pattern unlock which was very misleading and not genuinely useful like this.
