### ISSUE TITLE
Allow Access to Android data folder (To protect your privacy, choose another folder)

### ISSUE THREAD

**Issue by bugreporting** [GrapheneOS/os-issue-tracker#1778]
I use Solid Explorer to copy data from my device (using ftp over lan), however, when I do so I am no longer able to give access to the data folder on the device. (Appears to be upstream)

From what I have found on Google, people have suggested rooting the device/using an older version of the Files app.

https://www.reddit.com/r/AndroidQuestions/comments/qk9n44/to_protect_your_privacy_choose_another_folder_fix/

![Screenshot_20221203-224130](https://user-images.githubusercontent.com/65435240/205474993-bf60caaf-f382-4b5a-8bec-b923ba2def5b.png)

**Comment by thestinger** [comment]
This isn't the correct way to request access to this data. To be clear, this is also not internal app data but rather only data apps choose to store in their largely obsolete scoped external storage directory. There's rarely a good reason to store data there since it's significantly slower and it's better to support the standard backup API which is close to being mandatory for targeting Android 12+, or to provide an alternate export/backup mechanism.
