### ISSUE TITLE
[pixel 4 - flame] Face unlock stopped working since version ~2022112500

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [GrapheneOS/os-issue-tracker#1780]
The face unlock feature has stopped detecting any faces, a couple of updates prior.
It started having difficulties working with the previously fine, registered face model, but after deleting it and trying to re-register one, as stopped detecting any faces whatsoever.
Do note that I started adding a face model for my professional profile around the same time the issue occurred, so this could also been a potential reason, but I have not real coalition between those two events.

**Comment by thestinger** [comment]
We haven't gotten any other reports about face unlock not working. This may be a hardware failure. There are dual infrared scanners, a dot projection and flood illuminator providing 3D face scanning. If any of these break, it would likely stop working. The only way to fully rule this out would be a factory reset to make sure it's not caused by state corruption in the OS, etc. and then if it's still occurring trying the stock OS. There's a fairly high chance this is the problem. I know it would be quite annoying to confirm that, since we only have a lackluster backup/restore service included and many apps still aren't updated to API 31+ despite the Play Store requiring it since November (API 31 addresses the issues with the previous backup configuration system for apps and makes it so that nearly all apps should now be compatible).

Our recommendation is to delete the face models for all profiles where you have them registered. It may not work correctly in the work profile which may have screwed it up globally, we aren't sure about that. Since face unlock is ONLY implemented by the Pixel 4 and Pixel 4 XL, which are now in extended support, this is going to be a low priority for us.

**Comment by thestinger** [comment]
Our recommendation is to start by deleting the face models for all profiles where you have them registered. It may not work correctly in the work profile which may have screwed it up globally, we aren't sure about that. Since face unlock is ONLY implemented by the Pixel 4 and Pixel 4 XL, which are now in extended support, this is going to be a low priority for us. You could also try deleting the whole work profile.

We haven't gotten any other reports about face unlock not working. This may be a hardware failure. There are dual infrared scanners, a dot projection and flood illuminator providing 3D face scanning. If any of these break, it would likely stop working. The only way to fully rule this out would be a factory reset to make sure it's not caused by state corruption in the OS, etc. and then if it's still occurring trying the stock OS. There's a fairly high chance this is the problem. I know it would be quite annoying to confirm that, since we only have a lackluster backup/restore service included and many apps still aren't updated to API 31+ despite the Play Store requiring it since November (API 31 addresses the issues with the previous backup configuration system for apps and makes it so that nearly all apps should now be compatible).

**Comment by PoorPocketsMcNewHold** [comment]
> Our recommendation is to start by deleting the face models for all profiles where you have them registered. It may not work correctly in the work profile which may have screwed it up globally, we aren't sure about that. Since face unlock is ONLY implemented by the Pixel 4 and Pixel 4 XL, which are now in extended support, this is going to be a low priority for us. You could also try deleting the whole work profile.
> 
> We haven't gotten any other reports about face unlock not working. This may be a hardware failure. There are dual infrared scanners, a dot projection and flood illuminator providing 3D face scanning. If any of these break, it would likely stop working. The only way to fully rule this out would be a factory reset to make sure it's not caused by state corruption in the OS, etc. and then if it's still occurring trying the stock OS. There's a fairly high chance this is the problem. I know it would be quite annoying to confirm that, since we only have a lackluster backup/restore service included and many apps still aren't updated to API 31+ despite the Play Store requiring it since November (API 31 addresses the issues with the previous backup configuration system for apps and makes it so that nearly all apps should now be compatible).

I understand, I was going to correct that I indeed deleted the face profiles, but knew that this was a legacy feature not supported by GrapheneOS anymore *(Same with gestures that I intended to write a report too #457)*
Thanks for the quick answer.

**Comment by thestinger** [comment]
@PoorPocketsMcNewHold It is likely either a hardware failure or an OS bug where the state has been corrupted in a way that it can't handle. If a factory reset resolved it, it would be an OS bug. If not, then it's almost certainly a hardware failure which could be confirmed by trying the stock OS. Aware that this would be quite painful to test so not really expecting you to bother with it.
