### ISSUE TITLE
more energie safe by varios of ways

### ISSUE THREAD

**Issue by Nonie689** [GrapheneOS/os-issue-tracker#1793]
for google tensor

tool like kernel tool manger
undervolting

a boytum  for ultra energie safer loke muui

ram tweasf

scheduler

no all app after restart

apps in hibernate

**Comment by thestinger** [comment]
There's already a standard Android restricted battery mode for apps which does far more than disabling an app starting via the boot completed broadcast. There's already support added in GrapheneOS for disabling user installed apps to fully prevent them running, since in restricted battery mode another app can still start them.

Not clear what everything else is that you're asking for but this stuff is either already provided or not wanted for GrapheneOS.
