### ISSUE TITLE
Pixel 5a shuts down by itself since Dec 8, 2022 OS update

### ISSUE THREAD

**Issue by SapientHetero** [GrapheneOS/os-issue-tracker#1809]
Thursday night I installed the latest GrapheneOS update. My phone functioned normally at home, where I was connected to WiFi, the rest of that night and Friday. Then I left home Friday afternoon and not long afterward my Pixel 5a abruptly turned itself off. One moment it was running, the next it was completely off. I assume the OS crashed. I restarted it and noticed it displayed a date 2 days earlier until it connected to the T-Mobile network, shortly after which it crashed. It did this repeatedly each time I restarted while waiting at a traffic signal.

Once I arrived at my destination I restarted my phone and it operated normally on the T-Mobile network without a WiFi connection. When I left for home it ran normally all the way home.

I've taken two trips since then and each time my phone crashes when I leave home, works fine when I arrive at my destination and on the way home. Don't know if it matters, but I have a very weak cell signal at home. 

I've had GrapheneOS on this phone for over a  year and this has never happened before.

**Comment by vi13nce** [comment]
Same problem on pixel 5
As per the original post, the phone shuts down if connected to the mobile network. I have to keep mobile data turned off or the phone will shut down. The one exception is when the phone was plugged in when you turn it on and it connects to the mobile network. The issue seems to occur sporadically even when mobile data is off, but blutooth, and wifi are both connected. 
Every time the phone shuts down, the clock is set back to 1:47AM local time, Wed. 7 Dec. when I turn it back on.

**Comment by lndshrk** [comment]
With a few days testing over a 200+ mile route, the only common denominator is that with airplane mode activated but with WiFi turned on, there are no shutdowns.  The WiFi is actually connected to another phone acting as a hotspot.

With airplane mode off, and using the cellular network, there are random shutdowns.

They do not seem often enough to correlate with EVERY tower handoff.  I have locked my 5a into "LTE Only" mode for the next days tests.

**Comment by SapientHetero** [comment]
Good idea. I set my 5a to "LTE Only" today after taking a 4th trip during which my phone shut down by itself and reading your post. I was able to get home without it shutting down.

**Comment by lndshrk** [comment]
Same here.  "LTE only", 200 miles and 12 hours through 3 counties, and not a shutdown.  It's definitely related to NOT ("LTE Only") mode.

**Comment by buckohfive** [comment]
This is exactly happening to me as well. Has anyone tried to flash the Nov 2022 radio over the Dec update? I'm not always moving when it crashes, but it does seem to be tied to signal or network handoffs (BT, Wifi, cell).

**Comment by r3g-5z** [comment]
@buckohfive You're on stock OS and this is happening as well?

**Comment by buckohfive** [comment]
> @buckohfive You're on stock OS and this is happening as well?

Correct. I updated to the Dec 2022 pixel 5a update from Google and this happened.

**Comment by r3g-5z** [comment]
> Does Graphene force update to the latest radio? I feel like this is a flaw either in the radio firmware update, or in how the radio and app processor interface.

We always use the latest firmware provided by stock OS.

**Comment by lndshrk** [comment]
I think there is some scuttlebutt, some question as to if they (Google) actually held off pushing this Dec 2022 OTA to existing Pixel 5a phones.

**Comment by r3g-5z** [comment]
It impacts both Pixel 5 and 5a.

**Comment by r3g-5z** [comment]
It's unclear why this issue seems heavily underreported online for 5th-gen devices, if this apparently impacts stock OS and other OS's that use the latest firmware, except for a Reddit comment from 7 days ago that may or may not be related: https://www.reddit.com/r/GooglePixel/comments/zapd1z/pixel_5_turns_off_in_the_middle_of_the_night/izhs4pt/

Current workaround seems to be use LTE-only mode, but if this is confirmed to be a firmware issue then we're very limited on what we can do about this. Downgrading firmware is not a valid solution.

**Comment by buckohfive** [comment]
I manually updated my Pixel 5a to the December 2022 firmware through a full update (not side loaded OTA).

> I think there is some scuttlebutt, some question as to if they (Google) actually held off pushing this Dec 2022 OTA to existing Pixel 5a phones.
> […](#)
> On December 16, 2022 12:59:37 PM MST, r3g_5z ***@***.***> wrote: > Does Graphene force update to the latest radio? I feel like this is a flaw either in the radio firmware update, or in how the radio and app processor interface. We always use the latest firmware provided by stock OS.

**Comment by lndshrk** [comment]
Okay well to me, the question is: is this update being pushed to Pixel 5a's that are on the stock OS without manual intervention. In other words is it being pushed out as a normal update to everyone. The rumor and I repeat rumor is that it is not being pushed out to the 5a's for some reason.  Do we know of anyone on the pre-Dec official stock OS on a 5a that has had the Dec update pushef to them?

**Comment by r3g-5z** [comment]
I'm not sure what you're asking. December update is on Pixel 5a stock OS: https://developers.google.com/android/images#barbet

**Comment by lndshrk** [comment]
Okay, at risk of taking this off track which I am hesitant to do. Let's say that you are the average Joe and it is November and you have a pixel 5A running on the November update. You are the average Joe. You do not sideload. You do not directly load the OS from the developer site. In other words you're not one of us. This is the example. It is said and I repeat said with no verification that people in that situation are not being pushed the December 2022 update if they have a 5A. Hopefully that makes sense. Of course I'm not up on how updates are pushed to phones so it could very well be the carriers that aren't pushing that update, I don't know.

**Comment by buckohfive** [comment]
> Okay, at risk of taking this off track which I am hesitant to do. Let's say that you are the average Joe and it is November and you have a pixel 5A running on the November update. You are the average Joe. You do not sideload. You do not directly load the OS from the developer site. In other words you're not one of us. This is the example. It is said and I repeat said with no verification that people in that situation are not being pushed the December 2022 update if they have a 5A. Hopefully that makes sense. Of course I'm not up on how updates are pushed to phones so it could very well be the carriers that aren't pushing that update, I don't know.

Android Firmware updates are generally pushed by the cell network service provider. Pixel devices are different in that Google sends the updates themselves. There are sometimes carrier specific updates.

**Comment by lndshrk** [comment]
The original post is deleted, but the comments should raise an eyebrow.

https://www.reddit.com/r/GooglePixel/comments/zkvh8i/december_update_for_pixel_5a/

What carrier do the affected people have?  If it's an MVNO, what carrier does it run on?

(T-Mobile, here)

**Comment by SapientHetero** [comment]
T-Mobile on my 5a.

**Comment by Guns-Ablazin** [comment]
I've had the same crashing problem on a Samsung Galaxy J7V around June or July 2022 and also one my Pixel 4XL GrapheneOS early November 2022. Before they started crashing they froze while I was using them. On the J7 after restarting it showed an unlock bootloader message instead of the normal bootup. On subsequent bootups it went back to the normal screens. I assumed my phone was hacked and reset it to factory, but it would still auto reboot when I had it connected to a Samsung T7 SSD. After buying the Pixel 4XL with Graphene OS preinstalled and connecting it to the T7 it said that the SSD was corrupted and had to be formatted, but it also said the same thing for a brand new Sandisk SSD.

When my Pixel 4XL froze and started crashing I also reset it in the Graphene OS. It hasn't auto reset since then. I've transfered everything from my T7 to the Sandisk SSD on a linux laptop and formated the T7 on the Pixel 4XL. I also stopped using my family's WiFi, which I think was the culprit. Someone with access to the network must have hacked my phones and my family is to stupid or unwilling to secure it properly. I've noticed a lot of strange behavior on all of my devices when connected to any public or private WiFi that I didn't have control of.

Whatever the cause there must be an exploit common to Android OSs.

**Comment by flawedworld** [comment]
@Guns-Ablazin  Not relevant

**Comment by buckohfive** [comment]
> The original post is deleted, but the comments should raise an eyebrow.
> 
> https://www.reddit.com/r/GooglePixel/comments/zkvh8i/december_update_for_pixel_5a/
> 
> What carrier do the affected people have? If it's an MVNO, what carrier does it run on?
> 
> (T-Mobile, here)
> 
> Edit: and another one
> 
> https://www.reddit.com/r/GooglePixel/comments/zmpnrq/halfway_through_december_and_still_no_sign_of_the/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

Google Fi is T-Mobile/Sprint (effectively the same carrier now).

**Comment by lndshrk** [comment]
Noting that forcing the radio to "NR/LTE" mode also seems to not (with a sample of one day) have the shutdown issue.  I'll give it a few days and then switch in WCDMA and GSM as well.

**Comment by flawedworld** [comment]
If you have a crash, post your region and your carrier please.

**Comment by lndshrk** [comment]
T-Mobile ,- Utah/USA

**Comment by seriousastronaut** [comment]
Pixel 5, T-Mobile, Colorado, USA

**Comment by Mhandis** [comment]
Pixel 6a, Google Fi (T-Mobile), Los Angeles, CA

**Comment by SapientHetero** [comment]
Pixel 5a, Orlando, FL, T-Mobile.  

Not sure whether to think this bug is T-Mobile related, or if most GrapheneOS users subscribe to T-Mobile because a year ago reports suggested WiFi calling under GrapheneOS didn't work with other carriers because they use proprietary WiFi calling apps.

**Comment by lndshrk** [comment]
For those who have T-Mobile, if you are still having the crashes and HAVEN'T changed any settings, what do you see for your preferred networks in test mode?  Mine is currently "NR/LTE" but i don't remember what it was originally TBH.

**Comment by flawedworld** [comment]
Well that's a pattern... Okay my advice it to use LTE Only for now. My suspicion atm is that LTE <-> 3G handover and/or LTE <-> NR handover is causing this. I've seen 2 people mention that LTE/NR configured in the ```*#*#4636#*#*``` menu stops the crashing too, so you could try that instead. Either way, this issue seems to affect the stock OS and GrapheneOS, so it's likely something you will need to wait for Google to fix unless we can come up with a solution ourselves rather than the former mentioned mitigation.

**Comment by lndshrk** [comment]
Can someone tell me what the "standard" setting is/was in test (4636) mode?

After successfully testing "NR/LTE" mode for days, I've now switched to "NR/LTE/GSM/WCDMA" mode.

I'm curious what these phones are set to out of the box, and i don't remember.

Test it until it breaks again.

**Comment by SapientHetero** [comment]
Following a recent GrapheneOS update I switched my Pixel 5a back to  the 5g setting and can verify that the problem still exists.

**Comment by flawedworld** [comment]
> Can someone tell me what the "standard" setting is/was in test (4636) mode?
> 
> After successfully testing "NR/LTE" mode for days, I've now switched to "NR/LTE/GSM/WCDMA" mode.
> 
> I'm curious what these phones are set to out of the box, and i don't remember.
> 
> Test it until it breaks again.

You can revert it to the default by selecting the top option (5G iirc?) in the user facing menu in "Network and Internet" in Settings.

**Comment by lndshrk** [comment]
Fair enough.

The "normal" mode is:

"NR/LTE/CDMA/EvDo/GSM/WCDMA"

We know that both "LTE Only" and "NR/LTE" work as a temporary kludge.

I'm trying "NR/LTE/GSM/WCDMA" mode.

Personally unsure why either EvDo or CDMA were/are there in the first place.

**Comment by lndshrk** [comment]
"NR/LTE/GSM/WCDMA" mode started crashing, so i reverted to "NR/LTE" which is ALSO now crashing.

Note that there was a GOS update in there.

Now back to "LTE Only".

**Comment by Guns-Ablazin** [comment]
Reprogrammed Google devices having "glitches" on a Google owned network... Not unlike Google to make changes that affect open source apps/devices

**Comment by thestinger** [comment]
@Guns-Ablazin Stop spreading baseless FUD here.

**Comment by tybach** [comment]
Having the same issue on t-mobile with a pixel 5a.  Going to try and force LTE Only mode to see if it works.

**Comment by tybach** [comment]
Confirmed that setting LTE Only fixes the issue on my pixel 5a on t-mobile

**Comment by buckohfive** [comment]
The latest Pixel 5a firmware dropped today from Google. No mention of any issues wrt radios or LTE, or fixing outstanding issues. Has anyone tried it yet? Has Graphene  complied from upstream sources fixed this LTE issue?

**Comment by r3g-5z** [comment]
A new GrapheneOS release will be out soon.

**Comment by buckohfive** [comment]
> The latest Pixel 5a firmware dropped today from Google. No mention of any issues wrt radios or LTE, or fixing outstanding issues. Has anyone tried it yet? Has Graphene complied from upstream sources fixed this LTE issue?

I loaded the Jan 2023 Pixel 5a firmware update and it does not/not fix the LTE issue. My phone shut down today after switching back to 5G mode post update.

**Comment by r3g-5z** [comment]
Try the latest GrapheneOS release, currently in alpha.

**Comment by Alkali-V2** [comment]
Can someone test something for me?  If you are on T-Mobile, or Google Fi with Tmo towers, if you have a physical SIM card try removing it and running it on an esim.  There are instructions on how to do it on the T-Mobile website.

We've been discussing this issue in the LineageOS 20 thread over on XDA and one of the members posted this link: https://www.reddit.com/r/Tello/comments/y7aki5/i_found_a_potential_fix_for_5g_being_enabled/

Taking an idea from that post, today I tested removing my physical SIM and downloaded an esim on Google Fi.  I discovered that I didn't run into any shut downs or crashes even leaving the device on mobile data for over 10 hours leaving it in 5G with LTE hand-off.  This is just another potential workaround but there does seem to be an issue in my anecdotal case where a physical sim tower hand-off causes a hard shut down/crash. If someone else can corroborate this result this might help narrow down the issue.

**Comment by elizagamedev** [comment]
I don't know how much this adds to the conversation, but I've been having this issue plus another--I can't actually connect to LTE/5G period; I've been stuck on 3G only for about a month. I'm using Ting, which uses the T-Mobile network, which this issue seems to affect in particular. I'm curious if there are other users who have had similar issues.

**Comment by flawedworld** [comment]
> I don't know how much this adds to the conversation, but I've been having this issue plus another--I can't actually connect to LTE/5G period; I've been stuck on 3G only for about a month. I'm using Ting, which uses the T-Mobile network, which this issue seems to affect in particular. I'm curious if there are other users who have had similar issues.

@elizagamedev  Regarding being unable to connect to LTE/5G networks, this is a different issue totally. Suggest reading https://grapheneos.org/usage#carrier-functionality

**Comment by elizagamedev** [comment]
@flawedworld Thanks for the advice, but I've already been through all those steps to no avail, which made me wonder if this issue was the cause instead. I guess I can pester them to send me a new SIM card though.

**Comment by SapientHetero** [comment]
Have you tried an eSim? I think T-Mobile supports them and wonder if it would make any difference.

------- Original Message -------

**Comment by buckohfive** [comment]
> > The latest Pixel 5a firmware dropped today from Google. No mention of any issues wrt radios or LTE, or fixing outstanding issues. Has anyone tried it yet? Has Graphene complied from upstream sources fixed this LTE issue?
> 
> I loaded the Jan 2023 Pixel 5a firmware update and it does not/not fix the LTE issue. My phone shut down today after switching back to 5G mode post update.

For awareness, the February Pixel 5a Google Firmware update does NOT solve the issue. I'm still set to LTE only to prevent random shutdowns.

**Comment by kevinfiol** [comment]
I'm on CalyxOS and also having this problem. Switched to LTE in the meantime.

**Comment by mturilin** [comment]
What's interesting is that after switching to Boost which also uses T-Mobile network I don't have any shutdowns.

**Comment by kurtisnotcurtis** [comment]
At this point I would prefer to rollback to an Android 12-based build of GrapheneOS until the upstream issue is resolved to regain some reliability. I assume someone must have done so by now; does anyone have a process they could share to do that? Would I need to reinstall all apps after downgrading?

**Comment by thestinger** [comment]
You can't downgrade the OS version. There is also no maintained Android 12 branch of GrapheneOS. The last official Android 12 release of GrapheneOS was in August 2022 and Android itself has only provided the non-device-specific portion of the Android Security Bulletin patches for Android 12 since August 2022. Clearly it isn't a serious option to roll back to Android 12.

https://grapheneos.org/releases#2022081800

**Comment by thestinger** [comment]
@SapientHetero You'll be banned from the issue tracker and the rest of our community platforms if you concern troll again.

**Comment by kurtisnotcurtis** [comment]
Thanks for the quick response. 

In my case, I have a Pixel 4A 5G, and changing the preferred network type to "LTE Only" does not fix the issue for me; reboots seem less likely, but are still occurring somewhat regularly when the battery is below ~50%.

I suppose this is a reality for all Pixel users who are not on the latest flagship devices. Based on my needs, I will consider adjusting my security model to avoid automatic OTA updates moving forward, particularly in anticipation of new major Android releases the device did not ship with, for a set period of time until the build appears stable on the target device. Not ideal from a security standpoint, but then again there is always a compromise to be made between security and usability in real-world applications.

Thanks for contending with these upstream issues @thestinger . Upstream issues aside, GrapheneOS has been rock solid, it's a pleasure to use.

**Comment by thestinger** [comment]
It has been half a year since Android 12 was released and it would be extremely bad to be missing months of important privacy and security updates. Perhaps you should switch carriers if it bothers you that much.

**Comment by ilusions4** [comment]
My Pixel 5a on GrapheneOS issue sounds similar, but I'm not sure whether it's the same one. Randomly, the phone will crash, go back to the Graphene logo, and boot up with no apps open.
After moving to "LTE Only" on the 5a, I get reboots less often, but they still occur (even when above 50%). I'm not on T-mobile.

I thought "LTE only" had fixed the issue, so I used the phone as a gps; the phone crashed and rebooted on the highway at 96% battery.
I turned off the SIM card entirely (as I haven't transferred my main SIM over as of yet) and have received a couple crashes+reboots since then.

**Comment by thestinger** [comment]
@kurtisnotcurtis This issue also wasn't caused by Android 13 which was released in August. It was caused by Android 13 QPR1 released in December. Android 13 QPR2 will be available soon and will probably resolve the issue. This issue is not specific to GrapheneOS. It impacts the stock Pixel OS and other AOSP-based operating systems.

**Comment by buckohfive** [comment]
> 

Sometime recently Google dropped the .D2 variant of the February firmware update (for Pixel 5 this is 13.0.0 (TQ1A.230205.001.D2, Feb 2023, T-Mobile, T-Mobile MVNOs)).  I have tested it on my Pixel 5a and can confirm it fixes the shut down issue for me.  I am on Google Fi (T-Mobile).

**Comment by SapientHetero** [comment]
That’s great news. How would a T-Mobile customer running GrapheneOS on a Pixel 5a obtain and install this update?

**Comment by thestinger** [comment]
Wait for the March release on Monday.

**Comment by SapientHetero** [comment]
I would love to switch back to Verizon, but I live in a low signal-strength zone for all carriers and must use WiFi calling for all calls from home.

When I first installed GrapheneOS the website said WiFi calling only worked on T-Mobilewithout a carrier-specific app that wasn't available for GrapheneOS,.

Is the situation any different now, or did I misunderstand?

------- Original Message -------

**Comment by thestinger** [comment]
Wi-Fi calling works fine on most carriers. Many people have reported it works fine on T-Mobile.

**Comment by lndshrk** [comment]
> Wait for the March release on Monday.

QPR2 (seems to have) stopped shutdown mania, but seems to have introduced a new failure mode.

If 5g is enabled, the phone simply pretends that there is no signal on a random basis (in the middle of a large metro area where there is certainly signal).

Rather, you have "5G" and "bars" (but no data), then you have the exclamation point, then it drops to Edge (still no data) and if you pray hard enough (or enable/disable airplane mode) it will come back.

Again "LTE Only" seems to "fix" this.

A snoop into 4636 indicates "unable to get config" regarding NR network slicing.

4636 also has the usual provisioning buttons greyed out now.

**Comment by flawedworld** [comment]
If you continue to have this specific issue please let us know, provide your build number, carrier and region. Closing now.
