### ISSUE TITLE
enable forcing traffic through always on VPN by default

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#183]

**Comment by juliangaal** [comment]
Is this setting VPN independent? When going to `Settings -> Network -> Advanced -> VPN` I can enable `Always-on VPN` and `Block connections without VPN` in the specific vpn app (in my case wireguard). You mean to make this the default for all VPN apps that are listed in the settings tab mentioned above?

**Comment by thestinger** [comment]
@juliangaal Yes, it's VPN-independent, although only one can be configured as the always-on VPN at a time. It will preserve the state of the toggle when always-on isn't enabled but it won't do anything and will be grayed out.

**Comment by thestinger** [comment]
It's very unlikely that the setting is stored by the Settings app, so the file you linked is the wrong place to change the default. You'll need to look at the fragment implementation for managing this setting and figure out where the default needs to be changed. It often needs to be changed in a couple places, i.e. the underlying implementation and then also in Settings for display.

**Comment by juliangaal** [comment]
for future reference: [services/core/java/com/android/server/connectivity/Vpn.java](https://github.com/aosp-mirror/platform_frameworks_base/blob/5d30d86372163a9513aba828bdafab42e5d1099b/services/core/java/com/android/server/connectivity/Vpn.java#L148)

**Comment by jcpicard32** [comment]
I'm very new to security focused work, but this seems like a decent starting point. Is there any reading that people can recommend me? I should have slightly more time and would like to start contributing in whatever way I can.

**Comment by valldrac** [comment]
Please review both https://github.com/GrapheneOS/platform_packages_apps_Settings/pull/14 and https://github.com/GrapheneOS/platform_frameworks_base/pull/26.

These PRs enable by default the VPN lockdown setting. It only takes effect when always-on is also enabled. It remembers the preference of the user, and the control is greyed when always-on is off. Note that if a VPN app configures a tunnel with always-on, the default can be overwritten (see lockdown parameter in [setAlwaysOnVpnPackage](https://developer.android.com/reference/android/app/admin/DevicePolicyManager#setAlwaysOnVpnPackage(android.content.ComponentName,%20java.lang.String,%20boolean))).

**Comment by thestinger** [comment]
@valldrac I had to roll this back because it was causing problems when a VPN isn't being used.

**Comment by valldrac** [comment]
What kind of issues? I guess you're not refering to #213 but something else.

**Comment by thestinger** [comment]
Internet access not working without a VPN installed.

**Comment by anupritaisno1** [comment]
@valldrac I went through your commits and I see something strange 

Look at this for instance:
https://github.com/GrapheneOS/platform_frameworks_base/commit/e454e255c3be5e7a66ab7805904dafc5fc433e5f#diff-ccd35c3068009b098da2943d63940f8dR513

Why did you make the setting independent of the always on VPN? The issue title says that we want to enable VPN lockdown when always on VPN is enabled. Again, read the issue title. Your proposed fix is going in a completely different direction to the actual issue 

The default value should be false here https://github.com/GrapheneOS/platform_packages_apps_Settings/pull/14/commits/cf46fb26f8c418f41153f03e6d0c183a6cd863bc#diff-9e1d97f9d1161da2c99681e00aa27107R37 because always on VPN isn't enabled by all users 

Making the lockdown setting independent of always on VPN and then enabling it by default is definitely what causes the no network without VPN issue

**Comment by anupritaisno1** [comment]
@valldrac we need a solution where enabling always on VPN enables VPN lockdown by default. We don't need a solution that disregards always on VPN and just enables the lockdown everywhere. Again, see issue title

**Comment by frkt3m** [comment]
Can this issue be reopened again? It doesn't seem to be resolved at all by the commit linked

**Comment by thestinger** [comment]
I think we had to revert the change?

**Comment by Penguin-Guru** [comment]
For what it's worth, I also think this behaviour should be default for always on V.P.N.

**Comment by quh4gko8** [comment]
This has been implemented at https://github.com/GrapheneOS/platform_frameworks_base/commit/0bd1dbf60fe641dbdd7f60b77ace71c3328c7e37?
