### ISSUE TITLE
Pixel 6 Camera crashes after taking a picture

### ISSUE THREAD

**Issue by venfls** [GrapheneOS/os-issue-tracker#1844]
If you take a picture the screen freezes and the phone reboots. There's no error message. 

I started with the GOS Camera and then also installed GSF and GCam. Same. 

It doesn't seen to matter what orientation. I also tried clearing memory and cache. 

Main problem is: It isn't always and it isn't reproducible - after all I haven't found a way.

Is there a place to look for a crashlog or something?

**Comment by thestinger** [comment]
This sounds very much like a hardware issue because it's not reproducible and we aren't getting reports from other people.

**Comment by thestinger** [comment]
Unless other people are having these kinds of issues or there's more information available, there's not much we can do about this. There's unlikely to be any crash log available if the phone is actually fully rebooting.

**Comment by seifertm** [comment]
I can confirm the issue. It happens every now and then when taking pictures. I experience the issue ever since I switched the Pixel 6 to GrapheneOS. It just never bothered me.

Lately, I need to occasionally record videos, though. The issue happens very frequently when using the Video functionality, either when starting the recording or when stopping it.

I'm happy to provide any information that helps debugging, if you give me a few pointers.

**Comment by venfls** [comment]
To report back: I switched back to Google Stock ROM and installed the same version of the Google Camera App as I had on GrapheneOS.  The App crashed more infrequently but nevertheless. So I sent it back and ordered a Pixel 6 Pro, because I already had one running GrapheneOS without any problems. They are both running quite smoothly since...

**Comment by thestinger** [comment]
Likely a hardware issue then. If the camera had a loose connection that was disconnecting it would explain the crashes.
