### ISSUE TITLE
Storage Scopes for OpenNoteScanner

### ISSUE THREAD

**Issue by baermathias** [GrapheneOS/os-issue-tracker#1845]
I installed an app called OpenNoteScanner and set the permissions for it as follows:

- Allowed -> Camera
- Not Allowed -> Files, Network, Sensors etc.

Inside Files I have configured a scope: `storage/Documents/scans`
Now if I create a scan, the app automatically stores those scans to a folder called `storage/OpenNoteScanner`

Even if I remove the scope (which means, that the app has no longer files permission), it still stores scans. 

This is confusing because the file permissions scope setting tells me that the app only has access to the scoped area.
And if scopes are off, then it should not be possible at all to create files.

If this is the intended behaviour, Files should be renamed to `Read Files` and next to it, it should be an info that `Write Files` is always on, regardless what you do.

**Comment by thestinger** [comment]
Please read https://grapheneos.org/usage#storage-access. It explains how the standard Android storage system works and how Storage Scopes fits into it. We're not going to be changing the standard storage systems.

Adding scopes with Storage Scopes is unnecessary unless you need the app to access files from other apps. Scopes are for accessing files from other apps. Our feature is designed to fit into how the system already works and this is intentional. Apps can write files and read their own files. Storage Scopes expands where they can write files to where they could write them if you granted the requested storage permissions. Even without Storage Scopes they can still write files to special media locations.

**Comment by thestinger** [comment]
We're aware that the standard Android storage permission system is quite complex. We've done a good job documenting it and there's not much else we can do about that. Storage Scopes is designed to fit nicely into the existing system in a sensible way. It is not meant to be a whole new way of doing things but rather a **complete alternative** to granting any storage permissions where *no scopes need to be granted* for apps to work*, only for them to see files from other apps.
