### ISSUE TITLE
Suggestion to Implement a System-Wide Permission Access Logger Akin to Notification History

### ISSUE THREAD

**Issue by Syberkonda** [GrapheneOS/os-issue-tracker#1850]
I would like to see a feature akin to notification history that logs every time apps use permissions. I have an app (or multiple) that keeps accessing my location at random times in the background, and I would like to know what that app is so I can see if I need to restrict its permissions. Sometimes a similar thing happens with the microphone as well. I only know about this because of the green indicators, and would like a breakdown of which apps are accessing permissions like these along with exact timestamps.

**Comment by r3g-5z** [comment]
This feature already exists as a standard AOSP feature called "Privacy Dashboard" in Settings -> Privacy -> Privacy dashboard.

You can click on the permission in question and see what app and when it used said permission.

GrapheneOS extends this AOSP feature by checking all available permissions instead of just Location, Camera, and Microphone.
