### ISSUE TITLE
Google Camera shutter lag and long portrait processing on Pixel 7 Pro

### ISSUE THREAD

**Issue by MisterrrX** [GrapheneOS/os-issue-tracker#1853]
Taking pictures with the Pixel 7 Pro using Google Camera introduces enormous shutter lag and around 40 seconds long processing for portrait shots.

**Comment by thestinger** [comment]
Has already been reported and is a Google Camera limitation on the Pixel 7 hardware without having privileged access. Doesn't happen on other Pixels and we expect them to fix it. We aren't providing it privileged access.

**Comment by MisterrrX** [comment]
Why though? I understand security is GOS' biggest concern, but this heavily degrades the camera experience and Google, being Google, most definitely won't do something about it.

**Comment by thestinger** [comment]
Giving privileged access to Google apps goes against what we're supposed to be providing. We don't currently plan to do it. We could perhaps somehow provide a toggle but it's not clear how to implement it for this case.

**Comment by thestinger** [comment]
If someone is interested on working on a toggle for privileged Google Camera access, they're welcome to do that, but it's not a bug and not something we plan to do ourselves therefore we don't want issues, especially multiple issues, open about it. We can document it as a known limitation on the Pixel 7 and Pixel 7 Pro which we expect to be resolved by Google Camera in a future update and which may (unlikely) have the option to toggle on privileged access (this appears quite complex and unrealistic to implement).

**Comment by thestinger** [comment]
If someone is interested on working on a toggle for privileged Google Camera access, they're welcome to do that, but it's not a bug and not something we plan to do ourselves therefore we don't want issues, especially multiple issues, open about it. We can document it as a known limitation on the Pixel 7 and Pixel 7 Pro which we expect to be resolved by Google Camera in a future update and which would be possible to work around if we added the option to toggle on privileged access. Unfortunately, making that kind of toggle is far harder than the privileged eSIM toggle we provide because unlike the privileged eSIM toggle it cannot be based on disabling those eSIM apps by default since it's an optional feature for Google Camera, not mandatory.

**Comment by MisterrrX** [comment]
Yeah an update to the documentation would be great as GCam is documented to be working fine, even though that's not the case on the Pixel 7 models. Thanks for your hard work though, been loving GrapheneOS so far!

**Comment by thestinger** [comment]
The camera documentation is out-of-date and is missing information on the current GrapheneOS Camera feature set along with not having any information about the Pixel 7 and Pixel 7 Pro. We expected the Portrait mode issue to be fixed by them already.
