### ISSUE TITLE
Disabling CDMA (cdmaOne, CDMA2000) support

### ISSUE THREAD

**Issue by neelchauhan** [GrapheneOS/os-issue-tracker#1883]
I don't know if this idea would work, but considering that CDMA networks have been shut down in most parts of the world, for phones that have CDMA support, I propose disabling the CDMA codebase for devices which support CDMA, namely the Pixel 4, 4a, and 5 series devices.

This could reduce the attack surface by disabling a lot of legacy code, however there may also be no real way to use this code since there's no way to connect to a 3G CDMA network. Most CDMA carriers have either moved to 4G LTE (Verizon/KDDI) or 3G UMTS (Bell/Telus).

This would not disable WCDMA, as it's still in use.

**Comment by r3g-5z** [comment]
This might be doable since Verizon is pretty much done fully phasing out CDMA infrastructure and at this point people will have very noticeable issues on stock OS either way.

https://www.verizon.com/support/knowledge-base-218813/

> As previously communicated, Verizon is actively decommissioning our 3G CDMA network. We expect this to be completed by no later than December 31, 2022. This decommissioning effort affects 3G (CDMA) devices, 4G Non-VoLTE devices, and network extenders.

> Starting the day before your December 2022 bill period begins, if you are a Verizon customer using a 3G CDMA or 4G phone device that does not support HD Voice (Non-VoLTE), your line will be suspended without billing, and the device will no longer make/receive calls, send/receive text messages, or use data services. You can see your billing period on the [Bill overview](https://www.verizon.com/digital/nsa/secure/ui/bill/viewbill/) page in My Verizon. Until **January 1, 2023**, impacted phones will still be able to make 911 emergency calls, and calls to Verizon Customer Service (*611 and 1-800-922-0204), while the line is suspended.
Impacted 3G (CDMA) devices and 4G Non-VoLTE phones will remain suspended without billing until **February 2023**. Starting the day before your February 2023 bill cycle begins, any remaining impacted lines that are still suspended without billing will be disconnected.

**Comment by flawedworld** [comment]
Users wanting to do this are going to be expected to use the LTE Only mode at the moment.

**Comment by thestinger** [comment]
This will be handled by the end-of-life of these devices. Pixel 4 and 4 XL are already end-of-life.
