### ISSUE TITLE
WLAN Bug

### ISSUE THREAD

**Issue by Lullaby22** [GrapheneOS/os-issue-tracker#1887]
Hallo, seit Monaten habe ich das Problem, mich mit einem WLAN, egal welches, zu verbinden.
Die Zugangsdaten passen.
Ab und zu klappt der WLAN Login und ich kann dann darüber im Internet surfen.
Aber meistens klappt es nicht.

Ich gehe wie folgt vor: ich gehe auf Einstellungen, Internet und versuche das WLAN zu aktivieren. Manchmal lädt er keine WLAN Netze oder die Option WLAN aktivieren, lässt sich nicht aktivieren.

Wenn das der Fall ist, versuche ich meine Netzwerkeinetellungen oben recht, im Einstellungsmenü unter Internet, zurück setzen.

Danach klappt meistens nicht mehr das Mobile Internet, WLAN gar nicht. 
Ich starte das Smartphone danach neu.
Ich habe einen VPN aktiviert, diesen habe ich dafür auch deaktiviert. Es hat nicht geholfen.

Ich möchte gerne für euch Log Dateien posten, weis aber nicht, wo ich sie her bekomme.

Ich nutze ein google pixel6a mit aktuellem grapheneOS Stand heute.

**Comment by thestinger** [comment]
You need to use reset options to reset the network settings, and then start fresh. Remove your Private DNS or VPN configuration if you've changed those. You're assuming that this is a bug rather than a configuration issue with your device or network which is not a good assumption to make. There's no indication of a bug here and no reports from others about any similar issue which is an extremely strong indication that's not the problem. It's better to ask for help with this on discuss.grapheneos.org and please translate your post to English so other people understand it without translating it themselves as I've done for this.

**Comment by Lullaby22** [comment]
Im sorry for my bad! I try it. And next time the next question, i will post it in the another part and in english. Thanks for helping!
