### ISSUE TITLE
Rapid Battery drain issue

### ISSUE THREAD

**Issue by aleeasaleeas** [GrapheneOS/os-issue-tracker#1892]
Since the update of my pixel 6a to version TQ1A.230105.001.A2.2023010300, I noticed that the phone screen randomly lights up (although I have deactivated all gestures) and the battery is drained rapidly. In the battery settings it mentions that the CPU usage is abnormally high, which is probably the reason why the device runs hot. Upon further searching, it seems that the device has trouble entering deep sleep.

**Comment by thestinger** [comment]
This is almost certainly an issue caused by your apps and configuration, not an OS bug. Others aren't experiencing this. There's nothing we can do with this issue report especially without logs and lots of other data from a bug report zip, etc. No reason to think it's an OS bug right now though. You're assuming it was caused by an update but it's not likely.
