### ISSUE TITLE
Bluetooth fails to connect to older device

### ISSUE THREAD

**Issue by qdrop17** [GrapheneOS/os-issue-tracker#1895]
Hello there.

Since **TQ1A.230105.001.A2.2023011000** (or maybe TQ1A.230105.001.A2.2023010300), my Pixel 6 Pro can't connect to my Car (7-year old Hyundai i30) anymore. Frist it connects and also shows the Bluetooth icon on the car's display, but before the audio channel gets up, it loses the connection.

Then my Pixel 6 Pro says that the connection failed and I shall try to reboot the phone to fix the problem.
Unfortunately that does not fix the issue; neither does it to unpair and pair the devices.
I also tried to disable A2DP hardware offload - no luck.

My Nothing Ear Bluetooth headphones continue to work flawlessly though.
Also my friend's iPhone connects properly to my Hyundai.

This behaviour appeared with the newest update(s). It worked like couple of days ago without issues.

Any workaround or help is highly appreciated. I can also offer to send debugging information; just let me know how to collect them.

**Comment by thestinger** [comment]
It's a known upstream issue. You'll need to find info from upstream reports.

**Comment by qdrop17** [comment]
https://www.androidauthority.com/pixel-auto-bluetooth-pairing-3263107/

We have to wait for a fix then :-)

**Comment by qdrop17** [comment]
https://issuetracker.google.com/issues/265072581

It seems to be fixed - but I don't understand the pipelines and stuff. When are these changes integrated and rolled out to Graphene users?

**Comment by r3g-5z** [comment]
Likely in the February security update. However, this disconnection "bug" was discovered to be a new security check in the Bluetooth stack preventing your Bluetooth connection from being decrypted at the transport level, similar in the sense of TLS stripping.

It seems that most cars will start with an encrypted Bluetooth connection but later on downgrade it back to unencrypted plaintext. This new security check will kill the connection instead of allowing it to downgrade.

Despite the issues it seems to cause with very poor Bluetooth hardware like cars, GrapheneOS does not want to revert this security measure.

**Comment by r3g-5z** [comment]
It also seems to be intended behaviour with Bluetooth devices in general and only recently Pixels are now enforcing it.

> a certification requirement

https://github.com/GrapheneOS/platform_packages_modules_Bluetooth/commit/329fe84be73c9eb383df89f901163073317e708b

**Comment by qdrop17** [comment]
Thank you very much for clarifying; that's interesting!

It would be good to have at least a developer option to disable this. It's important to be aware of this behaviour. Still, a lot if people can't afford buying a new car to have handsfree audio.

**Comment by agiz10** [comment]
I had the same problem on Pixel 6. Google fixed it and newest GrapheneOS update (TQ1A.230205.002.2023020600) fixed it for me as well.
I can play music on my car again.
