### ISSUE TITLE
locked out

### ISSUE THREAD

**Issue by Gitopm** [GrapheneOS/os-issue-tracker#1932]
I entered the pin once the way I always do to create a new pin for the device. I entered it again the second time to confirm that it entered the correct pin the same way I always do. the same pin that I always use. The device confirmed that I entered the correct pin twice. Using the same four number pin that I've used so over the last 25 years for everything. I am now locked out of my device the same pin that I entered twice does not unlock the device and my bootloader is locked I have no way to access the device and I have no way to do a factory reset can you please help me I just need my phone back please I want my phone back please

**Comment by Gitopm** [comment]
It's a pixel 6A running your latest operating system

**Comment by Gitopm** [comment]
Also happens to be my company work phone and I'm losing money every minute that it's not ringing

**Comment by thestinger** [comment]
You must have changed the lock method and don't recall doing it. Maybe you wanted to test something. I don't think it would have locked you out otherwise. You should wipe via recovery.

**Comment by Gitopm** [comment]
I just found the literature on how to do it. I got my self out of the frying pan but wow like wow I was. This never happened to me. I've always punched my pin in perfectly. It's it's a such a simple pin. It's not 1, 2, 3, 4 but just as simple. Anyways, it's all good now other than that little mishap. I love graphene os by the way. I the only thing I don't like is the same thing that f***** me over. I really dislike not having the pattern lock. If you just brought back the pattern lock it would be perfect. 100% perfect in my opinion.

⁣Get BlueMail for Android ​

**Comment by thestinger** [comment]
Pattern lock is problematic and gives a false sense of security. PIN allows many more possibilities since you aren't stuck reusing adjacent digits and can reuse digits. You can generate a random PIN which is far more secure than coming up with one yourself. Random 6 digit PIN is the minimum baseline recommendation. Pattern lock can also often be obtained by looking at streaks on the screen as opposed to PIN where that's not nearly as easy. PIN also supports PIN scrambling as a near full mitigation for that and a partial mitigation for being watched.

**Comment by Gitopm** [comment]
Have you ever seen CRdroids pattern lock? You can increase the grid up to 12x12 or just about but even at 6x6 the pattern possibilities are exponential. I miss crdroid for that.

⁣Get BlueMail for Android ​

**Comment by r3g-5z** [comment]
Increasing the size of the grid still does not generate enough entropy compared to a far more secure 6 digit PIN due to human error, does not negate shoulder surfing, and does not negate the fact that your phone screen clearly visibly shows your pattern from your finger dragging on the screen so many times.
See this research done here https://web.archive.org/web/20210719003102/https://www.lancaster.ac.uk/staff/wangz3/publications/ndss_17.pdf for the 3 things I mentioned and https://github.com/GrapheneOS/os-issue-tracker/issues/570 for the initial discussion. Pattern locking is not coming back and is problematic for a security and privacy OS.
