### ISSUE TITLE
SUPL requests are being made, despite disabling it

### ISSUE THREAD

**Issue by enduring78** [GrapheneOS/os-issue-tracker#1939]
My Google Pixel 6 is making connections to supl.google.com about every 30min. I know this is the default behavior, but I disabled it in the APN settings according to the documentation. 

I first noticed the connections in my NextDNS log. To be sure it wasn't from another device, I disabled Private DNS and watched the queries on my Pi-Hole, and they also appeared there. I have also analysed my network traffic with the 'PCAPdroid' app from F-Droid, and again, I am seeing both a DNS-query and a connection to the resolved IP.

Off course I checked if this wasn't an app making these requests. A friend has a Pixel 6a laying around on which I installed GrapheneOS. No apps installed, just the OS and my SIM-card. In the settings I disabled SUPL in the APN-settings, just like I did on my main phone. This phone was making the connections as well.

I also tested this with SIM cards of 3/4 of the most popular carriers in my country: Tele2, T-Mobile and KPN. The behaviour is the same across all 3 carriers.

**Comment by thestinger** [comment]
After removing it from the list of APN types you need to save the APN settings with the menu.

**Comment by thestinger** [comment]
We're unable to replicate this so far. It is probably a carrier specific issue. The OS may not be respecting the changed APN configuration.

**Comment by thestinger** [comment]
@enduring78 Did you reboot after removing it?

**Comment by GY8VSdYYzvL8-K6T** [comment]
Does the carrier determine SUPL server address or can be forced through OS (to something other than supl.google.com in case carrier doesn't respect removal of SUPL from APN settings)? Maybe GrapheneOS can force a default SUPL server addresses than is more private than supl.google.com for such unruly carriers?

**Comment by thestinger** [comment]
We think this issue is specific to 6th / 7th generation Pixels.

**Comment by thestinger** [comment]
We've confirmed this only impacts 6th/7th generation Pixels due to them having a different GPS configuration set up to only partially respect the APN configuration.

We've added a Settings -> Location toggle for force disabling SUPL in the upcoming release of GrapheneOS. This avoids the need to edit APN configuration. We can decide if we want to change the APN configuration to be fully respected on 6th/7th generation Pixels in the future, but it won't really matter if we have a simpler, easier to use toggle for forcing it off regardless of your carrier. This will also be useful for disabling it when you have no carrier since it will otherwise still be used when the device isn't in airplane mode, although there isn't much reason not to put the device in airplane mode if you have no carrier unless you want to use SUPL or other network-based location services.
