### ISSUE TITLE
Lockscreen camera allowing access to all photos in gallery.

### ISSUE THREAD

**Issue by Occupant9589Carpet** [GrapheneOS/os-issue-tracker#1945]
If the camera is accessed from the lockscreen it makes it possible for an unauthorized person to access, view, and or delete all photos previously taken and stored on the phone.

I like being able to access the camera from the lockscreen to take a photo, but photos already taken shouldn't be available.

**Comment by thestinger** [comment]
If you open it in lockscreen mode take phones, then open it again in lockscreen mode **without the activity being closed in the meantime** then the earlier photos are still accessible until it's closed. That will change in the future.

**Comment by thestinger** [comment]
It's not clear which camera app you're referring to but I'll assume it's about GrapheneOS Camera
The lockscreen mode only allows access to what's captured in the lockscreen mode since it was opened. Try taking a photo in regular mode, then in lockscreen. It's not accessible there. If you open it in lockscreen mode take phones, then open it again in lockscreen mode without the activity being closed in the meantime then the earlier photos are still accessible until it's closed. That will change in the future.

**Comment by thestinger** [comment]
It's not clear which camera app you're referring to. GrapheneOS Camera doesn't work this way. The lockscreen mode only allows access to what's captured in the lockscreen mode since it was opened. Try taking a photo in regular mode, then in lockscreen. It's not accessible there. If you open it in lockscreen mode take phones, then open it again in lockscreen mode without the activity being closed in the meantime then the earlier photos are still accessible until it's closed. That will change in the future. Other camera apps need to implement a separate secure mode for lockscreen too. It's not up to the OS to implement that for other apps if that's what you're using.

**Comment by Occupant9589Carpet** [comment]
The only camera I have is what came with GrapheneOS. After reading what you said I checked and found out some new information. If you open the camera from lockscreen, take pictures, hit power button, screen turns off, hit power button, screen comes back on and bypasses lockscreen and photos are still available. But if you open camera from lockscreen, take pictures, hit back button, screen locks, open camera from lockscreen and photos are not available.

I think this is what had me and potentially others confused. I am used to locking a phone instantly by clicking the power button so it is almost an unconscious move to try and lock it with the power button when lockscreen camera is opened.

At least I know how to lock it asap now. It would be good if both ways could lock it in the future.

Love the OS. Keep up the good work.

**Comment by thestinger** [comment]
It's not bypassing the lockscreen. There's a dedicated lockscreen camera mode and photos taken there are available on the lockscreen until the camera is closed. You can't ever access photos not taken on the lockscreen from the lockscreen. We're aware that it would be nice if it closed automatically by default and it hasn't been implemented yet. It's a planned feature.
