### ISSUE TITLE
Pixel 6a crossprofile notifications not working

### ISSUE THREAD

**Issue by Hodiefx** [GrapheneOS/os-issue-tracker#1966]
I have Pixel 6a and the notifications between profiles are not working. Yes I enabled Send Notifications to current user and I have unrestricted battery setup for the apps, but still it does not work. I enabled notification on both profiles. One is the owner profile, the other one is "google" profile. I'm not getting any notification from the other profile at all. So if I'm on the OWNER profile, I do not get any notifications from google profile and when I'm on the google profile, I do not get any notification from owner profile. I only get notifications from the profile I'm currently on. I did reboot, I even switched to toggles on and off. I'm on Pixel 6a , Android version 13, Build Number is TQ1A.230205.002.2023021000

**Comment by thestinger** [comment]
The other profile needs to be running and the apps need to be designed to run while in the background. If you've turned off the notification channel or turned on do not disturb, etc. you won't get the notifications. Please ask for help in the Matrix chat room or discuss.grapheneos.org since it's unlikely this is a bug.
