### ISSUE TITLE
Receiving notification on lock screen closes keyboard

### ISSUE THREAD

**Issue by Foxtrek64** [GrapheneOS/os-issue-tracker#1979]
## Description

I use a passphrase to log in to my phone. When typing my passphrase, if a notification is received it closes the keyboard. The issue is guaranteed to happen with the first notification, but subsequent notifications may trigger this issue as well. I have also had it happen without a notification, but I could not speak to the cause.

## Reproduction

1. Change your login method to use a passphrase.
2. Set a secure passphrase (20-30 characters)
3. Place your phone on standby by tapping the power button.
4. Wake up your phone, and swipe to unlock.
5. Type your password while receiving notifications.
6. Swear in frustration as the keyboard closes, causing you to not input a key or double-input when overcompensating for a closed keyboard.

## Other info

This issue occurs regardless of the keyboard app being used. I use Florisboard currently, but I have also experienced this issue with AnySoftKeyboard and the built-in keyboard.

The notification I see close the keyboard most often is a message notification from Discord, though I have seen other notifications cause this behavior as well.

## Device information

Model: Pixel 5
Android version: 13
GrapheneOS Version: TQ1A.230205.002.2023021000

**Comment by SubSide** [comment]
Can confirm this. This is especially infuriating when someone is sending multiple messages and you want to respond, but it keeps closing your keyboard. And since you don't exactly kmow at which point it more often than not it means having to start from the beginning.

Don't think the type of message matters. I have it with whatsapp, sms, and telegram. I think I also had it on notification update (spotify changing song) but can't remember for certain.

Someone could probably lock me out of my phone by keep sending messages :p

**Comment by thestinger** [comment]
Someone needs to test on the stock Pixel OS.

**Comment by Foxtrek64** [comment]
I've been getting this error more frequently now. It seems to be closing my keyboard regardless of whether I get a notification after a few seconds. I haven't timed it, but it is rather uncommon for it not to close mid-typing. Not sure what may be causing this behavior.

**Comment by r3g-5z** [comment]
Please verify if this is still an issue on latest GrapheneOS release. QPR2 made changes in fwb for keyboard not showing under certain situations.

**Comment by r3g-5z** [comment]
Going to assume this is fixed in QPR2 / latest GrapheneOS release.

**Comment by SubSide** [comment]
> Please verify if this is still an issue on latest GrapheneOS release. QPR2 made changes in fwb for keyboard not showing under certain situations.

Sadly I came across this issue again today. I expected to receive an SMS for 2FA and I was trying to get ahead of it by already unlocking my phone. In the middle of typing it I received the SMS which closed my keyboard.

Build I'm running: TQ2A.230305.008.C1.2023032000

**Comment by Foxtrek64** [comment]
Likewise. The issue went away for a while but it appears to be back for me again.

However, I have personally noticed that it now appears to be time-based. That is, after a handful of seconds (I've yet to time it), the keyboard will close regardless of whether I receive a notification or not. I often find myself in the emergency menu because that part of my passphrase happens to be in the middle of the keyboard which is covering the emergency button.

Notifications can still trigger this issue, however it is no longer exclusively notifications that cause the issue.

**Comment by conrad57** [comment]
I am constantly experiencing this bug since I started using Graphene OS on a Pixel 6a almost a year ago.

For me it often happens with Signal notifications. When I want to unlock my screen and start entering my very long password and receive one or more notifications at that time the keyboard closes. It is really annoying and keeps me from logging in due to missing characters or double typing them.
