### ISSUE TITLE
Pixel 6a phone calls not working anymore

### ISSUE THREAD

**Issue by choeffer** [GrapheneOS/os-issue-tracker#1999]
Since the last update, Android 13 + Patchlevel 5th of Feb., I am unable to do phone calls. I can receive them, but not initiate them anymore. It does not matter if I am at home and do wifi calling, or on mobile network using 5G.
In addition, there seems to be a bug that after exactly 35min, the phone calls are hang up as well. This already happened before the last update.
I am located in Germany and use o2 directly, so no reseller and I did not actively change any settings regarding phone calls.
Any idea, do others have the same problem as well?
Edit 1: After disabling VoLTE in the SIM settings, I am able to make outgoing phone calls again via wifi calling. Also on mobile network, but with a worse sound quality and not HD voice anymore.

**Comment by smakaremy** [comment]
Hi 
I have the same problem. 
please let me know if you find a solution.

**Comment by thestinger** [comment]
> Since the last update, Android 13 + Patchlevel 5th of Feb

This was not the last update.

You need to provide clear information on which version you're using and when it stopped working. As is, we don't have enough information and will need to assume this is a carrier side issue.

**Comment by choeffer** [comment]
It is the latest available update on the stable channel. I manually clicked on "Check for Updates" and there is no newer one available. I am currently on Build Number TQ1A.230205.002.2023030400 . 
With this version, outgoing phone calls do not work anymore, the dailer directly hangs up, until disabling VoLTE in the SIM settings, see my first post.
The issue that the phone calls are dropped exactly after 35 min also happened on the build before the current one. I installed the current build, after an manual reboot, today. So yesterday I had this 35 min calling limit, and also before on that build I had many dropped calls, and with the new build, I was not even able to make outgoing calls anymore.
As @smakaremy  has the same issue, I doubt it is my carrier, and I had never experienced so many dropped calls and not working outgoing calls before on GrapheneOS.

**Comment by thestinger** [comment]
> As @smakaremy has the same issue, I doubt it is my carrier, and I had never experienced so many dropped calls and not working outgoing calls before on GrapheneOS.

They didn't provide any details and it's unlikely they have the same issue.

**Comment by choeffer** [comment]
@smakaremy could you provide more detailed information, like I did, when it stopped working, which build you are using etc.?

**Comment by thestinger** [comment]
There were no recent changes relevant to this. It was a carrier-side change, not an OS change. There are frequent OS updates often only days apart and OS updates are likely almost the only time you reboot in practice. The assumption that something which stopped working must have stopped working because of an OS update is wrong. We know what changed in the OS updates and the last time there were changes relevant to this was early in February, not 2023030400. It's incredibly unlikely that 2023030400 had anything to do with this and it will remain closed without evidence of that. You'll have to fresh install 2023030400, confirm that it doesn't work, then fresh install 2023022300 and confirm that it does work there, which we pretty much know isn't going to be the case. It will work on both or won't work on both. 2023030400 isn't what changed this.

**Comment by smakaremy** [comment]
I Turn off VOlte and it seems to be alright

**Comment by ezmegy** [comment]
I'm struggling with this too. 

Pixel 6a
Android 13, Build number 2023031500 (which seems to be the latest on Stable atm.)

I can't receive or make any phone calls (cellular, not wifi), the app just times out and quits without any error message or sound of connecting.
Interestingly, when the phone is trying to connect, I see the signal's icon turning from LTE to error (exclamation mark) in the status bar of the phone.
4G and WiFi work fine and I can make calls via Viber, Messenger etc.

Started for me in Feb as well: not sure which build exactly, but 2-3 updates since then didn't solve it (I always update to the latest).

Tried:
- updating + restarting
- turning off mobile data, roaming, VoLTE
- setting preferred network type to LTE
- removing SIM and trying in an other device: worked fine

Not sure how to proceed, but if anyone could give me some tips I'm happy to try and debug further...

**Comment by ezmegy** [comment]
Wow, onto something:

"Allow 2G" fixes it.

I probably turned that off at some point just didn't remember (or maybe the update did). 

Also not sure if calls are supposed to work without 2G (I thought most providers actually stopped 2G service didn't they?) but either way, leaving that on for now seems to do the trick so happy days.

**Comment by thestinger** [comment]
Lots of providers are shutting down 3G while keeping 2G.

**Comment by choeffer** [comment]
VoLTE enabled was working fine again, with one of the last updates, but I still got call drops after 35 min (I do not know why it is exactly 35 min).
I will now try to reset my network settings, described e.g. here https://www.verizon.com/support/knowledge-base-240095/ , to see if that will help. Interestingly, resetting network settings disables WifiCalling, which might introduce issues as well, regarding reddit and other sources.
