### ISSUE TITLE
[Feature Request] Option to override Private DNS per saved WiFi connection

### ISSUE THREAD

**Issue by russianbot91** [GrapheneOS/os-issue-tracker#2031]
Some network administrators block DoT/DoH which prevents you from even being able to establish a VPN connection. This is somewhat common on corporate networks. In order to use these networks you have to disable Private DNS system wide and remember to turn it back on before you disconnect. It'd be nice if Private DNS could be disabled for specific saved networks.

One notable example is UCHealth hospitals (the largest hospital network in Colorado, US).

Also, the same with regular DNS. You can disable DHCP and set everything manually, but there isn't an option to use DHCP and only override the default DNS servers. This doesn't work on many networks where you don't control the DHCP allocation ranges. You can set a static IP and the next time you try to connect someone else is already using it. MAC randomization prevents the DHCP server from being able to reserve the IP for your device.

**Comment by thestinger** [comment]
Blocking DoT is common due to the different port but blocking DoH is rare because it uses HTTPS. More servers supporting DoH and the DoH implementation being expanded to support more servers should take care of this. We don't plan on completely changing this setting to have per-network overrides especially since there are a lot more than Wi-Fi networks. In general, we also recommend using the standard DNS provided by a VPN rather than standing out from other users by overriding it, and since we recommend using a VPN for the purpose of having a shared IP rather than giving data to sites/services based on IP address which is also coarse location information in many cases, particularly for Wi-Fi networks where the public IP from an ISP tends to be accurate to within blocks unlike mobile IPs that are more coarse.
