### ISSUE TITLE
add option to remove notification panel from lockscreen

### ISSUE THREAD

**Issue by gitgit888** [GrapheneOS/os-issue-tracker#205]
The navigation panel on lockscreen makes device less secure.
It can show which VPN name you are connected to,it can also be used to find out which Wifi network the device is automatically connected to. It can also if you use custom apps that puts a toggle there tell the world that this phone is connected/subscribed to service X.

A solution for this could be a toggle in lockscreen settings.
Disable notification panel on lockscreen yes/no 

This can also prevent setting phone to Airplane mode among other things.

**Comment by beerisgood** [comment]
As you correct the title, you should correct your first sentence too. (navigation -> notification)

Anyway you can't enable airplane mode from locked phone.
Same for WiFi and mobile network. Can't be disabled from locked phone.

So i would rate this as privacy feature, not as security feature. And because of that i don't think it's worth it, as if the attacker own the phone, this information doesn't increase his attack chances.

**Comment by thestinger** [comment]
> This can also prevent setting phone to Airplane mode among other things.

That's not possible. GrapheneOS requires unlocking to use most of the quick settings tiles including toggling airplane mode:

https://github.com/GrapheneOS/platform_frameworks_base/commit/788afa3829f1e9a3a484ccfc58f3adb749583e90

Look through the changes in frameworks/base.

**Comment by thestinger** [comment]
The Wi-Fi network that's being used can be detect without this notification panel.

**Comment by thestinger** [comment]
Also, an attacker can detect the VPN being used once they have access to a network being used by the device. It's possible to trick a device into connecting to a different Wi-Fi network than intended with standard Wi-Fi encryption, since it doesn't provide authentication of the AP. Similarly, cellular networks don't provide strong encryption / authentication and the traffic can be intercepted. The VPN you are using is not something that's private. It's known to the network, and since networks generally don't have strong authentication, a nearby attacker can figure it out too. This just shows one of the ways that using a VPN is so useful.

Unless you don't use cellular and your device is only set up to use Wi-Fi networks with enterprise security features, you don't have strong authentication of the networks and the traffic can be redirected through an attacker's network instead. Networks shouldn't be trusted, and they aren't trusted by the OS or any sane apps.

So, the only concern that I think is truly valid is about custom quick tiles but people adding those should be aware that they are visible on the lockscreen and many apps *choose* to make their quick tiles usable from the lockscreen, just as they can mark their notifications as non-sensitive and make them available on the lockscreen with the default mode for notifications (hiding only sensitive data).

Making a change like this would be an extremely low priority and I'm not sure that it would be accepted, since it's hard to see much value and it would be one more thing to maintain and which could go wrong and cause problems for users. Every added feature has a cost. In this case, I don't think the cost is worth it even if someone else implements this. I'm not going to close this right now, since it wouldn't be a useless feature, but the value would be very low.

**Comment by thestinger** [comment]
This proposal is too coarse grained.
