### ISSUE TITLE
Failing to obtain an IPv4 address in local wifi network

### ISSUE THREAD

**Issue by maischus** [GrapheneOS/os-issue-tracker#2090]
Yesterday I updated my phone to the current GrapheneOS stable version 2023040400. Eversince my phone seems to not support IPv4 anymore: The phone does not apply the IPv4 address advertised by my DHCP server and when I set a static IPv4 address, the phone disconnects and tries to connect permanently. Other devices in my network work properly.

Any ideas?

Phone: Pixel 6a
GrapheneOS version 2023040400

**Comment by thestinger** [comment]
Sounds like your router doesn't handle per-connection MAC randomization properly. It perhaps ran out of DHCP table entries and doesn't know how to delete the least recently used entry when a new device needs an address. Try clearing your router's DHCP table in the router administration panel. If it was used for something like a coffee shop, it would quickly hit this from people coming and going. You can work around this problem by setting GrapheneOS to using the standard Android per-network random address approach instead of our default per-connection random address approach. Alternatively, replace the router or just work around the issue.

**Comment by tsvtx** [comment]
I was in a similar situation quite a while back with devices when they decided to use the randomized MAC addresses. What occured was I had a couple of devices that ended up rotating through macs (for any number of reasons) and started crowding my DHCP scope. The problem was my lease expiration was set too high/long. Wireless devices need to have a shorter expiration set for the scope to make sure that they don't hog up all the leases as devices come and go. One device I had come and go with multiple times on/off wireless and received a new lease each time due to the rotating mac address. A single device had taken up 30+ reservations over the course of a couple days. The scope lease timeout was at a default of 8 days and instantly starting chewing up space. Multiply that by multiple devices doing similar and you're completely out of IPs in a couple of days.

**Comment by maischus** [comment]
Thanks a lot, @thestinger. Your hints helped me resolve my issue.
