### ISSUE TITLE
OS still connects to supl.grapheneos.org even when SUPL is set to 'Enabled; standard server' or 'Disabled' and interferes with raw satellite data

### ISSUE THREAD

**Issue by 1C4K3** [GrapheneOS/os-issue-tracker#2128]
Tested on a Pixel 6. When Settings > Location > Secure User Plane Location (SUPL) is set to 'Enabled; standard server' or 'Disabled', the OS still connects to supl.grapheneos.org. 

Upon further inspection with the vpn app TrackerControl, there seem to be two different system apps that connect to supl.grapheneos.org. One connects to port 443 and the other connects to port 7275. When SUPL is set to standard server or disabled, only the system app that connects to port 7275 is actually disabled. Besides still making this connection, I also noticed that A-GNSS continues to interfere with the raw satellite data.

When SUPL is set to 'Enabled: GrapheneOS proxy', the OS connects to: 
- supl.grapheneos.org (port 7275) 
- supl.grapheneos.org (port 443) 

When SUPL is set to 'Enabled: standard server', the OS connects to: 
- supl.google.com (port 7275) 
- supl.grapheneos.org (port 443) 

When SUPL is set to 'Disabled', the OS still connects to: 
- supl.grapheneos.org (port 443)

**Comment by thestinger** [comment]
> Tested on a Pixel 6. When Settings > Location > Secure User Plane Location (SUPL) is set to 'Enabled; standard server' or 'Disabled', the OS still connects to supl.grapheneos.org.

The app you're using is reporting incorrect data due to multiple services being hosted on the same grapheneos.network servers. The only service referred to as supl.grapheneos.org is on port 7275. It appears the app you're using caches a mapping of host names to IP addresses based on the first lookup. Connections are to IP addresses, not host names.

Suggest reading https://grapheneos.org/faq#default-connections and looking at which services are hosted on the network servers at https://grapheneos.org/articles/grapheneos-servers#grapheneos.network.
