### ISSUE TITLE
[Feature Request] Different "Private DNS" server settings for each user profile

### ISSUE THREAD

**Issue by codenyte** [GrapheneOS/os-issue-tracker#2141]
I'd like to set a different DNS Server in the "Private DNS" option for each user profile. as I have my main User profile with a NextDNS Config and corresponding DoT address which completely blocks all connections to Google and Facebook, but I need to use WhatsApp sometimes, so I have a second profile for WhatsApp, and I need to set a different DoT address leading to a different NextDNS profile which allows connections to the WhatsApp servers.

**Comment by thestinger** [comment]
We don't plan to change how this works downstream since you can already accomplish the same thing by avoiding the Private DNS feature and instead using a per-profile VPN app supporting what you want to do.

**Comment by thestinger** [comment]
Apps can also simply do their own DNS resolution to bypass DNS-based client filtering. They can also just make the connections on their servers, which is very common since it avoids leaking your API keys in your app builds. This kind of enumerating badness approach which fundamentally doesn't really work for many reasons is not our approach and we're not going to be dedicating our resources to it, especially niche use cases for it.
