### ISSUE TITLE
Disabling HTTP Endpoints

### ISSUE THREAD

**Issue by VulcanElf** [GrapheneOS/os-issue-tracker#2181]
2 Ideas:

1.  Having an option for Internet Connectivity Checks disabled, as a default, but enabled to GOS Proxy upon  the detection of connecting to an open/public WiFi (no-password) would be more secure, private & use less bandwidth overall.

I've noticed that having it disabled generally does not interfere with functionality, that is, until connecting to a public/open WiFi Hotspot.

2.  Additionally, having an option to "Time-out" for Internet Connectivity Checks would probably be more practical.  In other words, just as GOS has a Bluetooth Timeout option, an Internet Connectivity Check timeout-to-disable would be more secure.

**Comment by r3g-5z** [comment]
> use less bandwidth overall.

A connectivity check is a blank HTTP 204 request... You are not saving bandwidth by disabling this at all.

Not really understanding how this is something more "secure, private". There are plenty of other GrapheneOS connections, why is the connectivity check the only one you want to mess with? Why don't you just disable connectivity checks if you don't want them?

> I've noticed that having it disabled generally does not interfere with functionality, that is, until connecting to a public/open WiFi Hotspot.

Because they use captive portals for you to login to their network. Connectivity checks also are for captive portal detection. Nothing is broken about that. You disable connectivity checks, you can't login to captive portals.

The timeouts added for radios like Bluetooth and Wi-Fi are not at all the same thing here.
