### ISSUE TITLE
Bug force closes all apps every 5 minutes

### ISSUE THREAD

**Issue by TheBready** [GrapheneOS/os-issue-tracker#2217]
Phone: Pixel 7 Pro
Build: TQ2A.230505.002.2023051600

All apps close after some time. This affects every app and all apps at once. Even music apps in the background are closed while the phone is not used otherwise.
Even the discarded 'sandboxed Play Store' notification is shown again.
This started around the 22nd of May.
Do you know if this is a known issue?
Will this be fixed with the next release?

**Comment by muhomorr** [comment]
Need to see a full bugreport.
Capture it after this issue happens again: https://developer.android.com/studio/debug/bug-report#bugreportdevice

**Comment by TheBready** [comment]
[Uploading bugreport-cheetah-TQ2A.230505.002-2023-06-01-22-06-21.zip…]()

I created the report seconds after an force close event.

**Comment by Hanouta** [comment]
To me it looks like this is related to the LocationService of GmsCompat (part of sandboxed play services), and it leads to an "Global reference table overflow".

> Is there something I can do to fix it right now?

Just a wild guess, but do you have the "improve Location accuracy" setting (under Settings->Apps->Sandboxed Google Play -> Google Location Accuracy) turned on? Did you grant location access to the Google Play services? Of course it could also be something different, maybe take a look at the privacy dashboard to see which apps have accessed your location and revoke the permission from those (especially background location).

Disclaimer: I'm not a GrapheneOS developer, I just looked at the log file because I was curious what could cause something like that

**Comment by muhomorr** [comment]
This is a bug in the sandboxed Google Play compatibility layer.

> Is there something I can do to fix it right now?

You can disable the "Reroute location requests to the OS” setting in Settings -> Apps -> Sandboxed Google Play.

**Comment by TheBready** [comment]
The option was disabled. I will activate it for now and test what happens.

**Comment by TheBready** [comment]
It seems that activating "Reroute location requests to the OS” did nothing to fix the issue.
However, when deactivating it I got a message that Google services need the location permission activated and it needs always access. 
Doing that fixed the issue for 24 hours, so I think it's fixed now. 
But I don't want to share my location with Google services. What would be the most private way to set the settings?

Thanks a lot for your help. Much appreciated.

**Comment by muhomorr** [comment]
Granting location access to Play services when ""Reroute location requests to the OS” is off is needed only if you use apps that use Google's location service.

**Comment by muhomorr** [comment]
This issue is fixed in [2023071100](https://grapheneos.org/releases#2023071100) release.
