### ISSUE TITLE
[ KERNEL PANIC ] Raviole kernel source.

### ISSUE THREAD

**Issue by Aarqw12** [GrapheneOS/os-issue-tracker#2241]
hi , here is the situation of source graphene regarding raviole kernel compile

here is the step :

mkdir -p android/kernel/raviole

cd android/kernel/raviole

repo init -u https://github.com/GrapheneOS/kernel_manifest-raviole.git -b 13

repo sync -j8

LTO=full BUILD_AOSP_KERNEL=1 ./build_slider.sh

= compile done , flash = kernel panic no log in sys/fs/pstore

2 workaround I find:

1 ) merge google common 5.10 over graphene os based in 5.10-lts

 = boot , go to home

2 ) merge google common 5.10 + 5.10-lts over kernel gs  ( no real conflict very easy )

compile command used : BUILD_CONFIG=private/gs-google/build.config.slider build/build.sh
*LTO=full is no needed here in this command as its will look config of gki_defconfig for LTO

result = boot , go to home

so my question is why you no use google common 5.10 base as google use it for compile gki and update android gki base here ( 5.10-lts is used only for upstream ) and I get simply a kernel panic using your guide compile in https://grapheneos.org/build#kernel-6th-generation-pixels

also what is the beneficit of using build mixed ? when you can very easy merge google common 5.10 + 5.10-lts without conflict & using 2 source for compile... also I discovered clang no properly detect error in mixed build for module ...

thanks in advance for look at it.

device I own [ pixel 6 ORIOLE ]

**Comment by thestinger** [comment]
You're not building correctly.

**Comment by Aarqw12** [comment]
> You're not building correctly.

what is wrong ? as per documentation in google kernel website BUILD_AOSP_KERNEL=1 ./build_slider.sh is for mixed build

**Comment by thestinger** [comment]
I think the issue is that you aren't re-signing the vendor modules with the key generated for the GKI. The only procedure that's supported for using the build without further changes is the one we describe. You're likely using the boot.img directly or something else like that.

**Comment by Aarqw12** [comment]
> I think the issue is that you aren't re-signing the vendor modules with the key generated for the GKI. The only procedure that's supported for using the build without further changes is the one we describe. You're likely using the boot.img directly or something else like that.

I directly use zimage.lz4 + vendor_boot + vendor_dlkm + dtbo

**Comment by thestinger** [comment]
We have fully enforced kernel module signing enabled. You can't use the vendor_boot, etc. from the kernel build unless you change how they're generated to sign the vendor modules with the key generated for the GKI. Look at the commit in kernel_gs for signing the vendor modules (currently 25c3d6f8bb9dfa339ea9266e5f177257b80e6066). You'll need to do this as part of it generating vendor_boot, etc.

**Comment by Aarqw12** [comment]
> 

need do that manually so ? mhmm I will look

**Comment by Aarqw12** [comment]
but without signing module I get too kernel panic idk what is wrong I need google common 5.10 base

**Comment by thestinger** [comment]
I don't know what you're talking about. I explained the issue you're causing with your approach. You don't need to merge anything.

**Comment by thestinger** [comment]
We sign the vendor modules at the end, since we only use them that way rather than using the images generated earlier. When we sign them, vendor_boot, etc. were already generated by the build script, so those aren't usable and we don't use them. You either need to do it with the approach we support, turn off enforced kernel module signing or sign the modules with the GKI key before they're included in the images you're using. We don't use those images. You're having this issue because you're doing things a different way than the supported approach of building those images with the OS.

**Comment by Aarqw12** [comment]
ok I see

**Comment by Aarqw12** [comment]
> I don't know what you're talking about. I explained the issue you're causing with your approach. You don't need to merge anything.

for unknow reason flashing directly kernel compiled need commit from 5.10 common base

**Comment by thestinger** [comment]
You're incorrect and I've explained what is going wrong with your approach. GrapheneOS enables forced module signing in the kernel build configuration. If you revert that or use the standard kernel build configuration instead, your approach will work. The correct solution is signing the modules that you're using with the correct key. If you build everything together instead of building a separate GKI and device modules, then it won't be an issue because the modules will get signed as part of the kernel build instead of needing to be signed separately after building them from a different source tree. That's not the official way to build these kernels though. The approach we're using to build them is the supported approach: building kernel from GKI common kernel tree, and building device modules from device kernel tree. They merge the GKI common kernel tree they're using into the device kernel tree, which we aren't currently doing because it's not mandatory due to the stable GKI ABI. It would be a mess to do that downstream. We care a lot about maintainability and porting.
