### ISSUE TITLE
Block location, camera, mic, sensors on timer

### ISSUE THREAD

**Issue by robcle** [GrapheneOS/os-issue-tracker#2345]
Would be nice to have the option to block sensors on a timer. User forgets to turn them back off after use.

**Comment by thestinger** [comment]
It makes more sense to use one-time location, camera and microphone permissions rather than using the OS toggles. It doesn't really make much sense to have timers for the OS toggles since apps with persistent access that are using them would keep them access. It's not the same as Bluetooth and Wi-Fi.

**Comment by thestinger** [comment]
Sensors doesn't have a one-time access option yet and that would be a useful thing to add.
