### ISSUE TITLE
Big yikes! GoS Team insist on implementing features that when used make the UX even worse. 

### ISSUE THREAD

**Issue by n3rdcub** [GrapheneOS/os-issue-tracker#2348]
&& all to say 'yeah feature is included it exists and we stamp it with our seal. Wait you tried using it? Why? It doesn't work. You know it just sets everything on fire right?'

Then proceeds to write up wiki docs, detailing how to use the feature that doesn't work except set things on fire.

The entire GoS team backed this and nobody stepped up to suggest 'well wait if all it does is set things on fire and the user has to go download an alternative anyway, why do we even include it?'

You have implemented features, backed them, and made no effort to inform your end users that by using said feature they are agreeing to set everything on fire while advertising it doesn't and is actually to prevent fires in the first place?

That's called deception, willful ignorance, and shows psychopathic behavior that you're  continuing to include a feature described as a useful tool when it actually does the opposite and it should be avoided at all costs. 

How and why is this project heralded as the golden child of Android OSs when it's developers intentionally include features to mislead it's users and establish fake trust in something that never worked in the first place?
My only guess is by including it, it qualifies them for some kind of funding. Regardless if functional or functions even remotely as described.

This feature is called SeedVault by the way 👍

**Comment by thestinger** [comment]
Seedvault is not a GrapheneOS project. It is not our fault that the Seedvault project was taken over by people who are both incompetent and malicious towards us. We are removing Seedvault once we implement a replacement.

**Comment by n3rdcub** [comment]
> Seedvault is not a GrapheneOS project. It is not our fault that the Seedvault project was taken over by people who are both incompetent and malicious towards us. We are removing Seedvault once we implement a replacement.

You've been saying that for over a year. 
**why even fucking include it if it does the opposite of what you describe it to do**

**Comment by thestinger** [comment]
It backs up the data of apps which support cloud backups. It doesn't back up data for nearly as many apps as it could because it treats itself as a cloud backup app instead of a device-to-device backup app. The reliability and other issues are code quality problems with Seedvault. We're aware that it's not well written. It is not surprising that it's in this state based on who took over development. We plan to make a replacement for the app, but as has been stated before, we have higher priorities and are focusing on those. We have a limited number of developers each with limited time and energy. We can't do everything at once. The time and energy you are wasting will take away from things that could be implemented. You will get the opposite of what you want by doing this.

**Comment by thestinger** [comment]
Do not create another issue like this.

**Comment by thestinger** [comment]
It is not dangerous. We fixed the 2 security problems known to us. The encryption format isn't great but it's not dangerous.
