### ISSUE TITLE
Hotspot doesn't work

### ISSUE THREAD

**Issue by andre4ik3** [GrapheneOS/os-issue-tracker#2371]
As title says. Hotspot just straight up doesn't work.

Devices can:
- Connect to the hotspot
- Ping each other (ICMP)
- Talk to each other (TCP/UDP)
- Ping the internet (ICMP, tried 1.1.1.1, 8.8.8.8, plus a couple of my own servers)
- Phone itself has working internet

But they can't establish TCP or transfer UDP to the web. I tried "resetting the internet" (refresh button top right of the internet settings page) and messing with the hotspot settings, including the security, to no avail. I tried this on a few devices, including 2 laptops and an iPad. I then put the SIM card into the iPad and its hotspot mode worked just fine. This has been an issue for a while (>4 months), but I'm only reporting it now because my ISP has an outage.

Even more strange: sometimes, after not using the hotspot for a while (maybe a day), it works fine for 2 minutes. Then it shuts off again, like some kill switch is activated. Reboot doesn't bring it back.

**Comment by thestinger** [comment]
Hotspot works fine in GrapheneOS. This sounds like a network configuration issue. You should reset network settings and try other debugging. You're going to need to debug this more before it can be considered an issue with GrapheneOS. Please bring it up on https://discuss.grapheneos.org/ first.

**Comment by andre4ik3** [comment]
Yeah you were right, I went into my mobile provider and found "mobile hotspot" service that was off for some reason. Apparently it's meant to automatically turn on and send an SMS saying hotspot costs extra, but I guess that doesn't work on GrapheneOS. Turning on the service option there fixed it.

**Comment by andre4ik3** [comment]
Also isn't GrapheneOS meant to bypass this sorta stuff? I get it's not a primary feature and stuff, but it still would be cool if I didn't have to pay extra every time I turn on my hotspot... considering I already pay way too much for my cell service

<img width="805" alt="CleanShot 2023-08-06 at 00 52 18@2x" src="https://github.com/GrapheneOS/os-issue-tracker/assets/62390580/6d692c6b-9f20-4a46-948d-5aee5b09a059">

**Comment by thestinger** [comment]
GrapheneOS does bypass these carrier restrictions and doesn't mark tethered traffic as tethered. However, your tethered devices likely have their TTL set to 64 which means it's reduced to 63 by the time it gets to GrapheneOS. This would also happen with a virtual machine running within GrapheneOS. Many carriers use this as a very flawed heuristic to detect tethered traffic. You can bypass it by raising TTL by 1 on each of those devices if they support it. That's not within the scope of GrapheneOS since it wouldn't make sense to pay a huge performance and battery life cost by routing all traffic through the OS to reduce TTL by 1. They also really shouldn't be doing that because it's going to impact virtual machines, etc. in the future unless everything works around the heuristic and the fact that it can be worked around shows how terrible of an approach it is.

**Comment by andre4ik3** [comment]
Thanks, I changed my TTL from 64 to 65 so hopefully I can side-step the heuristic detection now :) This is very useful, maybe it should be at least mentioned on the usage page? I feel like more people should know about this!

**Comment by thestinger** [comment]
They may also use other heuristics but it should be possible to bypass most of those by running a system wide VPN on the laptop or other machine that's tethered. Android VPNs are per-profile and the Owner VPN is used for system services but not other profiles or devices in order to provide the ability to run separate VPNs for each one, which is important for privacy to avoid other profiles and devices always having the same IP at the same times which would gradually tie together different identities, etc.

**Comment by andre4ik3** [comment]
Yeah, I run a WG VPN on my laptop most of the time anyway. A shame carriers do all this just to squeeze more money out of customers. Thank you for explaining!
