### ISSUE TITLE
The ability to set your own dns servers

### ISSUE THREAD

**Issue by DevenBL** [GrapheneOS/os-issue-tracker#2372]
It is currently completely impossible to set your own ipv6 DNS servers on the device. When using dhcp for IP address it is impossible to set both ipv4 and ipv6 DNS servers manually to override dhcp server settings.
This should not be the case. Allow the user to set their own DNS servers.

The private DNS option alone is not sufficient and totally cripples the device in the case of very bad and glacially slow ISP provided DNS servers that drop 90% of all DNS requests done to them including the ones to connect to private DNS.

**Comment by thestinger** [comment]
It uses the network-provided DNS servers by default. If you're using a VPN, those are the VPN-provided DNS servers. Using the Private DNS feature is not what we recommend since it doesn't play well with using a VPN. We don't intend to change this from how it works with Android.

**Comment by thestinger** [comment]
If the response above doesn't make it clear enough: you can already provide a local DNS resolver via an app, so you don't need anything else from the OS. Actual VPN apps provide both DNS and a VPN, but you can use one which only provides DNS and doesn't route traffic through itself. It's still the same API.

**Comment by thestinger** [comment]
It uses the network-provided DNS servers by default. If you're using a VPN, those are the VPN-provided DNS servers. Using the Private DNS feature is not what we recommend since it doesn't play well with using a VPN. We don't intend to change this from how it works with Android.

You can already provide a local DNS resolver via an app, so you don't need anything else from the OS. Actual VPN apps provide both DNS and a VPN, but you can use one which only provides DNS and doesn't route traffic through itself. It's still the same API. There are many of these apps available, providing all kinds of different features including filtering results, providing different approaches to authenticated encryption, DNSSEC, etc.

There are no planned changes to this in the short term for GrapheneOS and we focus on doing things that are not already possible via apps, especially when there are a lot of existing app options rather than it being something theoretical without good options available.

**Comment by DevenBL** [comment]
I dont think forcing the user to use third party vpn applications to bypass/reconfigure basic networking options is a good idea for multiple reasons including performance and security but do what you will. I hope you get around to it in the future and that you at least put it on the very long term TODO list.

On a second much less important unrelated point it's really weird that you can reconfigure the ipv4 dns settings but not the ipv6 dns settings for some reason
