### ISSUE TITLE
Support for car crash detection in Google Personal Safety

### ISSUE THREAD

**Issue by lyphyser** [GrapheneOS/os-issue-tracker#2400]
It would be nice to make car crash detection and in general the Google Personal Safety app work on GrapheneOS, which currently crashes after asking for login and asking for emergency contacts and info.

The reason is that it is a useful and potentially life saving feature and possible third-party implementations of car crash detection might not be as good as Google's, since Google has much more funding to do extensive testing and presumably they have performed such testing.

There has been some discussion on what is needed to make it work at https://discuss.grapheneos.org/d/3177-making-personal-safetysos-functional and https://discuss.grapheneos.org/d/1199-car-crash-detection/7

According to the second link, TelecomManager.isInEmergencyCall() and UserManager.getUserName() need to be shimmed using the gmscompat infrastructure, and once these work either the app will work or it will call other privileged APIs that will in turn need to be shimmed.

Regarding UserManager.getUserName(), simply returning "User" seems the best strategy.

For TelecomManager.isInEmergencyCall() the best seems to be to change permissions on it so that it works with the same READ_PHONE_STATE permission that isInCall requires; alternatively perhaps it can be emulated using isInCall() and reading the phone call log to check if the last number is in a list of emergency numbers.

**Comment by muhomorr** [comment]
This likely requires allowing Play services run custom code on sensor hub, which is fully disallowed for unprivileged apps.

**Comment by gsture** [comment]
If you want to use these kind of features you are probably better of using stock Android. I personally think functions like these should should not be added to a privacy and security focused os.

**Comment by lyphyser** [comment]
> This likely requires allowing Play services to run custom code on sensor hub, which is fully disallowed for unprivileged apps.

It's not clear to me whether the CHRE nanoapp is included in the app or if it is included in Google's stock factory images.

In the former case, a permission with manual opt-in could be added to let specific apps run nanoapps; in the latter case, the nanoapp can be extracted from the factory image and included in the GrapheneOS build, and only enabled if a default-disabled setting is enabled.

**Comment by flawedworld** [comment]
It may be possible to make an app which uses the nanoapp, but this is out of scope really for GrapheneOS. I don't see how we can support this via sandboxed Google Play. Example of this being done in the past for active edge: https://github.com/ProtonAOSP/android_packages_apps_ElmyraService

**Comment by Saarsk** [comment]
> Imo, if you want to use these kind of features you are probably better of using stock Android. I personally think functions like these have no place in a privacy and security focused project like grapheneos.

The problem with this way of thinking is that it makes it so that privacy choices become an all or nothing type of deal. So, many people choose to stay with Pixel OS because they don't want to give up a certain feature. 🫤

But had GrapheneOS had that feature, they'd be happy AND had much better privacy (and security). It should be a choice, just like Play Services. No GrapheneOS users are forced to use Play Services just because it's available. But for those who want it (or insist on it), it's there if you enable it.

Why decide whether "it has a place in a privacy and security oriented OS" when users can make that decision themselves? Which results in users avoiding GrapheneOS completely because choices like these are taken away from them? 🙂 Usually, becoming more privacy conscious isn't an instant thing, and people have different levels of compromizes they accept or tolerate.

PS: a friend of mine refuses to give up Pixel OS because of car crash detection not working on GrapheneOS. 🤷‍♂️
