### ISSUE TITLE
Pin number can be used to add a new fingerprint

### ISSUE THREAD

**Issue by robjob1938** [GrapheneOS/os-issue-tracker#2409]
Pixel 5a running GrapheneOS 2023080800.

I had a prank pulled on my that I believe shows a flaw in security.  Someone I know shoulder surfed my pin number on my phone.  When I was not paying attention, they took my phone, used my pin to unlock my phone.  I am aware of this flaw in using a pin, so I use the fingerprint scanner (bio metrics) to lock my apps that allow it.  However, they then used my pin to add their fingerprint to the phone.  Sophisticated apps like LastPass and Bitwarden automatically force the re-entry of a master password if a fingerprint is added, however several apps such as MySudo and my email client do not.

Is there a way to add an option to lock down adding fingerprint (Pixel Imprint) with something besides the device pin number?

**Comment by thestinger** [comment]
The issue here is that your PIN was shoulder surfed. With access to your PIN they had access to all your data and the ability to enable developer options, enable ADB and allow a computer to have ADB access. They could also install / enable an accessibility service app designed for surveillance. The issue is not that they added a fingerprint but that they got access to your phone via your PIN in the first place.

Enabling PIN scrambling can make that harder. Biometric unlock is only usable as a secondary unlock mechanism and has significant downsides but it does have the advantage of not being something people can shoulder surf.
