### ISSUE TITLE
Pixel 6a - all vibration stops functioning until restart

### ISSUE THREAD

**Issue by dippydocus** [GrapheneOS/os-issue-tracker#2414]
Build: TQ3A.230805.001.2023080800

I haven't been able to determine a set of actions that causes this but it's happened probably around 10 times now. 

Haptic feedback on unlock, key presses and all other vibration triggers no longer cause the vibrations to take place. 

I've confirmed that I haven't just disabled the vibrate ringer (which wouldn't affect the haptic feedback anyway). 

Has anyone else noticed this? 
Does anyone have any idea how I could diagnose the cause of this? 

Thanks

**Comment by dippydocus** [comment]
I've finally been in a position to grab some logs after experiencing the issue.
There're lots of 

```
[09-06 20:10:22.074 1222:27231 E/android.hardware.vibrator-cs40l26]
Polling error or timeout! (0)
```

and 

```
[09-06 20:10:41.948 1222:27563 W/Vibrator]
Failed to get state "Haptic"
```

As well as a few 

```
[09-06 20:07:05.492 1314:1445 E/NotificationVibratorHelper]
Error creating vibration waveform with pattern: [0]
```

and 

```
[09-06 20:05:03.736 1314:1668 E/VibratorController]
Vibrator HAL on failed: Status(-5, EX_ILLEGAL_STATE): ''
```

I'm struggling to find anything that may have caused this. Unfortunately I couldn't get logs around when the issue started but it looks like the hardware itself is inaccessible? 

Logs are below. 
[logcat_09-06-2023_20-16-04.txt](https://github.com/GrapheneOS/os-issue-tracker/files/12541704/logcat_09-06-2023_20-16-04.txt)

Any help with this would be hugely appreciated. 

Thanks

**Comment by Goopdegooo** [comment]
Hi All

Just discovered this thread. I have been experience this issue over the past few days. As soon as the build went to Android 14 I noticed the issue.  And I also need to restart to get it to work. But is stops or is very very light, as if it is set to the lowest of touch feedback for example.

**Comment by dippydocus** [comment]
I personally haven't experienced it in a while

**Comment by Goopdegooo** [comment]
I realise this thread has been closed although my device did an update two days ago. And i am experiencing this issue now.

**Comment by thestinger** [comment]
@Goopdegooo Please open a new issue and provide as many details as possible about what triggers it.

**Comment by pedohorse** [comment]
experienced this bug too just now.
vibration feedback stopped working randomly in the middle of writing a sentence. No vibrations at all worked after till reboot.

**Comment by YuaBeVibin** [comment]
hi, not rlly a graphene user but I was looking this up to see if anyone was doing anything abt it and I just wanted to chime in to say that this is an android issue on the pixel 6a in general - it seems like as of rn google is ignoring it, which rlly sucks ass ngl. hoping someone fixes it 👍

**Comment by thestinger** [comment]
Are other people having this issue on the Pixel 6a too beyond @YuaBeVibin and @AndrewFeelz?

**Comment by pedohorse** [comment]
> Are other people having this issue on the Pixel 6a too beyond @YuaBeVibin and @AndrewFeelz?

as i wrote above - had this around 2 weeks ago, but haven't caught it since

**Comment by YuaBeVibin** [comment]
just at 2am twice in a row, hence I was checking if anyone was doing anything about it. came back 5 minutes after reboot, so I rebooted again and it worked fine. managed to go fine for 3-4 months until today.

sometimes it rarly happens, other times it happens daily or even beyond. it's rlly frustrating as it doesn't just effect haptics but also the notification buzzer.

**Comment by RADHASHREE26** [comment]
I have been having the same issue for a while now. Someone here mentioned it's occurring after the Android 14 update. Rightly so. Until last week it was happening once in a fortnight. But this week it has been happening almost every 2 hours.

**Comment by Pietro395** [comment]
This is continuing to happen to me at least once a day

**Comment by pedohorse** [comment]
Just encountered a variation of this bug again (first time since my last post)

This time vibrations were not gone completely, but either dampened, or cut a couple of milliseconds shorter: small feedbacks (light vibrations), like one from keyboard keys, almost disappeared, became barely noticeable, while difference in other stronger vibrations (when entering pin, fingerprint, switching apps, notifications) was not noticeable 
(all profiles)

reboot fixed the issue

**Comment by CrispyChicken44TM** [comment]
Hi, everyone. Just commenting to let you know that my phone is fully updated with the current updates and this problem still persists. I Googled the issue and found a reddit thread that didn't help, then this GitHub link that lead here. Upon reading everyone's comments, the vibration wasn't working. During reading, I got a Snapchat notification and the vibration worked for the notification(s) of Snapchat and basically 'kickstarted' the haptics again. However, writing this on my phone, the basics stopped. It's a roller coaster of emotions with this problem. It works, then doesn't. Works, then doesn't. Currently, I'm in a room with LTE and half signal strength if this helps. I tried to send myself a text to see if the vibration will come back since it worked for Snapchat, but it failed. ¯\_(ツ)_/¯

**Comment by pedohorse** [comment]
First, why I think this is important bug to address:
I, as I assume a lot of people these days too, use phone only in vibro mode: I rely on feeling for notifications, or on silent woop-woop on the table, as in work environment all notifications/calls are distracting for everyone.
So not having vibrations is not an option, and forces me to reboot the phone. Thankfully it's fast, but it is inconvenient as it does a noticeable battery drain to reboot, and i have to punch in all the pin codes while being exposed in the public.

Now to more experiences:
All of a sudden happened to me again, 3 times in 2 days which is unusual.
what I have noticed: 
- for me it ALWAYS happens when typing
- it ALWAYS happened for me on the road (can sim switching towers be the cause?). yet obviously it doesn't happen every time on the road.

> came back 5 minutes after reboot

This time I had it hard: haptics just stopped working on the train as I was typing, then around 5 seconds later it came back by itself, and in another minute or two it stopped working again and for good (until reboot).
After reboot it stopped working again just after 5 minutes, had to reboot it once more.

Next day, going the same train in the other direction - haptics+vibrations stopped working again, until reboot.

This summer I started getting much more instances of this issue than before, not sure since which grapheneOS build it started though.
It also feels like this problem is experienced more often, judging from comments here and posts on discuss, like this: https://discuss.grapheneos.org/d/11507-haptic-feedback-randomly-crashes

> I got a Snapchat notification

I got once (or twice) the same thing - a notification seemingly brought back the haptics, but then a couple of times it just started working on it's own, so it feels like the notification is just a coincidence.

Another notice is that this bug seem to be able to manifest in different forms sometimes: it can change intensity (one case I experienced and described earlier, another seem to be here: https://discuss.grapheneos.org/d/8223-haptics-acting-funky)

I understand it might be an upstream bug, but I haven't seen any stock pixel users complaining about this.
Is there a bug reported in upstream bug tracker for this?
Or will this issue just continue to be there forever?

@thestinger , can we do anything to bring attention to this issue somehow? 
it being here as closed makes it harder for people experiencing it to find it

**Comment by mainmachine** [comment]
FYI - I have been experiencing this exact issue on my Pixel 6a on LineageOS 21. Upon reboot, vibration and haptics work fine, then at some point they just stop. I haven't been able to catch exactly when they stop, however I WFH in a suburban environment so I think we can rule out cell tower switching as a factor, though it's anybody's guess at this point...

**Comment by snowboardbruin** [comment]
Has anyone seen a fix on this?

**Comment by AI-ich** [comment]
I also suffered from this problem for about two years, but it seems to have been fixed now. What I did was to clean the terminal of the vibrator and the terminal nearby that contacts the internal frame. I don't know the details, but I assume that a charge was building up due to poor contact of the terminal, which was causing the adverse effects. (Disassembly is at your own risk.)

**Comment by mint1goose** [comment]
I believe the issue comes from the spring loaded contacts losing their elasticity. I bent the pins on the motherboard for the vibrator upwards and the pins on the vibrator downwards. When I screwed it back, there was more tension between the contacts and made a better connection. Before, the vibrator would go out after 10 seconds of typing. After this, I have not had any disconnects for a few days. I think the firmware is too picky and once there is a slight disconnect the phone just shuts off the vibrator because it thinks there is a serious hardware issue.
