### ISSUE TITLE
Regression with citibank banking app 

### ISSUE THREAD

**Issue by pjasnos** [GrapheneOS/os-issue-tracker#2446]
Hello,

Please apologise if it shouldn't be reported here. This concerns com.konylabs.cbplpat . Up to and including release 2023090600, this banking app was working normally. With update to 2023091800, the app states that "original protections of your phone were modified" and refuses to function.  I fully understand and apologise if this is not the concern of the project.

**Comment by thestinger** [comment]
It sounds like the app is going out of the way to detect an alternate OS and is refusing to run on one. You should try using the exploit protection compatibility mode. Make sure you haven't disabled native debugging support since some banking apps require it. You could also try temporarily disabling secure spawning and rebooting to see if that breaks the app.

**Comment by thestinger** [comment]
Make sure native debugging is enabled, and if that's not the issue then try the per-app exploit protection compatibility mode. If neither of those work, leave both enabled and try disabling secure app spawning temporarily to see if that gets the app working after a reboot. You should leave secure app spawning enabled but it's worth seeing if this GrapheneOS feature is the cause of the compatibility issue. The app may be detecting the different spawning mechanism and refusing to run with it.
