### ISSUE TITLE
Setting for force animation speed to 0.5x (Similar to how in Dev Mode, but without the Dev Mode itself)

### ISSUE THREAD

**Issue by topminipie** [GrapheneOS/os-issue-tracker#2449]
In my opinion it is more pleasant than 1x and most applications work fine with 0.5x

**Comment by thestinger** [comment]
Changing this isn't planned.

**Comment by avwZhNgfQMz9Ewuw** [comment]
Please reopen. This is the only reason I have developer options enabled. 1x is too slow. Developer options shouldn't be required for this.

**Comment by defiling9046** [comment]
Pasted from my prev feature request since i think i created a duplicate, sorry.

I would really appreciate the:

"Ability to change the following settings without developer options turned on:

Window animation scale
Transition animation scale
Animator duration scale
I remember turning on developer settings a while ago when I was curious about all the settings and one of the options i tried was changing the speed of the transitions etc to 0.5x (which lowers a 1 seconf transition to a 0.5 sec transition for example) and ever since I turned off developer settings to try and focus more on my security I have felt like a snail trying to use my apps.

Imagine your mouse moving very slowly across your desktop or trying to drag a file from one place to another with your DPI turned all the way down. That's what it feels like.

I will probably have to keep my developer settings on now for this one feature but would really appreciate this maybe being located in the display settings and maybe instead of them each having a slider it's one slider that controls all of them meaning they would all be 1x, 0.5x, 2x etc.

Either way I understand you have a lot going on so I assume this would be low priority. Thanks for taking your time to read this though.

P.S I would highly recommend trying out the 0.5x scale for each of the settings so you can hopefully have more of an understanding of how I feel going all the way from 0.5x to 1x scale."
