### ISSUE TITLE
UI - Automatically center apps in dock if empty

### ISSUE THREAD

**Issue by irelativism** [GrapheneOS/os-issue-tracker#2462]
For some users 5 apps or even 4 apps in main app dock is to many but they still want a high density grid.

GrapheneOS should automatically center apps to middle when empty basically what I'm suggesting is a dynamic grid for the dock as you feel it soh default grid might be 5 but if only 3 or 4 apps are present in app dock then those should center automatically and not follow chosed grid on home screen settings

Cheers Irelativism

**Comment by thestinger** [comment]
We don't plan to change this.

**Comment by irelativism** [comment]
Why is that? A reason should always be provided before issue is closed.

**Comment by irelativism** [comment]
Migrated to #2463

**Comment by thestinger** [comment]
It's not the kind of thing we work on. You can use a different launcher with the features you want. You don't have to use the default one.

**Comment by irelativism** [comment]
That is obvious but still doesn't answer my question, how this addition is not useful to make the default launcher better

**Comment by irelativism** [comment]
What I can or cannot do is kinda irrelevant for this issue report

**Comment by irelativism** [comment]
If its a matter of time and resources I would be happy to work on it has a learning exercise with small amount of guidance

**Comment by thestinger** [comment]
It's not the kind of feature we want to invest resources on maintaining and porting to new releases. It would be taking the place of a small privacy or security feature, which is what we want to implement instead. We cannot do everything at once. You can use a launcher providing the features you want. You or someone else could even make a fork of the AOSP launcher fork used by GrapheneOS and use it without it being included in the OS.

**Comment by thestinger** [comment]
Also, please don't refile issues if you disagree with them being closed.

**Comment by irelativism** [comment]
I most definitely will if issue is closed with no reason given, means issue is still standing. So I would suggest you don't close issue just because

**Comment by thestinger** [comment]
This feature request was closed because it's not planned due to being outside the scope of what we work on in GrapheneOS. Not every feature you want is going to be added to GrapheneOS. In this case, you don't need us to add it to GrapheneOS to have the feature because you don't need to use the launcher we provide. Every change to AOSP added to the project has an initial development cost, an ongoing maintenance cost and a porting cost for each new release of AOSP, particularly quarterly and yearly releases. We can only make and maintain a limited amount of changes, so we focus our work on the things that are important to the project. We try to avoid investing our resources into things which aren't related to privacy, security or filling in gaps from not having Google/Pixel components included. We also try to avoid investing too much of our resources into apps which can be replaced with alternatives. In this case, both of those things apply. You're proposing a very niche aesthetic feature and it's simply not the kind of thing we work on. You could add more apps to your home screen if you don't like the aesthetics of a row not being filled uneven.

**Comment by irelativism** [comment]
Again you fail to answer my question, I proposes to help improving default launcher, and it is obviously nonsensical to close a issue without providing a reason shows disrespect and a ease to abuse one position of power, its obviously understood other launchers have such feature, but if I wanted to use such I would be here my intent with this report is to improve default one has I'm providing my own resources and time for the matter. Obviously I don't expect all my issue reports to be accepted but I will not allow you abusive action of closing issue with no reasons provides. But I see you are to full of yourself to collaborate with others even if on a lower level of the OS. Good luck on your never ending ego feeding loop.

**Comment by thestinger** [comment]
The multiple reasons for this being closed have been provided above repeatedly.

**Comment by thestinger** [comment]
The multiple reasons for this being closed have been provided above multiple times.
