### ISSUE TITLE
"Failed to check for updates. An error occured checking for the latest update. The update system will try again soon."

### ISSUE THREAD

**Issue by random3456345** [GrapheneOS/os-issue-tracker#2469]
There is no network issue. DNS resolution for releases.grapheneos.org is successful.
Release channel: Stable

**Comment by random3456345** [comment]
> 3rd gen devices have not been supported for a very long time already, not even extended support.

It's a Pixel 3a so I am afraid it's unsupported. 

My only issue is apparently with firebase push notification. Is it expected?

**Comment by random3456345** [comment]
Thank you for your help

**Comment by thestinger** [comment]
Pixel 3a has been end-of-life since after July 2022. It hasn't received firmware and driver updates since after the end-of-life date and stopped receiving official GrapheneOS extended support after we moved on to Android 13 in August 2022. We unofficially supported it for several more months after August 2022 by providing fixes for the sandboxed Google Play compatibility layer and some security patches. It hasn't received updates since then and therefore you should expect that sandboxed Google Play will stop working. Lack of firmware and driver updates means continued updates from an OS won't make the device secure. You really need to move to a secure device. Pixel 7a has almost 5 years of support remaining and the Pixel 6a has almost 4 years. You should move to one of those. They may drop in price after the upcoming release of the Pixel 8 and Pixel 8 Pro.

**Comment by MantaYay** [comment]
Hi, I get the same error: "Failed to check for updates. An error occured checking for the latest update. The update system will try again soon." But it has this written below it: 'Unable to resolve host "releases.grapheneos.org": No address associated with hostname' 

I have a 8a, hoping for some help.

**Comment by random3456345** [comment]
> 'Unable to resolve host "releases.grapheneos.org": No address associated with hostname'

It's a DNS error message. Your phone was not able to find the IP address associated with the hostname releases.grapheneos.org.

I confirm this domain has the following addresses: 

51.222.159.48
148.113.200.36
51.79.74.15
167.114.114.114

Check your internet connectivity.

**Comment by MantaYay** [comment]
I've tried pausing my VPN and I have internet, but I'm still getting the same message when I try to update. I've also tried updating Beta just to try, same message. I made sure the 'Always On VPN' was turned off under network settings. It's a real concern because I can't remember seeing it update for months now that I'm thinking about it. It sounds like a connectivity issue but I'm not sure what's blocking the connection/updating? Any more suggestions? Would appreciate it.

**Comment by random3456345** [comment]
> I have internet

I don't know what else to say. I see here that your device (Akita) is supported: https://github.com/GrapheneOS/releases.grapheneos.org/blob/main/nginx/nginx.conf#L240

Hopefully the developers can help you with your issue. Good luck.

**Comment by random3456345** [comment]
> only reporting if the device fails to check for updates for a long period of time

It seems to be the case according to their recollection but indeed they ought to make sure it's true.

**Comment by MantaYay** [comment]
Thanks, I'm not sure what else to try besides a reset and hope the phone starts updating again, I've tried everything else. Also my phones not called (Akita). Thanks.
