### ISSUE TITLE
Dose installing PlayStore defeat privacy of Graphene OS ?

### ISSUE THREAD

**Issue by Graphnoob** [GrapheneOS/os-issue-tracker#2472]
I recently switched internet providers to T-Mobile. But in order to complete the transaction, the T-Mobile app had to be used. Auroa Store wouldn't make the app available. So I was forced to install the PlayStore to get to the T-Mobile app.                      Have I defeated the privacy of Grapheme OS ?   If so, what do I need to do to get privacy back ?

**Comment by thestinger** [comment]
The issue tracker isn't for support questions. Please use the Matrix chat rooms or discussion forum at https://discuss.grapheneos.org/.

> Dose installing PlayStore defeat privacy of Graphene OS ?

It doesn't defeat the purpose of GrapheneOS in any way. It's a regular sandboxed app. Please read https://grapheneos.org/usage#sandboxed-google-play. It's no different than installing and using other apps.

> Auroa Store wouldn't make the app available

Aurora Store's default "anonymous mode" sends the wrong device model and therefore doesn't obtain the proper available apps and also doesn't obtain the right variants of apps which can result in apps crashing or having unavailable functionality. Google Camera is an example of an app that will be broken due to Aurora Store fetching the wrong variant. Aurora Store uses the Play Store service and uses an account since that's required. It obtains shared account credentials by default which is a terms of service violation and increasingly hits rate limiting issues, so it may not remain viable long term without needing to create and log into a non-shared account.

**Comment by Graphnoob** [comment]
**Thanks, thestinger, You've answered my question fully. I have made note of the proper site for future Graphene OS related questions.
Sorry for the inconvenience.**
