### ISSUE TITLE
Remove sepolicies for several apps where it isn't required or the app isn't included in the base system

### ISSUE THREAD

**Issue by renlord** [GrapheneOS/os-issue-tracker#255]
For context: https://twitter.com/DanielMicay/status/1292405448381997056

**Comment by boniek83** [comment]
It doesn't require Google Play Services or MicroG. This shell implementation is sufficient: https://github.com/lukaspieper/Gcam-Services-Provider. It makes Google Camera work without any downsides.

**Comment by thestinger** [comment]
> without any downsides

There are downsides to having this SELinux domain exposing a huge amount of attack surface for something that cannot be supported and is very likely to stop working.

**Comment by boniek83** [comment]
> 
> 
> > without any downsides
> 
> There are downsides to having this SELinux domain exposing a huge amount of attack surface for something that cannot be supported and is very likely to stop working.

Fair enough. By downsides I meant GPS or MicroG :)

**Comment by thestinger** [comment]
It would be different if Google Camera was open source and part of AOSP so that we had control over the code, but as is this is granting special privileges (QDSP and Neural Core access) to something outside the project and not signed with our keys. It's also unlikely that it will continue working without Play Services, etc.

**Comment by boniek83** [comment]
Maybe [this ](https://github.com/GrapheneOS/os_issue_tracker/issues/204) is related as well?

**Comment by ponyzucker** [comment]
Can't this be made optional, e.g. via a switch in the settings? Some users might look for a compromise between functionality and security.
If the Google Camera breaks and no workaround is found, the user still has the choice to remove the SELinux domain again.

**Comment by anupritaisno1** [comment]
BTW see oneplus 7 pro, which never had a gcam domain and gcam still launches

It will most likely be the same on pixel. It will work but with limited functionality

**Comment by anupritaisno1** [comment]
And no, we can't have a toggle that reloads selinux policies at runtime

**Comment by anupritaisno1** [comment]
I requested this change. It's not just gcam. There are several other domains for apps that we don't ship in grapheneos

There are also domains for apps like timeservice which actually exist for compatibility with generic system images. There is no grapheneos GSI and this is out of scope of the project. Further the sepolicies only work for a certain pinned signature but we already sign these apps with the platform key so it doesn't make sense to leave these policies in either

**Comment by thestinger** [comment]
@ponyzucker GrapheneOS doesn't include Play Services or Google Camera. It's not about a compromise between functionality and security but rather the removal of an unused and unsupported SELinux domain which adds attack surface. The priority for this was raised by the recent announcement of DSP vulnerabilities which is part of the attack surface this is exposing via Google Camera.

**Comment by thestinger** [comment]
Using Google Camera is unsupported and already very likely to break either due to it growing a hard dependency on Play services which cannot be satisfied with a stub app not incorporated in the OS, or due to it being incompatible with others changes that we make. It's not expected to work, and the temporary ability to use a stub Play services app not incorporated into the OS to get the basics working is not something that's likely to keep working or that we can support. We don't want users to start relying on hacks that are unlikely to keep working. You're going to end up disappointed regardless. Should we really have lower security for everyone to support an obscure hack that's unlikely to keep working, and which is entirely specific to Pixel phones? We're obvious not going to hack in compatibility with Google Camera to other supported devices, so it would become an inconsistency with Pixels.

**Comment by beerisgood** [comment]
Official Google Camera works fine with https://github.com/lukaspieper/Gcam-Services-Provider
Just install it work APK Mirror (block network access before use)
It's a huge difference to even OpenCamera on 3a. Specially the night mode.

So i hope this doesn't get blocked

**Comment by jefferya1** [comment]
Hello! Quick background for context: A few months ago I became aware of, and uncomfortable with, how much data is causally sent from standard Android devices. I was delighted to find the GrapheneOS project, and after the Pixel 4 was added to the supported devices list I bought one. This wasn't a hard decision for me; I had considered getting one for the camera before I knew about GrapheneOS. I was pleasantly surprised at how painless the installation and setup process was. I installed MicroG and Google Camera, disabled network access for both, and was feeling very good about having a functional Pixel-grade camera on a fairly secure and private device. A couple days ago I thought I might learn more about the project; I started browsing the subreddit, and @DanielMicay on Twitter, which led me to this GitHub issue.
To reiterate, I bought the device because 1: it has a best-in-class camera, and 2: it was on the supported devices list for GrapheneOS.

I'll freely admit to being a (relative) novice to security and Android development, and perhaps since I'm willing to compromise somewhat on security in order to have features I'm not in the intended user group for GrapheneOS, but if I'm not able to take advantage of the primary feature of this device I'll question my OS choice. I know I am not the only person in this situation; I've seen other individuals around the web who have told more or less the same story of how they came to install GrapheneOS, and have also emphasized the Pixel camera as part of that decision.

From a project maintainer's perspective I understand not wanting to deal with the special case of supporting a third-party application, but I'd like to re-emphasize that this is a primary feature for many users. I'd ask the maintainers to consider that the security of a system is a moot point if the system doesn't have functionality that users want and expect, thus causing them to not use the system. **I suspect that a large number of users will be upset if their Google Camera app unexpectedly stops working after an update.** 

I don't know enough about this issue to propose a proper solution. Could this SELinux domain be disabled by default, but the users provided with an opt-in option (even if it means a reboot after applying the setting)? Could users be provided with an "at your own risk" way of re-enabling it? Is there another Android distribution that is relatively secure that users who want full camera functionality should be directed towards? Should users be directed to modify and compile their own versions of GrapheneOS if they want gcam functionality?

My thoughts on non-Pixel devices: They're not on the supported devices list. I would think that "supported" devices would get a certain amount of special accommodation.
My thoughts on the Play Store dependencies: The current versions of the Google Camera packages are unlikely to disappear from the web; even if future published versions have a hard dependency on Play Store, the working versions will still be available for current devices. Perhaps I'm missing something key, but I would think that known versions of the app, without network access, should remain secure?

Sorry for the text wall, and thanks for this project.

**Comment by thestinger** [comment]
> I suspect that a large number of users will be upset if their Google Camera app unexpectedly stops working after an update.

You do realize that this is going to happen anyway, without us removing the SELinux policy? You're using a Google app that partially depends on Play services on an OS without it using a hack. Where did you ever get the impression it would keep working?

**Comment by thestinger** [comment]
> My thoughts on the Play Store dependencies: The current versions of the Google Camera packages are unlikely to disappear from the web; even if future published versions have a hard dependency on Play Store, the working versions will still be available for current devices. Perhaps I'm missing something key, but I would think that known versions of the app, without network access, should remain secure?

There are going to continue to be major updates to the OS including moving to new major releases like Android 11 and the quarterly maintenance releases. Also, you're completely wrong about attack surface for the app. The camera app explicitly exposes APIs for taking pictures, videos, etc. to other apps. Google Camera has had past vulnerabilities via those APIs such as allowing apps to automatically take pictures without the user authorizing it. It also has attack surface via the camera itself, especially since it has a ton of post-processing code. It also handles things like barcodes, etc. You certainly need to keep it updated. This gets back to the main issue being that your goals are not aligned with the goals of GrapheneOS. Maybe you should use a different OS after all. It's not going to bother us. When Google Camera stops working there too, maybe you'll understand that relying on hacks to keep an app partially working that's not intended to support the environment wasn't a good idea.

**Comment by domhaas** [comment]
Thank's @thestinger for being that clear.
I'm personally using GrapheneOS since about 3 months. And of course, I'm missing GCam on my pixel 3a. But I haven't switched from Stock for the Camera, but for security.

There are other Projects out there, like [CalyxOS](https://calyxos.org/) which is maybe a better fit for some people who needs GCam or any other GMS dependence-app.
My personally solution for the gcam-issue is to buy me a compact-camera.

**Comment by thestinger** [comment]
Is using one of the many non-Google Camera apps that work without Play Services really so bad that you can't use the phone as a camera?

**Comment by beerisgood** [comment]
> Is using one of the many non-Google Camera apps that work without Play Services really so bad that you can't use the phone as a camera?

The difference from Google Camera to e.g. OpenCamera (with! activated APIv2) is huge. Specially the night mode. You should try it

**Comment by thestinger** [comment]
> You should try it

What makes you think I haven't used Google Camera?

**Comment by thestinger** [comment]
Again, is using one of the many non-Google Camera apps that work without Play Services really so bad that you can't use the phone as a camera? What are you going to do when Google Camera depends on more of Play Services and can't be used via the hack that you're currently using? That's obviously going to happen. At that point, it doesn't break compatibility with anything to remove since it's already going to be broken by that.

**Comment by anupritaisno1** [comment]
I don't know how many times this has to be said

Pixels are the only devices out there to have an selinux domain for google camera

Know what? You'll most likely not find a single non pixel device with such a domain that allows such kind of privilege escalation for a single app

...and yet google camera works fine on all those devices!

We are not breaking gcam. We are just removing its exclusive access to a few parts of the hardware that could be used as attack surface. I don't know who spread this misinformation that we are breaking gcam but we aren't and regardless of what you say this change will go through

@jefferya1 dynamically patching the selinux policy at runtime is NOT something that will be permissible on a hardened ROM and we're talking about something huge: adding entire domains into an sepolicy at runtime can be an even larger attack surface

...it also proves you just came here to give your 2 cents before you read my previous comments on this issue

There is an at your own risk option: you're free to build it yourself

@domhaas if you're going to use a hardened ROM for the purpose of taking good photos I suggest you look into something like a physical camera. Most of them will produce way better photos than a camera running on a phone

**Comment by rhclayto** [comment]
> 
> 
> I don't know how many times this has to be said
> 
> Pixels are the only devices out there to have an selinux domain for google camera
> 
> Know what? You'll most likely not find a single non pixel device with such a domain that allows such kind of privilege escalation for a single app
> 
> ...and yet google camera works fine on all those devices!
> 
> We are not breaking gcam. We are just removing its exclusive access to a few parts of the hardware that could be used as attack surface. I don't know who spread this misinformation that we are breaking gcam but we aren't and regardless of what you say this change will go through

Google camera works fine on all those devices, but without https://github.com/lukaspieper/Gcam-Services-Provider , which depends on this SELinux domain you intend to remove, I can't get it to work at all on the Pixel 4 XL. Either I'm doing something wrong or Gcam-Services-Provider is necessary, & breaking it breaks GCam on GrapheneOS.

It's really unfortunate if there is no way to reconcile the security goal of removing this domain & having the Google Camera. Whatever they're doing under the hood, the app really brings out the quality of the camera, one of the strong suits of these phones.

**Comment by thestinger** [comment]
Gcam-Services-Provider doesn't depend on any special SELinux domain. The special SELinux domains only apply to apps signed with the correct keys. Google Camera is signed with the correct key to use the Google Camera domain. A modified variant of it won't be.

**Comment by lukaspieper** [comment]
@rhclayto, if you have a problem with my app, my repository is the place to ask (discussions are enabled). In general, the GrapheneOS project should not be blamed for anything related to Gcam.

Since the time I implemented the service provider, I was aware that this is only a temporary solution and one day it won't work anymore. Currently new Gcam versions are already not compatible. 

I appreciate that GrapheneOS is strict about security and should not make an exception here.

**Comment by thestinger** [comment]
Mostly done. Google Camera works fine without privileged hardware acceleration access.
