### ISSUE TITLE
Swedbank app stop working after OS update

### ISSUE THREAD

**Issue by CalicoOI** [GrapheneOS/os-issue-tracker#2568]
```
type: ANR
osVersion: google/barbet/barbet:14/UP1A.231005.007/2023101300:user/release-keys
package: lt.swedbank.mobile:21541
process: lt.swedbank.mobile
installer: com.aurora.store

activity: lt.swedbank.mobile/com.swedbank.mobile.app.MainActivity
cause: ANR Input dispatching timed out (7ed2a4b lt.swedbank.mobile/com.swedbank.mobile.app.MainActivity (server) is not responding. Waited 5005ms for FocusEvent(hasFocus=true))
info: ANR in lt.swedbank.mobile (lt.swedbank.mobile/com.swedbank.mobile.app.MainActivity)
PID: 3826
Reason: Input dispatching timed out (7ed2a4b lt.swedbank.mobile/com.swedbank.mobile.app.MainActivity (server) is not responding. Waited 5005ms for FocusEvent(hasFocus=true))
Parent: lt.swedbank.mobile/com.swedbank.mobile.app.MainActivity
ErrorId: 6bd64525-c748-4fce-b639-225cdff6593d
Frozen: false
Load: 0.87 / 1.14 / 1.4
----- Output from /proc/pressure/memory -----
some avg10=0.00 avg60=0.10 avg300=0.20 total=98777364
full avg10=0.00 avg60=0.04 avg300=0.09 total=50808792
----- End output from /proc/pressure/memory -----
----- Output from /proc/pressure/cpu -----
some avg10=2.18 avg60=0.96 avg300=1.26 total=942675241
----- End output from /proc/pressure/cpu -----
----- Output from /proc/pressure/io -----
some avg10=0.00 avg60=0.17 avg300=0.28 total=232032857
full avg10=0.00 avg60=0.10 avg300=0.20 total=163381419
----- End output from /proc/pressure/io -----

CPU usage from 0ms to 12573ms later (2023-10-17 11:54:34.154 to 2023-10-17 11:54:46.726):
  65% 3917/lt.swedbank.mobile: 33% user + 31% kernel
  57% 3826/lt.swedbank.mobile: 2.5% user + 55% kernel / faults: 134 minor
  8.4% 1748/system_server: 4.5% user + 3.8% kernel / faults: 14721 minor 8 major
  4.3% 4328/com.android.systemui: 2.7% user + 1.5% kernel / faults: 17162 minor 21 major
  2% 2043/kworker/u16:8-events_unbound: 0% user + 2% kernel
  1.6% 4751/com.android.phone: 1.1% user + 0.4% kernel / faults: 1462 minor 444 major
  1.6% 5952/com.android.nfc: 1.1% user + 0.4% kernel / faults: 3224 minor 524 major
  1.4% 28642/kworker/u16:14-ufs_pm_qos_0: 0% user + 1.4% kernel
  1.1% 4594/.qtidataservices: 0.6% user + 0.4% kernel / faults: 2474 minor 614 major
  0% 6012/com.qualcomm.qti.services.secureui:sui_service: 0% user + 0% kernel / faults: 1516 minor 418 major
16% TOTAL: 6.2% user + 10% kernel + 0% iowait + 0.2% irq + 0% softirq
CPU usage from 19ms to 370ms later (2023-10-17 11:54:34.173 to 2023-10-17 11:54:34.523):
  63% 3917/lt.swedbank.mobile: 35% user + 28% kernel
  59% 3826/lt.swedbank.mobile: 3.5% user + 56% kernel
    59% 3826/swedbank.mobile: 0% user + 59% kernel
  30% 1748/system_server: 6.8% user + 23% kernel / faults: 455 minor
    30% 3935/AnrAuxiliaryTas: 10% user + 20% kernel
  3.8% 28642/kworker/u16:14-memlat_wq: 0% user + 3.8% kernel
18% TOTAL: 5.5% user + 12% kernel + 0.3% irq

```

**Comment by akc3n** [comment]
> installer: com.aurora.store

Apps can check if they were installed from the Play Store and can choose to refuse to work if they were not installed from the Play Store. See [here](https://akc3n.page/posts/banking-app-issues/#auroraoss-is-problematic) for more details and possible workaround solutions.

More info on latest official information regarding your issue here:
https://nitter.cz/GrapheneOS/status/1712962862832865456#m

Check the [banking apps compatibility with GrapheneOS](https://privsec.dev/posts/android/banking-applications-compatibility-with-grapheneos/) listings, updated instructions located [here](https://github.com/PrivSec-dev/banking-apps-compat-report#banking-apps-compatibility-with-grapheneos).

If your banking app has an report already, please comment on it to update the status for users who maybe tracking it's compatibility.

Feel free to open a [new issue](https://github.com/PrivSec-dev/banking-apps-compat-report/issues/new?assignees=&labels=app+report&projects=&template=app_report.yml&title=%5BReplace+this+with+the+name+of+your+banking+app%5D) if it's not listed and report your results.

Note:
> This is 3rd party community-sourced effort containing banking app compatibility information is maintained by PrivSec.dev. GrapheneOS does not make any guarantees regarding the list's validity.

**Comment by akc3n** [comment]
> installer: com.aurora.store

Apps can check if they were installed from the Play Store and can choose to refuse to work if they were not installed from the Play Store. See [here](https://akc3n.page/posts/banking-app-issues/#auroraoss-is-problematic) for more details and possible workaround solutions.

More info on latest official information regarding your issue here:
https://nitter.cz/GrapheneOS/status/1712962862832865456#m

Check the [banking apps compatibility with GrapheneOS](https://privsec.dev/posts/android/banking-applications-compatibility-with-grapheneos/) listings, updated instructions located [here](https://github.com/PrivSec-dev/banking-apps-compat-report#banking-apps-compatibility-with-grapheneos).

If your banking app has an report already, please comment on it to update the status for users who maybe tracking it's compatibility.

Feel free to open a [new issue](https://github.com/PrivSec-dev/banking-apps-compat-report/issues/new?assignees=&labels=app+report&projects=&template=app_report.yml&title=%5BReplace+this+with+the+name+of+your+banking+app%5D) if it's not listed and report your results.

Note:
> This is 3rd party community-sourced effort containing banking app compatibility information is maintained by PrivSec.dev. GrapheneOS does not make any guarantees regarding the list's validity.
