### ISSUE TITLE
Fingerprint/biometric prompt freezes if you get a notification or call prior

### ISSUE THREAD

**Issue by brxken128** [GrapheneOS/os-issue-tracker#2585]
I tried to unlock my phone while receiving a phone call (to enable mic access, as the prompt said), but my fingerprint wouldn't work and the sensor/screen kept displaying white on/off in time with the vibrations. It's not that it wasn't recognised, the sensor just wouldn't stay on long enough for it to be read.

Also I swiped the notifications tab down/received a notification (I'm not 100% sure which one was the cause, the timing was very tight), and immediately after got a fingerprint prompt from an app that I was opening, but the fingerprint prompt was entirely frozen (despite showing above the notifications panel) - I had to close the app and re-open it to resolve.

**Comment by sec-oops** [comment]
Can you confirm what device/which version?

I attempted to recreate this using the following steps on both a Pixel 7 Pro running UP1A.231005.007.2023101300 and Pixel 8 running UD1A.230803.041.2023102000. For comprehensiveness I ran the same scenario in both the owner and a secondary profile:

- Enrol a fingerprint and allow use for screen unlocking
- Disable Mic Access, set phone to vibrate and lock device
- Call GOS device from a second phone
- Tap unblock access prompt that appears over incoming call screen
- Fingerprint icon appears (solid) over sensor
- Pressing correct finger allows microphone access and call then functions as expected when answering

At no point was I able to recreate the flashing screen/sensor for the calls :/ 

For the notification issue, not entirely sure if it's related but there have been reports of apps such as Signal failing to open after tapping notifications (since A14 update). Was the device in a locked state and then you tapped a notification to open the app and need to unlock the phone, or was the device unlocked and the app you were opening uses the fingerprint unlock itself?

**Comment by R4toLoko** [comment]
I have also experienced the same issue and the solution is to don't disable the mic.
I had to call my partner back many times because I couldn't unlock the screen to enable the mic, sometimes the same happens when all I needed to do was to unlock the phone with fingerprint. It just becomes lag-ish and doesn't work.

Pixel 7 Pro with the latest software update.

**Comment by thestinger** [comment]
Please reopen if it still happens on the 2023120701 release.
