### ISSUE TITLE
Update Ideas

### ISSUE THREAD

**Issue by BarrelBacks** [GrapheneOS/os-issue-tracker#2593]
Here is a update idea inspired by "SimpleWall".

Give the user the opportunity to get asked if a user want to allow access to a site,app etc or not.
After the user(as an example declined it) it will be automaticcaly put down on the block list.
Make also sure to go more in the details, as example allow the user to choose more deeply what exactly he wants to get blocked.
Do the user only want the app to work or also all other stuff like auto update etc.

Also, there should be an option not only to allow acess if the display is on, more if the app has been opend or not.

For more inspiration you can go yourself to the Windows app "SimpleWall"

**Comment by thestinger** [comment]
You can use a VPN service app for filtering based on DNS or IP addresses. It doesn't provide fundamental privacy/security improvements can be trivially bypassed so it has no place in the core OS especially since it can already be done with an app. You can still use an actual VPN while using local filtering this way by using an app support both like Rethink DNS.
