### ISSUE TITLE
"App not installed as package conflicts with an existing package"

### ISSUE THREAD

**Issue by gitdahube** [GrapheneOS/os-issue-tracker#2605]
After installing and then uninstalling google play services on a secondary profile, I get the error: "App not installed as package conflicts with an existing package" when trying to install Aurora Store.  I am thinking g-play services didn't completely uninstall, or left something behind that causes this issue.  I'm not the most technical, so any help would be appreciated.

**Comment by thestinger** [comment]
Aurora Store doesn't use the same app id as Play services. That's not relevant in any way. You're having this issue because you installed another variant of Aurora Store in another profile. Each variant of an app is supposed to use a unique app id. F-Droid doesn't follow this rule and causes usability issues for profiles. Please report the issue to them.

**Comment by gitdahube** [comment]
Hey, thank you! That was a very quick and helpful response! I really appreciate all GraphineOS has to offer! I try to just get all my applications straight from github (sticking to FOSS that is pretty well vetted). There was just one specific app my work uses that I needed. I honestly don't even use aurora on my main profile anymore, kind of surprised I haven't deleted it yet.

-------- Original Message --------
