### ISSUE TITLE
USB-C to 3.5mm Headphone Jack adapter not working

### ISSUE THREAD

**Issue by DavidRLTG** [GrapheneOS/os-issue-tracker#2632]
As the title says.
I use the one that comes with Xiaomi devices
And no, it is not faulty
It works anywhere but my phone
Any ideas? Thank you!
PS: I am on a Google Pixel 8.

**Comment by thestinger** [comment]
There's no analog USB-C audio output on Pixels, only digital. You need a DAC or digital USB-C headphones, not just an analog converter.

**Comment by DavidRLTG** [comment]
Salutations. Sorry for asking but, well, then how do I get my analog headphones working on the Pixel? Any hardware suggestions? Thank you.

**Comment by thestinger** [comment]
Any USB-C DAC. There are small ones of varying prices.

**Comment by DavidRLTG** [comment]
Alrighty! Thank you for your help. Have a great day!

**Comment by thestinger** [comment]
2 examples:

https://store.google.com/us/product/usb_c_headphone_adapter?hl=en-US
https://www.amazon.com/Anker-Adapter-Female-Samsung-Devices/dp/B08Z3B5QL3/

**Comment by thestinger** [comment]
Audio quality, efficiency loudness will be determined by the DAC you buy since they convert the digital audio to analog rather than the phone doing it with an internal DAC. Even the basic Google DAC is higher end than the DAC included in most phones with analog audio output. You'll need to look at reviews if you care about audio quality, etc.

**Comment by DavidRLTG** [comment]
That makes sense, already got that part
(Hence why I already started researching which one would be best)
Welp, Thanks for your help, Dude! You were super helpful, and answered really fast.
Have a great day, I'll go uh.. save up some money I guess, hah
