### ISSUE TITLE
Gesture navigation stops working if a secondary user profile is added

### ISSUE THREAD

**Issue by snrkl** [GrapheneOS/os-issue-tracker#2661]
Pixel8 GOS UD1A.230803.041.2023.103100

Issue: gesture navigation swipes (back, home) stop working if a secondary user profile is added to the device.

Steps to reproduce:
- Add a secondary user profile and finish setting it up
- swap back to the primary user account
- home swipe, back swipe don't work.
- Some gestures can be recognized if actioned immediately after unlocking the device.

Problem persists even after second user account is removed, until device is rebooted.

Worth noting that there are no 3rd party launchers involved.

This issue has a high impact on my GrapheneOS device, as I cannot run my second user profile for apps requiring GSF /Google Play Services

**Comment by snrkl** [comment]
I have tested this on a pixel5 running stock Google Pixel Android UP1A.231005.007 and confirmed the same issue occurs with this combo.

I am unsure how to raise the bug on AOSP as I am not a developer and [user raised bugs seem to get closed and ignored](https://issuetracker.google.com/issues/304001478#comment4).

**Comment by snrkl** [comment]
Confirmed that another GOS phone in my household is having the same issue (P5) 
Pixel 5 Build: UP1A.231005.007.2023103100

**Comment by robovoice1** [comment]
Also on my P6pro (raven) with the same unresponsive 3 point navigation when switching back to owner profile.
Rebooting solves this.

UP1A.231105.003.2023110700

**Comment by snrkl** [comment]
@robovoice1 does the issue stop for you after a reboot?

**Comment by robovoice1** [comment]
yesterday i tried 5 times with always the same result described above. 
-today i changed screen resuolution from full to high and back to full with reboot. settings, display, screen resolution
- And enabled remove animations in settings, screen accessibility, color and motion also with reboot.
both settings in owner profile were changed.

Now all of a sudden this works (no new updates since yesterday)  when switching.

**Comment by hermitworm** [comment]
Confirming with my P6Pro as well, but manifests differently than described above for myself. The issue has been extant since the first 14 build. For me, I can't navigate (except forward, back) but only in the secondary user profile. Having a secondary user profile doesn't affect my main profile's navigation, however, I did have this profile prior to 14 and haven't added another user profile since. Changing the navigation type from gesture to the legacy buttons adds the ability to go home, but still no response trying to go to app switcher. I swore a few builds ago I was able to reboot into the secondary user profile (which wou

UP1A.231105.003.2023110700

**Comment by benutzer74** [comment]
Same here with
Pixel 7a  GOS UP1A.231105.003.2023110700

Using Nova Launcher in all my profiles.
Main profile, Nova works fine.
Secondary profiles, only going back gesture works, no show home screen, no recent apps.

On my Pixel 4a running GOS Android 13, there is no such issue.

**Comment by snrkl** [comment]
@benutzer74 to be clear, this particular issue is when 3rd party launchers are NOT being used. I believe there is another known bug when 3rd party launchers are in use.

**Comment by benutzer74** [comment]
Gesture navigation is being handled by the built in stock launcher, thus such bugs automatically affect 3rd party launchers. If the bug gets fixed, it probably will fix it for 3rd party launchers as well.

**Comment by Chevek** [comment]
I face the same issue, since the upgrade to Android 14 on my Pixel 6.
In the second profile (with use google apps) I often get stuck in the application, gesture to home do not work. I do not use any launcher. 
Workaround is to unlock the profile with tend to send back to home after a delay.

This is quite annoying. Reboot does indeed fix until trigger again.

**Comment by aussedatlo** [comment]
Same here, with Pixel 6a since Android 14

**Comment by snrkl** [comment]
Confirmed issue is still present in UD1A.231105.004.2023111500 on Pixel8

**Comment by Chevek** [comment]
It seems I found a workaround:
- Reboot
- Use it
- Each time you switch to another profile, close all applications first.

Does it work for you too?

**Comment by snrkl** [comment]
Let me re-test and revert.

**Comment by robovoice1** [comment]
re tested with no additional 3rd party launcher, and works as expected 😀 UQ1A.231205.015.2023120800 P6pro raven

**Comment by snrkl** [comment]
Confirmed - I have not been able to reproduce this issue on the current build.
