### ISSUE TITLE
Netflix doesn't work?

### ISSUE THREAD

**Issue by Feuerswut** [GrapheneOS/os-issue-tracker#2721]
It still does work, but i can't install updates, so this is a Play store thing...

![Screenshot_20231127-223715_1.png](https://github.com/GrapheneOS/os-issue-tracker/assets/80217805/4244a5ab-f62d-4af8-8805-0b171ed99b41)

**Comment by flawedworld** [comment]
Netflix have regressed their Play Store listing, and will now only let you install it if you use a Google certified operating system.

**Comment by Feuerswut** [comment]
Thats stupid. Will other apps do that?

**Comment by thestinger** [comment]
Netflix doesn't understand Play Integrity and fails to check for certification in their service but marks their app as requiring it. It's either a bug in their Play Store listing configuration or their service, depending on how you see it.

**Comment by thestinger** [comment]
Some other apps do this. It has been possible for many years, it just used to be based on SafetyNet attestation instead of Play Integrity. The move to Play Integrity changes little. It still has the same split between near useless software checks which can be spoofed (but that's fragile) and hardware-based checks that cannot be spoofed with few apps enforcing that yet.

The reason the Play Store has this configuration is so an app requiring Google certification, etc. via Play Integrity can avoid listing the app for users who aren't going to be able to do it. What Netflix is doing with it makes absolutely no sense.

**Comment by Feuerswut** [comment]
@thestinger And if Banking Apps and more are going to be disabled, and many Apps move over to Play Integrity, what are we going to do? Can we get hardware attestation services? Users may have to move over to stock...

**Comment by Feuerswut** [comment]
I will go check the Digital Services Act and see if something can be done legally.

**Comment by thestinger** [comment]
GrapheneOS supports hardware attestation. See https://grapheneos.org/articles/attestation-compatibility-guide. These apps are choosing to disallow using an OS not certified by Google that's much more secure than any of the ones which are. I agree it's anti-competitive nonsense but it doesn't mean they will do anything about it.

**Comment by thestinger** [comment]
Play Integrity uses software or hardware attestation to check for Google certification. GrapheneOS is not Google certified. Services can use hardware attestation directly and permit GrapheneOS, if they want. At the moment, we haven't seriously tried to convince any developers to do this and we lack the resources to do it so it's not going to be something we pursue for a while.
