### ISSUE TITLE
A reboot due to overheating should not be considered an acceptable time to install updates

### ISSUE THREAD

**Issue by tiedotguy** [GrapheneOS/os-issue-tracker#2796]
I was stuck without navigation for 5 minutes in 100+ heat, due to the phone deciding that after a reboot due to overheating, it was an acceptable time to perform updates (and subsequent app optimization).

Updates should not be done as a result of a crash, only user initiated (pushing reboot on the notification, not reboot from the power menu) and user configured (ie, idle/automatic after update) reboots.

**Comment by thestinger** [comment]
That's not how it works. The update was already installed.

**Comment by tiedotguy** [comment]
As I understand it, it's installed to an alternate partition. Activating that alternate partition should only occur on user action, not system failure.

**Comment by thestinger** [comment]
It was activated when the update completed, that's how the update system works. The update was finished installing before anything went wrong and caused a reboot. We could add a pause button for the post-boot app recompilation in the future.

**Comment by tiedotguy** [comment]
Right, that's what makes it a bug.  A way to pause would be a sufficient workaround though.

**Comment by thestinger** [comment]
It's not a bug, it's just how A/B updates work. It's the same on the stock Pixel OS. The update is installed in the background and activated after it's validated. The update is NOT installed on reboot, it was already finished being installing before that. The reboot is only needed to boot up the already fully installed new version. Since GrapheneOS uses ahead-of-time compilation, it has to recompile apps after reboot, but the stock OS doesn't. Recompiling apps isn't about installing the update but rather a consequence of having an updated OS needing to redo compilation.
