### ISSUE TITLE
SSBD and KPTI are broken in the Android 11 kernel for Pixel 4 devices 

### ISSUE THREAD

**Issue by randomhydrosol** [GrapheneOS/os-issue-tracker#283]

**Comment by thestinger** [comment]
Removing the Android 11 port label since this is a Pixel 4 specific issue caused by kernel changes not directly related to Android 11.

**Comment by thestinger** [comment]
Going to mark the Android 11 port as done even though this isn't completed since it's not directly related to migrating to Android 11. It's caused by changes they made to ShadowCallStack, CFI, etc. which were shipped in the next major release (Android 11) but are specific to these kernels rather than being an inherent part of Android 11.

**Comment by thestinger** [comment]
Not an issue for the more recent Pixel 4a (5G) and Pixel 5 devices.

**Comment by thestinger** [comment]
This was resolved.
