### ISSUE TITLE
GrapheneOS automatically downloads updates over metered network

### ISSUE THREAD

**Issue by vbooka1** [GrapheneOS/os-issue-tracker#2946]
Hello,

https://grapheneos.org/usage#updates-settings

> The "Permitted networks" setting controls which networks will be used to perform updates.
> It defaults to using any network connection.
> It can be set to "Non-roaming" to disable it when the cellular service is marked as roaming or "Unmetered" to disable it on cellular networks and also Wi-Fi networks marked as metered.

Please consider changing this to "Unmetered" by default, or to just notify the user instead of automatically downloading an update over the mobile network.

related: #1257 #91

**Comment by thestinger** [comment]
That's not going to be changed since many people don't have access to unmetered networks for long periods of time or even never have access to them. It's unacceptable for people to fall very behind on OS updates. OS updates are mostly very low bandwidth usage as long as you don't fall behind due to delta updates. If you fall more than around 2 weeks behind and there isn't a delta to upgrade in one step, that will use a huge amount of bandwidth (up to around a gigabyte) rather than something like 30M or 80M depending on how much changed in the release. Updates are **always** going to remain fully automatic by default. If you can't afford to download 30M to 80M for delta updates automatically, that's a very special case. App updates also likely currently use more bandwidth than OS updates since we don't support deltas for the app repository yet. Implementing deltas for the app repository would be what someone who cares about this should prioritize.

**Comment by thestinger** [comment]
Delaying OS updates will in fact use dramatically more bandwidth if you fall around 3 weeks behind and there isn't a delta update. The regular Vanadium updates currently use a lot of bandwidth due to lack of delta support. We do compress APK transfers so it's a lot less than it would be if the APKs were downloaded directly since there's a very large amount of uncompressed data in the APKs to allow directly memory mapping it from the APK.

**Comment by vbooka1** [comment]
> If you fall more than around 2 weeks behind and there isn't a delta to upgrade in one step, that will use a huge amount of bandwidth (up to around a gigabyte)

that was exactly my case, an updater ate my data package before I've noticed :(
