### ISSUE TITLE
BitWarden unable to authenticate with WebAuthn in Vanadium

### ISSUE THREAD

**Issue by Keeblo** [GrapheneOS/os-issue-tracker#2974]
Device: Pixel 6A
Android version: 14 with December 5th, 2023 security update
Build number: UQ1A.231205.015.2023121200

Problem:
```
When attempting to authenticate my second factor (a Yubikey 5 using NFC) I receive this error after scanning the Yubikey:

An error has occurred.
Please make sure your default browser supports WebAuthn and try again.

NotReadableError: An unknown error occurred while talking to the credential manager.
```

Potentially relevant details:

1. Google Play Services are installed and sandboxed.
2. I'm using the default Vanadium browser.
3. BitWarden was installed using F-Droid, *not* Google Play (the Google Play version has Microsoft telemetry enabled last I checked).
4. I think that I've enabled Storage Scopes for Google Play as mentioned here ( https://discuss.grapheneos.org/d/1274-how-to-use-fido2-security-keys/4 ).
5. I'm pretty sure that my BitWarden account is configure to use FIDO or FIDO2, not Yubico's proprietary Yubikey OTP service.
6. I'm attaching relevant screenshots to this post.

Is this a bug, or is my phone misconfigured? Either way, is there a configuration change that I can make to allow FIDO2 authentication?

Thank you all for your time and your commitment to building an amazing operating system!

![Google_Play_Services_permissions](https://github.com/GrapheneOS/os-issue-tracker/assets/7781968/d454d408-8180-4f38-823d-f537f4a2c679)
![Error_from_BitWarden](https://github.com/GrapheneOS/os-issue-tracker/assets/7781968/359633f5-b5a0-49f0-8333-35021ae144b2)

**Comment by thestinger** [comment]
The F-Droid package likely doesn't have this functionality. No reason to think this is an OS issue.

**Comment by Keeblo** [comment]
> The F-Droid package likely doesn't have this functionality. No reason to think this is an OS issue.

Please elaborate, if only to satisfy my curiosity. Does this functionality require something in Google Play Services that the F-Droid version would have removed? I'm curious to learn how this stuff works :-)

P.S. Thank you for the lightning fast response!

**Comment by thestinger** [comment]
The main way apps implement FIDO is with the Google FIDO library. Apps can provide their own implementation where they provide a UI for choosing the type of security key and request the ability to connect to it. Since Play services provides this, nearly everyone uses that  and there wasn't much demand for a library providing a simple implementation for apps. There's an open source library available for doing this, but it has to be licensed from the company for use in anything other than a GPLv3 app. It's also not actively developed.

https://github.com/cotechde

It's unfortunate there's no proper permissively licensed library for this and it's why everyone just uses Play services with no fallback option.

**Comment by Keeblo** [comment]
Thank you for the quick and thorough explanation!

**Comment by thestinger** [comment]
F-Droid removes proprietary libraries from apps so that build of the app is likely just missing this library without providing a replacement for it.
