### ISSUE TITLE
Android Auto does not show any of my Map apps

### ISSUE THREAD

**Issue by DavidRLTG** [GrapheneOS/os-issue-tracker#3004]
Salutations! I installed Android Auto, Enabled unknown sources, and all my apps show up BESIDES Waze and Organic Maps, Despite them supporting Android Auto. Help?

**Comment by DavidRLTG** [comment]
I got a modded version of Waze, APK file, as I trust even that more than the official version and I got Organic Maps from F-Droid.

**Comment by thestinger** [comment]
That sounds like the issue. Apps needs to have explicit support for Android Auto.

**Comment by DavidRLTG** [comment]
What do you mean? Waze and Organic Maps both officially support Android Auto

**Comment by thestinger** [comment]
Try the Organic Maps variant from the Play Store instead of F-Droid, and try the official Waze app.

**Comment by DavidRLTG** [comment]
Uh.. Sure!
And aye, will this problem ever be solved somehow?

**Comment by thestinger** [comment]
There's no indication of a problem yet since you haven't tried the regular Play Store release of Organic Maps or the regular release of Waze yet.

**Comment by DavidRLTG** [comment]
Well, I tried OsmAnd from google play as an example which also supports AA, but it didn't show up. Any tips?

**Comment by lyphyser** [comment]
Some sources claim that, at least for navigation apps, this is caused by a check in Android Auto or Google Play Services that only allows apps installed from Google Play to show up in Android Auto (some sources claim that spoofing the installer name used to work, but doesn't anymore).

If there is indeed such a check, it would be nice for GrapheneOS to neuter it, ideally in GmsCompat if possible, or otherwise with automated SMALI patching and signature spoofing of Android Auto and/or Google Play Services.

**Comment by thestinger** [comment]
Seems to be working as intended.

**Comment by thestinger** [comment]
> If there is indeed such a check, it would be nice for GrapheneOS to neuter it, ideally in GmsCompat if possible, or otherwise with automated smali patching and signature spoofing of Android Auto and/or Google Play Services.

Why? Removing security checks is not what we do. Sandboxed Play Store is the safest way to get apps from the Play Store. We don't recommend getting apps from APK mirror sites or from an alternate client like Aurora Store which doesn't validate Play Store signatures proving apps came from the Play Store like Aurora Store.

**Comment by thestinger** [comment]
> APKs can be obtained from other reliable sources such as directly from the app developer website or repository.

There's no confirmation that this doesn't work when that's how the developer set it up to work.

**Comment by thestinger** [comment]
This is not a support platform. It's not a place to request support or ask questions. Without evidence that there is any issue, this is the wrong place to be.

**Comment by lyphyser** [comment]
I think there is some evidence that it doesn't work, although the exact technical mechanism is unclear and might require disassembling and/or debugging Google code to find out:
- https://developer.android.com/docs/quality-guidelines/car-app-quality claims that "Apps don't work with Android Auto unless they are installed from the Play Store or the ONE store"
- This comment claims that OsmAnd~ from f-droid works with Android Auto, but only if the installer is spoofed to be Play Store via adb: https://github.com/osmandapp/OsmAnd/issues/13514#issuecomment-1086203926
- This comment claims the spoofing worked until Android 10, but stopped working in Android 11 or 12, presumably because Google started checking something else as well (maybe a whitelist of package signatures? or maybe it's now possible to query the installer signature and not just the id, or pm install no longer allows spoofing?): https://github.com/osmandapp/OsmAnd/issues/13514#issuecomment-1173075386
- Several sources claim that /data/data/com.google.android.gms/databases/phenotype.db contains a whitelist of Android Auto apps, in particular records in the table Flags with packageName="com.google.android.gms.car" and name="app_white_list", although it seems to only contain package names (https://www.idaf.it/index.php?topic=56648.0)

**Comment by thestinger** [comment]
@lyphyser This seems to be working as intended and is a meaningful security check. Whitelisting based on app id is only secure in combination with either a check for whitelisted app signing keys or a check for the app coming from a certain store. A check for the app coming from a certain store is only secure if the store is guaranteed to be included in the OS (stock OS) or the signing keys are checked like our sandboxed Google Play compatibility layer does for these apps. This security check should work as intended on GrapheneOS. We're not going to bypass security checks and weaken the security model. It may already be possible for apps to have their app id and signing key whitelisted for distribution outside the Play Store. This only applies to the official Android Auto which requires having Play services and the Play Store. Please avoid requesting that we remove meaningful security checks. It's not what we do, and sandboxed Google Play doesn't do any of it. The reason we made sandboxed Google Play in the first place is because the only available option removes / skips a bunch of security checks and introduces important data leaks, etc. That's unacceptable for GrapheneOS. Security features available won't be downgraded, it's against how we do things. It would be possible to implement security for this in another way but that's really not our job. Android Auto is not our app, and we don't currently have an alternative implementation of it.

**Comment by thestinger** [comment]
Apps downloaded from the Play Store have a signature included in their metadata proving they came from the Play Store. Checking the app id in combination with this signature is a valid security check, which indicates Google has signed off on it being uploaded by the actual developer.

Alternatively, checking that the OS marks the app as coming from the Play Store and that the Play Store app that's installed has the valid signature or is a system app should also be valid. Since we check the signatures for sandboxed Google Play, it being implemented based on the assumption it's included in the OS should be fine in a case like this.

You may not like that combining an app id check with checking for Google's Play Store signature or checking that an app was installed from the Play Store can be used instead of checking the app's own signing key. It is a valid, secure way to check that it's the official app, and also the only robust way to do it for apps that are not your own due to how Play Signing key rotation works. Play Store uses Play Signing for all new apps and existing apps are being pushed to migrate to it. Play Signing can rotate keys for new install, which developers can trigger themselves or the Play Store can do it automatically to replace legacy signing algorithms, after they upgrade HSM infrastructure, etc. This means that trying to pin keys for Play Store apps no longer really makes sense unless it's your own app. For the Play Store variant of apps, it makes more sense to confirm it came from the Play Store via the Play Store metadata.

**Comment by lyphyser** [comment]
Well, if you wrote an alternative implementation of Android Auto, I would guess you wouldn't implement a check in it that forbids apps installed outside Google Play from being displayed on the car screen in some cases (btw, Google Play might not even be installed on GrapheneOS).

If so, that doesn't seem a meaningful security check and thus it can be bypassed in the Google implementation of Android Auto as well without compromising security.

Or in other words, it surely takes less work to alter the undesirable parts of Google's Android Auto code (preferably in GmsCompat so it's less likely to break on update) than rewriting it from scratch.

**Comment by thestinger** [comment]
We're not going to remove the security check, whether or not it's our own implementation. We could provide an alternative approach to the security check not depending on the Play Store but would still do it.

Not clear why you're claiming that it's not a meaningful security check. Enforcing that an app is genuine is a meaningful security check. Checking app id + signing key is one way to do that. Checking app id + signing metadata proving it came from a specific source is a way of outsourcing it to that store, and for a store which signs apps themselves it makes more sense than checking a signing key they can rotate for new installs. Android supports key rotation authorized by the previous signing keys which provides transparent, automatic key rotation via the OS package manager and pinning checks can work with it. However, that feature isn't currently used by the Play Store. When either a developer or Google rotates the Play Signing key, it currently just starts using the new key for fresh installs and leaves existing installs alone. They could use Android's standard key rotation feature for existing installs, and they should. They could use it for new installs too, but they don't have to unless they want to avoid breaking checks for the specific signing key. It would be nice if they moved to standard key rotation at least for Android 13+ via key signing v3.1 and they almost certainly will at some point, but for now checking that the app came from the Play Store does actually make more sense for apps using Play Signing.

**Comment by DavidRLTG** [comment]
Okay but, I really don't want apps from Google Play, even if it's an app I trust. Even if it's Organic Maps or OsmAnd, I want to use it from F-Droid. Why can't we get some sort of fix for this?

**Comment by lyphyser** [comment]
Why is there a need to "enforce that an app is genuine" to display it on the launcher on the car screen?

It seems to me that if an app is fine to be displayed on the app launcher on the smartphone screen (which is any app that is successfully installed and wants to be displayed there), it should be OK to display on the car screen as well, since it's pretty much the same thing.

It might be fine to be able to check that apps are indeed a specific app in general, but I don't see why it would be something that the car screen implementation needs to be at all.

In fact, it would be nice to be able to run ALL apps on the car screen, not only those that explicitly support Android Auto, if that's technically possible.

**Comment by thestinger** [comment]
If the developers want Android Auto to support using releases they sign themselves, they need to work that out with Google. Builds signed by F-Droid are not trustworthy since F-Droid is known to have insecure infrastructure and highly untrustworthy developers/packagers. We're certainly not going to add something which treats F-Droid releases as equivalent to the Play Store releases. That's not valid. It would be more reasonable to treat official developer releases as equivalent to what they release via the Play Store, but we're not interested in adding hooks overriding this.

We got Google to add Vanadium as an allowed browser for security key support and removed the compatibility layer adding it to a similar list of browsers and key fingerprints. We're not going to do this for other people's apps and aren't doing it for Vanadium anymore since we got it added.

**Comment by thestinger** [comment]
> Why is there a need to "enforce that an app is genuine" to display it on the launcher on the car screen?

They made this security improvement for Android Auto apps, so we're going to keep it. We don't remove security improvements.

> It seems to me that if an app is fine to be displayed on the app launcher on the smartphone screen (which is any app that is successfully installed and wants to be displayed there), it should be OK to display on the car screen as well, since it's pretty much the same thing.

That's not what they implement though. They do something more secure.

> It might be fine to be able to check that apps are indeed a specific app in general, but I don't see why it would be something that the car screen implementation needs to be at all.

It would be nice to check that apps are genuine in general, which is a planned feature for GrapheneOS via the combination of an app signing key pinning database and verification of Play Store signing metadata. This will be possible to use to verify that an app is signed with the official developer keys or is the official Play Store release.

For Android Auto, they did something similar as a mandatory baseline, which we aren't going to remove.

> In fact, it would be nice to be able to run ALL apps on the car screen, not only those that explicitly support Android Auto, if that's technically possible.

Apps have to opt-in to Android Auto being allowed to see content from them and send the content to it themselves. Allowing Android Auto to see data from all apps would be a violation of the principles of the sandboxed Google Play compatibility layer. That's not simply adding dangerous special privileges but ones that don't even exist on the stock OS.

**Comment by thestinger** [comment]
GrapheneOS is not going to remove security and other checks done by apps. That's not what we do. We're also not going to add a way to block ads in the official YouTubve app without subscribing, which at least wouldn't reduce security, but is just not what we do. We don't mess with how app developers want their apps to work beyond us adding privacy and security improvements such as Contact Scopes, Storage Scopes, Sensors toggle, baseless app sandbox improvements, etc. We're not going to hook into apps to fix your pet peeves with them.

**Comment by lyphyser** [comment]
But the problem is that users can install a YouTube client that is modified to not have ads (e.g. the NewPipe app or an hacked YouTube app if available) so there is no need for GrapheneOS to mess with the official YouTube app.

OTOH AFAIK the user can't install their own alternative Android Auto implementation since the OS only gives the necessary permission to the actual Android Auto.

Hence, the Android Auto provided by GrapheneOS is not merely Google's app, but rather it is effectively the way the OS supports car screens.

Hence, declining to alter the behavior of Google's Android Auto means being hindered in being able to improve GrapheneOS's support for car screen overall (until/unless someones writes an alternative implementation that is accepted, but that might be years from now or might never happen), and so I think that should not be GrapheneOS's policy, although it would be nice to also provide an option to fully preserve the original Google behavior in case the user wants that.

**Comment by lyphyser** [comment]
I suppose changing GrapheneOS to let the user grant the Android Auto permissions and GmsCompat workarounds to any application of their choice (at least if the app opts in) could be a better alternative, since that means there is no longer any need for GrapheneOS to be directly involved in distributing or developing car screen support.

**Comment by thestinger** [comment]
We have a hard rule against removing security checks, so it's not going to happen. We also don't open up new holes in the security model that are not there in the stock OS. You seem to misunderstand what we do here.

> GmsCompat workarounds

None of this is relevant to other apps. You misunderstand what sandboxed Google Play provides. It has no special access or privileges. That's not how we do it. Android Auto support is an extension that goes beyond the normal sandboxed Google Play support and is not possible to provide as part of it without special toggles.

> Android Auto permissions

This is a special case that was made for Android Auto, not part of the baseline sandboxed Google Play support, and isn't going to be supported for other apps. For wired support, most of the functionality could probably be done with an accessibility service though.

If you don't like the completely optional Android Auto support, just don't use it.

**Comment by thestinger** [comment]
> Hence, declining to alter the behavior of Google's Android Auto means being hindered in being able to improve GrapheneOS's support for car screen overall (until/unless someones writes an alternative implementation that is accepted, but that might be years from now or might never happen), and so I think that should not be GrapheneOS's policy, although it would be nice to also provide an option to fully preserve the original Google behavior in case the user wants that.

You're assuming that special privileges are needed to support car screens, but it doesn't seem that you've tried making an app simply using regular USB support and an accessibility service.

**Comment by thestinger** [comment]
We decided to add special toggles for supporting the official Android Auto app as a very special case. It has a signature check for Android Auto and uses the regular sandboxed Google Play approach to the extent that's possible. For the special privileges it requires that we could not figure out how to eliminate as we do for sandboxed Google Play, we stripped down what those privileges can do by making more limited variants of them, and they are not granted to it unless users explicitly enable the relevant toggles. Over time, we can gradually eliminate more access as the standard permission model gains the capabilities or if we figure out other approaches. If we can fully do it, it can be part of the baseline sandboxed Google Play with no toggles. The toggles are a temporary workaround for not being able to do it in the way we wanted and the way we handle sandboxed Google Play itself.

**Comment by lyphyser** [comment]
Letting the user choose to treat another app as if it were Android Auto would be useful since it would make it easy for the user to decompile Android Auto, patch it, rebuild an APK and have it work by choosing their own APK as the "car screen support app" that would receive the permissons.

Not having the additional permissions would require to do something that you deemed too hard or impossible; not having the GmsCompat workarounds might be manageable by copying the code from GmsCompat or something equivalent to the patched APK, but it would require additional work on the user's part.

There are additional reasons one may want to patch Android Auto: for example, it has an obnoxious check that disables some functionality if the car is not parked (such as non-voice typing and game apps), even though the passenger might be using it or the driver may judge it's safe enough to do so, and it would be nice to get rid of that check.

**Comment by thestinger** [comment]
> Letting the user choose to treat another app as if it were Android Auto would be useful since it would make it easy for the user to decompile Android Auto, patch it, rebuild an APK and have it work by choosing their own APK as the "car screen support app" that would receive the permissons.

Apps are choosing to explicitly trust Android Auto with their data. You're proposing violating the security model, which isn't what we do.

> Not having the additional permissions would require to do something that you deemed too hard or impossible; not having the GmsCompat workarounds might be manageable by copying the code from GmsCompat or something equivalent to the patched APK, but it would require additional work on the user's part.

Making a variant of Android Auto is not the right approach but rather making a new implementation of the protocol that's not dependent on Google Play (or microG).

> There are additional reasons one may want to patch Android Auto: for example, it has obnoxious checks that disable some functionality if the car is not stopped or parked (such as non-voice typing and game apps), even though the passenger might be using it or the driver may judge it's safe enough to do so, and it would be nice to get rid of that check.

Okay, but we're not going to be doing it, and we're going to be upholding the Google Play and Android Auto security model as part of sandboxed Google Play and the largely but not entirely deprivileged Android Auto support, which wasn't quite possible to do as part of baseline sandboxed Google Play.

**Comment by thestinger** [comment]
The reason not all apps can be used with Android Auto is because apps don't allow other apps to get their audio/video output and create input events into them. Apps are sandboxed and that's not allowed. Accessibility services are a reluctantly supported special case that's incredibly dangerous because it allows doing these things. It's not meant to be used for stuff like this, but it can be used for it. It's not allowed on the Play Store, but it can be distributed outside it. Android Auto doesn't use it because it would be a huge hack and would give more access than required too.

Apps which support Android Auto are explicitly sending data to Android Auto and receiving data from Android Auto. That's why it doesn't need as many special privileges as it might seem it would. Wired Android Auto **barely** requires any special privileges, but wireless Android Auto is fair bit more than just regular pairing, unfortunately. Android Auto isn't as far from being able to work without special privileges as we expected, and we plan to work towards eliminating as much as possible over time.

These things are going to be provided to anything else. It's a workaround specifically for Android Auto. Other things should be implemented without special privileges from the beginning. Making a special case for Android Auto with a secure signature check for it doesn't mean it's valid to do it for other things within our approach. We didn't add a way to violate the secure model in general but rather hard-wired specific support for Android Auto with a secure check for it. We also greatly reduced the privileges it requires to a quite reasonable set of them and split it up into separate toggles. Enabling the wired Android Auto toggle barely gives it any special access. Enabling wireless has to give a fair bit right now, but perhaps some can be eliminated. Ideally they would eliminate it on their end by making a simpler approach, but there has to be backwards compatibility.
