### ISSUE TITLE
Android Auto voice commands fail to work on first attempt, but work afterwards

### ISSUE THREAD

**Issue by lyphyser** [GrapheneOS/os-issue-tracker#3015]
When attempting to use voice with Android Auto, either via a dedicated button on the car, or the voice input button on Google Maps, the first attempt always fails with a spoken error message, and then afterwards, if one tries again, it works properly until the phone is disconnected and reconnected from the car, at which point it again falis the first time.

It would be nice if it always worked. Perhaps, since the microphone permission is only for "while the app is in use", it doesn't think the app is in use the first time, but then it becomes "in use"?

**Comment by thestinger** [comment]
> It would be nice if it always worked. Perhaps, since the microphone permission is only for "while the app is in use", it doesn't think the app is in use the first time, but then it becomes "in use"?

It shouldn't be the cause.

**Comment by niels-beier** [comment]
This isn't a bug caused by GrapheneOS. I just tested it on my S21 with One UI 6.0 (Android 14) installed with the newest Android Auto Version. Every first try to use the voice commands fails, while every subsequent try succeeds. This bug exists for a long time and after many attempts of trying to report it, Till now nothing changed.
