### ISSUE TITLE
Kernel crashes during charging animation while shutdown.

### ISSUE THREAD

**Issue by ilmatari** [GrapheneOS/os-issue-tracker#3043]
**Most likely low priority as it happened in "shutdown" state**

The battery of my Pixel 5A died just as I was about to snap my friends my new glasses 🕶️. Naturally I found the nearest Hesburger 🍔, ordered coffee ☕ and plugged in my phone to finish what I started.

My phone had died so it was a cold start during which i believe the default mode is "shutdown" (in quotes) which displays battery percentage and a modest charging animation. My phone froze mid-animation. I was still able to force restart and that's when I got a notice that kernel had crashed so I'm guessing that crash took place when the animation froze.

I guess It's also possible that kernel crashed when my battery died, but looking at the [logs](https://pastebin.com/raw/37DYsAEr) it says that charger is connected and that it's a cold restart so it seems to me that kernel crashed while phone was in charger mode or shutdown state.

> Anyway, probably not important.
> I just wanted to use the opportunity to contribute to open source.
> 
> [I'm doing my part meme]
>
> BTW, why is GrapheneOS and to be direct Android project still using Linux v4.19.
> I mean I'm not complaining -- it's not like we could do anything with the updated kernel without rooting --, I just find it odd.
>
> I love GrapheneOS (even with all the drama) & I hope GrapheneOS will become the norm. I'm so waiting for GrapheneOS forks.

Enough rambling. I have new glasses to post about.

**Comment by thestinger** [comment]
Appears to be a hardware/firmware issue, or the hardware being configured incorrectly by drivers.

> BTW, why is GrapheneOS and to be direct Android project still using Linux v4.19.

It isn't using that. The LTS branches for Android 14 launched devices are 5.15 and 6.1. The current generation devices are using the 5.15 LTS branch. 6th/7th generation Pixels use the 5.15 LTS branch. Due to the longer lifetime, 6th/7th and especially 8th generation Pixels will likely move to new LTS branch, and there are experimental ports of the Pixel 6 to 5.15 and 6.1. You're using the Pixel 5a which is last 5th generation Pixel that's not end-of-life yet, but it's approaching it.

> it's not like we could do anything with the updated kernel without rooting

Not clear what you mean. It also seems that you're missing the LTS branches get frequent updates.
