### ISSUE TITLE
Crashs and memory corruption

### ISSUE THREAD

**Issue by Skealz** [GrapheneOS/os-issue-tracker#3104]
Hi,
I'll try to be precise and short.

I use GrapheneOS on a Pixel 8. It is a reconditioned phone, from BackMarket, that I've got since ~2 weeks.
I've factory reset 2 times. Because : 
- I've got regular app crashing, but that's kind of okay and someone told me that it is normal (notably because of MTE)
- I've got regular system_server crash (I've open 2 issue for that #3067 and #3076, but there are other scenarios where it happen, like normally using an app, like Signal, Vanadium or Element).
- Sometimes (maybe 3 times per day, that's still a lot), kernel crash with device rebooting. Issue #3070 but there are other scenarios too...
- And what made me open that issue, happened today : Memory corruption and unable to boot

Memory corruption and unable to boot description : 
- I was trying to switch to a secondary profile, but typing my password correctly failed to open the profile (tried several times). Each time It went back to asking my password. I switched to Owner, then retried to secondary, then the phone stopped and asked me If I wanted to wipe data because of corruption. I said no, and tried to reboot.
At boot, the logo phase went OK (Google then GOS) and then I end up in a complete black screen. The phone is alive, because pressing power button gives me the "Power down/Reboot" menu. I tried booting in fail safe, but same thing. I tried to wait a bit also.
I end up wiping data through recovery, and booting worked again.

It feels to me that all the crashs are "normal" bugs, not due to a faulty device. But the memory corruption is quite something, so now I'm not sure what to do.

Questions : 
- Is my device faulty (storage failing) and should I replace it ?
- I installed the stock Pixel OS to test things and compare. What may I see that could confirm my device is faulty ?
- If you judge my device is OK, should I continue to open issues about system_server crashs and kernel crashs ?

Thanks a lot !

EDIT: 
Noticed system_server crashes already, on the stock OS

**Comment by thestinger** [comment]
You appear to have a device with faulty hardware. There's nothing we can do about that.

> I've got regular app crashing, but that's kind of okay and someone told me that it is normal (notably because of MTE)

This is not normal or okay. If an app has memory corruption bugs detected by MTE or hardened_malloc, you should report the bugs to the developer. You can use exploit protection compatibility mode. People don't many more regular app crashes on GrapheneOS any more so than the stock OS, other than memory corruption bugs being detected, which are usually clearly memory corruption bugs in the crash logs.

> I've got regular system_server crash (I've open 2 issue for that https://github.com/GrapheneOS/os-issue-tracker/issues/3067 and https://github.com/GrapheneOS/os-issue-tracker/issues/3076, but there are other scenarios where it happen, like normally using an app, like Signal, Vanadium or Element).

You've made it clear there are hardware issues now so that explains both of these problems now. It explains why no one else has had them.

> And what made me open that issue, happened today : Memory corruption and unable to boot

This shows the hardware is faulty, and explains the other problems.

> It feels to me that all the crashs are "normal" bugs, not due to a faulty device. But the memory corruption is quite something, so now I'm not sure what to do.

None of the issues you're describing are normal issues people experience. The vast majority of users do not experience any regular crashes.

> Is my device faulty (storage failing) and should I replace it ?

It's definitely faulty.

> I installed the stock Pixel OS to test things and compare. What may I see that could confirm my device is faulty ?

Stock Pixel OS doesn't have user-facing crash reporting so lack of that doesn't mean it's not having the same issues. You would have to notice kernel panics, etc. which usually occur while the device is idle rather than in use based on the device having rebooted silently when you come back to it. There won't be a crash report like GrapheneOS.

We're planning to tone down the default enabled crash reports when it comes to ones that are almost never GrapheneOS issues because people attribute hardware and Android bugs to GrapheneOS because of it and think it's causing stability issues for them simply because we're reporting the problems to them.

> I installed the stock Pixel OS to test things and compare. What may I see that could confirm my device is faulty ?

What you really need is running a memory test system but that would require flashing something providing that in early boot without loading a normal OS and we don't know if it's available.

> If you judge my device is OK, should I continue to open issues about system_server crashs and kernel crashs ?

No, it's clearly faulty hardware after showing data corruption and all the issues have to be attributed to it. It's likely not actually an SSD problem but faulty memory that's randomly corrupting data.

**Comment by thestinger** [comment]
> Noticed system_server crashes already, on the stock OS

It's nearly 100% clear that it's faulty hardware based on the data corruption report which then went away, but this is further proof that it's a hardware flaw. GrapheneOS and the stock OS do not randomly crash in all kinds of ways like this. There are crashes, but they're almost always caused by a specific usage pattern.

We believe it's specifically faulty memory, but it could be a faulty SoC cache or CPU. We've seen higher than usual hardware failures with the Pixel 8 based on the number of user reports about it, perhaps due to a faulty batch of memory.
