### ISSUE TITLE
Feature Request: Notification LED Dot Emulation like Holey Light

### ISSUE THREAD

**Issue by stevenagev** [GrapheneOS/os-issue-tracker#3106]
Having upgaded to a pixel and transitioned over to GOS, I really miss the old LED notification dot.

Although I found a great app on f-droid called "Holey Light" which recreates the led with a circle (or halo) around the camera (which works on Pixel) or on the main screen (which doesn't work on Pixel) with custom colours for each app & notification type, unfortunately the app does not appear to be maintained.

What are your thoughts on integrating something like this into GOS as a toggle option in the notification settings?

**Comment by thestinger** [comment]
We agree this was a useful feature when the screen is off but we don't plan to add a replacement for it. There's already the option to use always-on display which can display icons showing you have notifications on the lockscreen. The amount of power saved by showing only a dot on the display would likely not be very significant since the extra power usage comes from keeping the display powered at all. It's reasonably efficient and you can try it out and see if you even notice a significant loss of battery life for your usage.
