### ISSUE TITLE
Fine-grained per-app network permissions 

### ISSUE THREAD

**Issue by ThatOneCalculator** [GrapheneOS/os-issue-tracker#3119]
- Being able to restrict an app to only do downloads, not uploads (& vice versa) 
- Restricting apps to only communicate with certain domains
- Activating a VPN automatically while launching an app

Would all be really useful, especially for privacy-invasive apps that people are sometimes forced to use.

**Comment by thestinger** [comment]
> Being able to restrict an app to only do downloads, not uploads (& vice versa)

That's not possible.

> Restricting apps to only communicate with certain domains

You can use a VPN service app which supports both filtering and using a real VPN such as RethinkDNS. However, you should be aware this will only filter direct access by the app and is leaky when it comes to indirect access unless you block all traffic from components/apps providing indirect access such as DownloadManager and others.

> Activating a VPN automatically while launching an app

This would be leaky since apps can make indirect connections too. VPNs are per-profile and that's how you should use a specific VPN for specific apps.

**Comment by thestinger** [comment]
Even DNS queries to the DNS resolver can be used as a 2 way communication mechanism with any party, which is commonly used as a way to hide the traffic for malware since the only connections will be to your DNS resolver (such as the ISP DNS servers, Cloudflare or Google Public DNS, etc.) with information sent via the name being queried and received via the result of the query (such as arbitrary data encoded into a TXT record, but it can also be done without TXT records so filtering them is pointless).
