### ISSUE TITLE
Weird Wi-Fi bug

### ISSUE THREAD

**Issue by DavidRLTG** [GrapheneOS/os-issue-tracker#3127]
Salutations!
Basically, I have 3 phones.
A Samsung Galaxy S8,
A Poco F3,
A Google Pixel 8.
All of them are connected to Wi-Fi, and have Cloudflare Warp always on.
Except the Pixel 8 with GrapheneOS, will VERY OFTEN either remain connected with no network and sometimes get fixed by turning wifi on and off
or it will just disconnect and i gotta reconnect manually, and sometimes it fails and I gotta try later.
Mobile data works perfectly fine.
Any ideas? Thank you!

**Comment by LunchBoxC** [comment]
I'm noticing strange behavior on my Pixel 7a with WiFi ... Especially since:  2024011600

Today I left the house and it remained connected to my home WiFi despite not being in the neighbourhood and told me that it had problems contacting GrapheneOS servers and also DNS connectivity.

I had to cycle the WiFi off manually and then it reverted to the Mobile data and all my notifications started coming in.  

I thought it was weird so I decided to restart my phone (I restart daily at night so it wasn't running that long).

When I got home about 6 hours later it reconnected to my home WiFi and gave me the messages again that it couldn't contact the GrapheneOS servers and DNS servers.

I cycled the WiFi off waited a few seconds and then cycled it back on and it worked fine.

As a comparison my spouse as a Samsung Galaxy S23 and it connected no problem when we got home.

I just restarted my Access Point and the phone remained connected despite my tablet disconnecting during the reboot process and again I got the message on my phone that it lost connectivity with the Graphene OS Servers and DNS and it didn't automatically flip over to Mobile Data despite having full bars where I am.

I didn't notice this issue until today and so that is why I listed the build number above in-case it's something in that release that is adding to the issue.

**Comment by thestinger** [comment]
@LunchBoxC Does not seem related.

**Comment by LunchBoxC** [comment]
> @LunchBoxC Does not seem related.

Ok

**Comment by DavidRLTG** [comment]
> @DavidRLTG You need to try with a different VPN or without the VPN to determine if it's an app bug. If it's an app bug, you can try exploit protection compatibility mode with that app. You need to provide more details and reasoning for believing it's an OS issue.

So, small update: I tried the suggestion (enabling exploit protection compatibility mode) and the bug remains. Now, I'll try not using the VPN.
