### ISSUE TITLE
Add battery care functionality

### ISSUE THREAD

**Issue by boniek83** [GrapheneOS/os-issue-tracker#379]
It would be nice to have a feature that many laptops have, that stops charging battery at specified "high" threshold (eg 80%) and starts only when another "low" threshold is hit (eg 20% or eg any percentage at or above high threshold which will always charge battery). "High" threshold should reset full charge in Settings/Battery/Battery Usage, "low" threshold should, optionally, notify user to connect charger (battery low event). This is needed for creating charging plan that minimizes battery wear.

**Comment by thestinger** [comment]
The hardware already throttles charging based on how charged the device is so that by the time it's approaching full capacity, it's barely charging it anymore.

This is out-of-scope for GrapheneOS. Our goal is to match the functionality provided by the stock OS. Beyond that is not within the scope of enhancing privacy and security.

**Comment by kbftech** [comment]
Hi, regarding the previous exchange, I wonder if that functionality matched in grapheos?

https://support.google.com/pixelphone/answer/10011133?hl=en#zippy=%2Coptimizing-for-battery-health-pixel-later%2Ccharging-temporarily-limited-pixel-later

**Comment by flawedworld** [comment]
The firmware deals with trickle charging between 80-100%
