### ISSUE TITLE
replace wallpapers

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#39]

**Comment by Peter-Easton** [comment]
I tried a simple test render of the logo in 3D on a carbon fiber textured background and liked the way this turned out, although I'm trying to learn Blender at the same time so improving it will be a bit slow. What would you say to something like this...? 

https://jollyroger.site/unlisted/grapheneos-wip-red-blue.png

How it looks on my phone:
https://jollyroger.site/unlisted/phone-screenshot-2.png

**Comment by renlord** [comment]
please submit a PR here: https://github.com/GrapheneOS/branding

**Comment by thestinger** [comment]
The default wallpapers are replaced so https://github.com/GrapheneOS/os-issue-tracker/issues/556 can replace this issue.

**Comment by thestinger** [comment]
I think I like having a black one as the default but we could bundle a couple more fitting the general theme.
