### ISSUE TITLE
Implement support for Pixel Active Edge functionality

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#457]
See: https://github.com/ProtonAOSP/android_packages_apps_ElmyraService

**Comment by flawedworld** [comment]
@thestinger Active Edge is not present on Pixel 5, 4a, and 4a 5G

**Comment by thestinger** [comment]
Ah, then we should just cancel implementing it if it's not going to be a thing anymore.

**Comment by MrAce100** [comment]
Please correct me if I am wrong, but the component initially mentioned seems quite easy to implement into the project; I am sure many of the users of the devices with Active Edge capability would be happy to be able to use one of their phone's built in hardware features. Surely the removal of a hardware feature on newer models is not reason enough to deprive users of older models, especially if the componant to enable support is easy to implement? Could this issue be reopened and considered for implementation please?

**Comment by thestinger** [comment]
It's an obsolete feature which has been removed on newer devices. It doesn't make sense to add it for older devices at this point. It doesn't exist on 5th and 6th generation devices. It only existed from the 2nd through 4th generation. 2nd generation devices are dropped. 3rd generation devices are end-of-life this year (Pixel 3 and 3 XL are already end-of-life). 4th generation devices are end-of-life next year. I don't see a reason to add this for them at this point. It would have made sense to add it when latest generation devices had it, but it didn't happen. It might have made sense to add it even after the release of the 5th generation with the assumption it would come back later. It didn't. It's obsolete.

**Comment by thestinger** [comment]
Anyone on a 3rd generation Pixel needs to move on to a 6th generation Pixel. People on 4th generation devices will need to move on to a 7th generation Pixel or perhaps a phone built to run GrapheneOS if that works out and launches in late 2022.

**Comment by thestinger** [comment]
It's not present on the Pixel 4a which is BY FAR the most used 4th generation device. Pixel 4 and Pixel 4 XL were very expensive without all that much to show for it: $799 and $899 for the 64GB models, $899 and $999 for the 128GB models. Compare that to the Pixel 6 / Pixel 6 Pro at $599 / $899 which are both significantly nicer hardware than the Pixel 4 and Pixel 4 XL were at the time. Pixel 4 and 4 XL are our least used devices, and soon enough they'll be on the way out and this won't be relevant anymore. I'd much rather just wait a year for it to not be relevant than adding complexity to support a legacy feature. It's such an awkward feature anyway. They removed it for a reason. It was not widely used or well received.

**Comment by MrAce100** [comment]
> It's an obsolete feature which has been removed on newer devices. It doesn't make sense to add it for older devices at this point. It doesn't exist on 5th and 6th generation devices.

You and I appear to have differing ideas on how hardware features ought to be implemented. I am of the opinion that users of specific devices ought to be able to use every hardware feature their device supports on an operating system that does not compromise their security, barring features that compromise security by their design, of course. If I were a developer on a major AOSP project such as GrapheneOS, I would feel obligated to ensure the hardware features of each device were compatable with my project, especially if my project supported as few phones as GrapheneOS supports. In my opinion, although new Pixels do not have Active Edge capability, the phones that do are considered to be currently supported by the project and releases of the project for each device ought to be feature complete. However, my opinions carry no weight as I am not in control over this project nor do I have any experience in projects such as these. I can only entreat you to consider my own opinions.
> Anyone on a 3rd generation Pixel needs to move on to a 6th generation Pixel. People on 4th generation devices will need to move on to a 7th generation Pixel or perhaps a phone built to run GrapheneOS if that works out and launches in late 2022.

Not everyone has the ability or the will to upgrade their phone once it becomes obsolete. Many do not feel comfortable with spending $500 or more every three years on a new phone, and would rather save their money for other purposes. Certainty, these people assume all risk of using obsolete technology upon themselves by doing so; I do not argue for indefinite support of obsolete technology, although I do personally wish that technology was supported longer than is the norm today.
> I'd much rather just wait a year for it to not be relevant than adding complexity to support a legacy feature. 

Makes sense; I am willing to accept my knowledge in this area is insufficient to understand the complexity this new component may add to your project. I might disagree if I did possess such knowledge, but unfortunately I am ignorant.
> It's such an awkward feature anyway. They removed it for a reason. It was not widely used or well received.

Perhaps this feature was not well received because of it's limited nature. The original capability only allowed users to either activate Google Assistant or silence alarms and such. The extended capability of the module initially proposed by flawedworld is where the practical use of this feature lies. The ability to turn on the device's flashlight with a simple squeeze is quite enticing to me in particular.
I repeat my initial request: That you reopen this issue for inclusion into your project. Although the last devices that support Active Edge will stop receiving updates in October, I assume you will offer extended support like you are providing for the Pixel 3 and 3 XL for a while afterwards, please do correct me if I am mistaken.

**Comment by Zanthed** [comment]
It's not going to be implemented. The devices that do support it are EOL (Pixel 3, 3 XL) or are approaching EOL (3a, 3a XL, 4, 4 XL). 

It isn't present on newer Pixels and it's not an open source component that can be easily implemented/enabled. kdrag0n has an open source implementation, but that just adds more feature maintenance and reliance on out-of-band/non-AOSP components which does not make sense for something that clearly has been removed.

If Google brings it back then we can implement it, but for now it's seen as a legacy feature that has been removed and we're not going to bring it back and maintain a legacy feature. Same way we're not going to maintain 2/3-button navigation or solve issues/improve it because it's legacy, deprecated, and replaced with gesture navigation.

**Comment by Zanthed** [comment]
Our extended support releases are not meant to be relied on or provide any more assurance in your EOL devices. They are only a security stopgap for people who need a little more time to get newer supported devices. They do not have the same security as the newer devices and it is not something you should be relying on.

**Comment by MrAce100** [comment]
As much as I disagree with it, I understand your position. Your goal is to make the best privacy focused Android option (which is an excellent endevor I greatly appreciate), not to make a customizable user experience utilizing the full extent of the hardware. If I find the lack of customizability unsatisfactory, I shall look elsewhere rather than shout at you all to change for me. :)

**Comment by thestinger** [comment]
We have so much work to do on very important things and this just doesn't make sense for us. We need to work on our app repository, eSIM activation support, memory tagging for hardened_malloc and tons of other things. Carrier support always needs improving, a bunch of AOSP apps like Messaging and Contacts need updates, endless privacy and security stuff needs to be done. This super niche feature they abandoned for the 4a and beyond (i.e. generation 4.5 Pixels and beyond) just isn't going to happen at this point. It might have happened if we were aware of kdrag0n's work on it much earlier, but we weren't. It's too late now.

**Comment by thestinger** [comment]
Pixel 4 and Pixel 4 XL are now end-of-life and in extended support from GrapheneOS, so this issue has resolved itself with time. This wouldn't have been a good use of our resources due to the feature never reappearing on any newer devices.
