### ISSUE TITLE
Auto disable cellular radio when connected to wifi

### ISSUE THREAD

**Issue by SimonMGS** [GrapheneOS/os-issue-tracker#539]
Feature request to add an option to disable the cellular radio when connected to a wifi network. Currently I do this by remembering to manually go into airplane mode, and then re-enable wifi, whenever the cellular radio is unneeded. 

I think this would be an improvement for privacy, reducing the amount of time the cellular radio is providing a location, if we forget to manage it manually.

For convenience, perhaps separate option to auto re-enable the radio when the wifi is out of range.

EDIT: Just to clarify, this is for those of us who heed the advice in the FAQ, and communicate only over data connections on secure apps - our cellular connection is purely for data.

**Comment by 1989gironimo** [comment]
Is Tasker an option for you? 
Easer (an opensource alternative) only allows to disable mobile data, but not the cellular as a whole.

**Comment by IT-Exilion** [comment]
Tasker and easer need to have geolocation enabled to register wifi list, so you must have one radio alltime enabled to disable another from time to time.

**Comment by Peter4487** [comment]
It would be important to have as a sub-feature here some sort of check on whether the wifi connection you have is actually allowing you to connect to the internet.

If I understand correctly, the goal is to not leak location data + not have traffic associated with a mobile phone account whenever possible. However, merely being connected to a wifi network doesn't do the trick for most use cases because that wifi network needs to be a usable path to the internet too.

**Comment by lbdroid** [comment]
In "Developer options", there is a flag "Mobile data always active" (default on). This sounds like a related but mutually exclusive kind of feature. I'd probably aim to put it in there with a similar kind of description for advanced users, since there will be some side-effects to it, such as the absolute inability to seamlessly hand off a vowifi call to a mobile network.

**Comment by flawedworld** [comment]
It's not relevant to this

**Comment by lbdroid** [comment]
Its relevant as a contra-feature that has to be also handled, and as an example for implementation pattern.

**Comment by Zanthed** [comment]
We're not going to handle cases of users going to developer options and messing with things. It's not a user-facing area and will break stuff.

**Comment by lbdroid** [comment]
In that case, don't implement this. It will break things to the extent it should be restricted to people who know what they're doing.

**Comment by Zanthed** [comment]
We're not a power OS. If you decide to go into non-user areas and break stuff, we can't and will not account for that and we can't help you easily.

Please stop derailing issues.

**Comment by thestinger** [comment]
It's not known if this feature is wanted but developer options aren't going to factor into it. Please don't get into an argument about that, it's off-topic.

**Comment by Peter4487** [comment]
An additional sub-feature that is more just "nice to have" would be geo-fencing areas in which wifi should be on. This allows us to only have the correct radio on for a given situation.

I would guess that the information leaked from having wifi on all the time is not of great concern (unless you have programmed in hidden SSIDs?). However, there may be situations where you don't want it automatically trying to connect to wifi networks with common SSIDs (e.g., certain ISPs try to blanket an area with wifi (comcast), a work network, a campus-wide network...).

Imagine starting in "travel" mode, where you are using a cellular connection for data but wifi is off.

1. You arrive home.
2. Based on GPS data the phone deduces you are home (perhaps "home" is a 200m diameter circle around the coordinates when you indicated home is)
3. The phone activates the wifi radio
4. The wifi radio successfully connects to your home wifi network
5. Phone does an internet connection check via wifi
6. The check comes back True (you are in fact connected to the internet via wifi)
7. The phone disables the cellular modem (equivalent to airplane mode + turning wifi back on?)
8. The phone continues to check for internet connectivity at a random interval between 10 and 30 seconds, using a randomly selected IP (selected from a list). Or maybe the better plan is to use the default server every android phone uses, if there is such a thing.

Later you decide to go out for pizza.

1. Walk out of your house in the direction of the pizza place
2. Phone either detects loss of internet connection from internet connectivity check OR loses wifi connection
3. Phone automatically powers up cellular modem and establishes internet connection.


This is much more of a nice-to-have because the situation where you want to have wifi power on and auto-connect to certain networks but not all is probably less useful than the simple case where:

IF internet connection thru wifi
THEN kill cell modem

IF no internet connection thru wifi
THEN power up cell modem

However, this simpler case entails having the wifi on all the time.

**Comment by thestinger** [comment]
We don't do anything of the kind.

**Comment by e-t-l** [comment]
Correct me if I'm wrong (and I would be _very_ happy to be wrong, because I've been fairly frustrated with the number of harmless disability-friendly/accessibility apps that aren't working on Graphene, e.g. my example with Extra Dim above), but isn't the reason that apps like Shizuku don't work that ["GrapheneOS disallows shell (adb) to execute codes from apk"](https://github.com/RikkaApps/Shizuku/issues/226#issuecomment-1170894458)? That dev cites [this GrapheneOS commit](https://github.com/GrapheneOS/platform_system_sepolicy/commit/fe67984a4070a6f840487e0e496a164e4e58b261) as responsible for the aforementioned kneecapping, although personally I'm not code-savvy enough to grok it. 

Again, I'd love to be wrong, but since switching to Graphene I've had a number of profiles, which control simple things like toggling the Extra Dim state, completely stop working, even after I've manually granted `write_settings`, `write_secure_settings`, etc. via ADB...

**Comment by thestinger** [comment]
Unless these apps depend on the incredibly problematic approach of enabling network ADB and accessing the adb shell through it, nothing we change is relevant. This also has nothing to do with this issue and is inappropriate for this discussion.

**Comment by e-t-l** [comment]
> enabling network ADB and accessing the adb shell

So, in your own words, yes this is a relevant discussion. You say incredibly problematic, others can say incredibly useful. Security and usability is and always has been a spectrum. Regardless of individuals' personal feelings on the subject, Tasker was proposed as a solution, so I was confirming whether Tasker is working on GrapheneOS. If you have any relevant insight in this matter please do share it.

**Comment by r3g-5z** [comment]
This is a security and privacy focused OS. Not a random OS off of XDA that has zero thought for security.

Furthermore, this is not at all relevant to the main issue.

**Comment by r3g-5z** [comment]
Please keep discussions on topic. You can discuss this manner at https://discuss.grapheneos.org/
Not here.

**Comment by robcle** [comment]
Is the team thinking about working on this? This seems like a good battery saving feature anyway. With WiFi calling I wouldnt think cellular would be needed when on WiFi
