### ISSUE TITLE
Device requests previous v4 network address

### ISSUE THREAD

**Issue by jpds** [GrapheneOS/os-issue-tracker#551]
I noticed that my device appears to request the previous IPv4 network address it had on a WiFi network on the new MAC address it has.

If I delete the network, and reconnect, it just does a `DHCPDISCOVER`.

**Comment by flawedworld** [comment]
Hi @jpds , I have not been able to replicate this on the Pixel 5 running RQ2A.210505.003.2021.05.04.01. Could you please provide more information.

**Comment by thestinger** [comment]
It won't successfully get the previous address but the report from @jpds is that it will attempt to do it and then be rejected since that was handed out to the previous MAC address. I don't really think this is stored persistently but we may need to restart the DHCP process or configure it differently.

**Comment by thestinger** [comment]
This is fixed by https://github.com/GrapheneOS/platform_packages_modules_NetworkStack/commit/69ebf7cf7541bd3604a2b2d1c18a2df081e96e3f.
