### ISSUE TITLE
Option To Hide Persistent Notifications.

### ISSUE THREAD

**Issue by Penguin-Guru** [GrapheneOS/os-issue-tracker#552]
My vague understanding is that some apps install persistent notifications to ensure they can operate as desired in the background. I assume this is a facet of system optimisation. Personally, I would like the option of hiding those on a per app basis without worrying about the apps being suppressed in any functional way. Is this currently possible somehow? If not, would it be a reasonable feature to request? I have several of them and really dislike how they clutter up my notification area when I pull it open. The minimised icons don't bother me as much and might be sensible to keep for some apps to show status.

**Comment by thestinger** [comment]
It would reduce protection against stalkerware-type software since foreground vs. background has security implications. I don't really think we want to implement this. We'll go along with the way it works in AOSP. Apps can set these notifications to the lowest possible priority so that they get collapsed.
