### ISSUE TITLE
Occasional crash when disconnecting bluetooth headphones

### ISSUE THREAD

**Issue by tguen** [GrapheneOS/os-issue-tracker#558]
I use bluetooth headphones every day. About 1/30 times, when I turn my headphones off, my Pixel 4a will freeze for ~5 seconds, then reboot. It doesn't seem to matter if I am playing anything when I turn them off.

**Comment by thestinger** [comment]
Sounds like a memory corruption bug being detected. It would be helpful if you could use the bug report capture tool at the top of developer options (you can turn developer options back off afterwards) and send the zip to contact@grapheneos.org. It may contain sensitive logs even though apps aren't supposed to log sensitive data to system logs, so you can optionally look through the zip and censor it if you want, but it's a fair bit of work since it contains a lot of data.

**Comment by tguen** [comment]
It just happened again. After reboot, I clicked "bug report" and it asked for interactive or full report. I tried each several times and nothing happened. I tried again about 10 minutes later and suddenly it worked. I sent it, hope it helps.

**Comment by thestinger** [comment]
This should be resolved now. Does it still happen for you?
