### ISSUE TITLE
Camera app / service crashes due to upstream memory corruption bugs uncovered by hardened_malloc

### ISSUE THREAD

**Issue by packetup** [GrapheneOS/os-issue-tracker#56]
The camera app crashes whenever you switch the front or back cameras. This occurs on Blueline.

**Comment by thestinger** [comment]
There are various upstream memory corruption bugs in the userspace camera driver code. The hardened malloc implementation ends up uncovering these. I've reported some of these issues but it generally takes a long time for them to be fixed, and I lack the time to do it myself. It would make sense to deploy some more workarounds for this code in the meantime.

**Comment by thestinger** [comment]
Can you try again in the latest release? The mitigations enabled in the camera service are a bit less aggressive now.

**Comment by jengo9332** [comment]
@thestinger The problem still exists:

1) Start camera app
2) Switch from i.e. back camera to front camera
3) Camera app crashes
4) When you start the camera app the front camera will be active

Same goes if you switch from front to back camera.

**Comment by thestinger** [comment]
I can replicate it on blueline. I could try disabling more mitigations for it but I don't have time to work on this right now. The project desperately needs contributors to help identify and narrow down these issues, along with fixing as many as possible rather than just working around them like this.

**Comment by thestinger** [comment]
This isn't nearly as bad as it used to be. There are still some issues uncovered.

**Comment by thestinger** [comment]
Closing until we manage to replicate the new crashes with logs, since it's much less common.

**Comment by thestinger** [comment]
This is now much less common but I'm going to leave this issue open for tracking the removal of the workarounds.

**Comment by lbrunkho** [comment]
I dont know if this is related to this issue but im having a massive amount of camera failures on my pixel 4a. Both OpenCamera and Signal's cant use the camera the majority of the time due to it being "unavailable" or "serious camera error" this happens 50% of the time when I use open camera and nearly 80% of the time on signal. Strangely i just upgraded from a pixel 3 that did also have this issue but not to this extent. Let me know if i should open a new issue for this.

**Comment by thestinger** [comment]
No, don't open a new issue for it. We're aware of multiple upstream camera bugs uncovered by our hardening.

**Comment by lbrunkho** [comment]
Ok, I suspected these two issues where the same. So I'm glad I asked. Just for the sake of usability are there anymore workarounds that I can use that aren't already implemented in the stable release of the OS? I understand upstream ASOP issues can take a long time to work their way down.

**Comment by jorgeluiscarrillo** [comment]
I think we can close this issue now with the release of our new Camera app.

**Comment by thestinger** [comment]
The service is part of the OS implementation rather than the Camera app. It can probably be closed based on the Pixel 3 and 3 XL being end-of-life and only supported via extended support releases since we could move the workaround to the branch they use. Currently still have the workaround in the main branch though so this should remain open until it's removed.

**Comment by thestinger** [comment]
We're no longer going to be working on these issues for 3rd generation devices. The workaround is fine for their remaining lifespan.
