### ISSUE TITLE
Open-Vpn Crashes

### ISSUE THREAD

**Issue by SpiderPants** [GrapheneOS/os-issue-tracker#562]
Once the VPN config file has been added, Open-VPN doesn't load and freezes on the apps bootup screen.  The config file isn't at fault, as they work on android and ubuntu.  Pixel 4a (5G)

**Comment by thestinger** [comment]
You aren't clear on which app you're using. There are multiple apps providing OpenVPN support. It's likely that this is a bug in the app, not GrapheneOS. There needs to be a strong reason to think that it's a bug in GrapheneOS for it to be filed here. There's not enough information to work with here.

**Comment by thestinger** [comment]
Please start in the Matrix chat channels to narrow down what the problem might be. It's very unlikely to be a GrapheneOS bug and it may not even be an app compatibility issue. The app could simply have a bug, or it could have a bug that's uncovered by memory corruption mitigations. It may simply have a feature depending on Play services and can't handle it not being present. Getting logcat logs would help with that. You can either get that via ADB or the bug report capture tool, but it would help a lot if you could get the relevant logs from the zip if you do it that way. We need something to work with and also a reason to think it's something we can address rather than an app issue.
