### ISSUE TITLE
Photos missing after last Update on Pixel 4a 5G

### ISSUE THREAD

**Issue by orcv** [GrapheneOS/os-issue-tracker#564]
After yesterday's Update, many of my photos are missing from my phone.
I have manually checked with a different Gallery, File Manager and by connecting it to my PC.
Weird to me, some pictures are still there, though the majority is gone.

**Comment by thestinger** [comment]
An update wouldn't have done that and there were no relevant changes. You're associating something with the update that's not related to it.

**Comment by orcv** [comment]
I looked at the pictures, updated my phone, wanted to send one of them and noticed they were gone. Absolutely nothing in terms of user interaction happened inbetween that.

**Comment by thestinger** [comment]
It's not related to the OS update. There's something wrong with that story. There's no real reason to connect it to the update.

You should go through the apps you gave write access to your photos including via the legacy storage permissions. It's likely one of the apps deleted them, likely by accident, either due to a bug or something you had them do. Possible that rebooting triggered an app to do something but it's unlikely. It's definitely nothing to do with the update.

Nothing we can do with an issue that says something has to do with an update that we know doesn't.

**Comment by thestinger** [comment]
Just because something happened in between you checking it and then checking again after updating does not mean it had anything to do with the update. A full list of changes in the update is at https://grapheneos.org/releases#2021.05.29.09 and the update system doesn't do anything like that with user data. It wasn't caused by the update. You should get support on the official chat rooms because it's support issue rather than an OS issue.
