### ISSUE TITLE
Feature request: Allow the user to save a value in the secure storage that the stock OS uses to bind a device to a Gmail account

### ISSUE THREAD

**Issue by stevie553** [GrapheneOS/os-issue-tracker#577]
In stock OS, you could bind the device to a GMail account.

Now if we expose that secure place to users, they could bind the device to their own string, without the need to rely on Graphene for any sort of servers like Google, it's all locally done. So the next time the OS is factory reset, they must enter that same string.

Of course the user must use a secure value, or maybe Graphene could generate a value for the user to store somewhere safe?

I hope I make any sense.

**Comment by thestinger** [comment]
This will result in users bricking their device when they lose the seed.

**Comment by thestinger** [comment]
It has no security value and is purely an anti-theft feature. Anti-theft acts as deterrence since thieves are aware that any decent phone they still with a 6 digit PIN or better is basically scrap metal to them. It doesn't make much difference for GrapheneOS in that regard. Many users will brick their devices based on our experience with people forgetting their password, etc. and yet it won't really stop any devices being stolen. I don't think we want to implement this. See https://grapheneos.org/faq#anti-theft.

**Comment by stevie553** [comment]
@thestinger understood, thank you for the quick response.
