### ISSUE TITLE
Launcher back button missing on new update

### ISSUE THREAD

**Issue by dspacejs** [GrapheneOS/os-issue-tracker#580]
Previously there was a back button in the launcher, at the bottom of the screen. Since a recent update, it's now been removed and I can't go backwards in apps. This is a huge pain. 

![signal-2021-06-18-115208](https://user-images.githubusercontent.com/9282837/122496904-ad9f4700-d02b-11eb-98cd-b0a9e3df4548.png)

## Environment

* Pixel 2 XL
* Android 11

**Comment by thestinger** [comment]
GrapheneOS uses gesture mode by default now like the stock OS on recent devices. See https://grapheneos.org/usage#system-navigation for a guide.

Going back is done with a gesture by swiping from the left or right edge of the screen above the navigation bar towards the center of the screen.

**Comment by thestinger** [comment]
We didn't want to have older devices using a different navigation system by default, so we changed the default for GrapheneOS as a whole rather than specific devices. Users who had set a specific preference did not have their choice overridden. We only changed the default for users who haven't set a specific navigation mode. Most people prefer gesture mode after trying it. Read the instructions on it and try it. If you don't like it, you can go back to 2-button or 3-button navigation.
