### ISSUE TITLE
GrapheneOS was not in control of ePDG IPSec WiFi calling domain resolution

### ISSUE THREAD

**Issue by EntropySmoke** [GrapheneOS/os-issue-tracker#612]
Primary Issue

- Case 1
Device: Pixel 4a (3 units)
OS: Stock Google Android 11 Sunfish factory images
Carrier: Google Fi (which locally used T-Mobile towers)
WiFi Calling options: Disabled (in Network Mobile options and Google Fi app)
Result: personal local network Pi-Hole DNS server showed that all 3 phones attempted to resolve epdg.epc.mncXXX.mccXXX.pub.3gppnetwork.org domain (where XXX was a number that gave away my carrier's MNC and MCC) exactly every 15 minutes

- Case 2
Device: Pixel 4a (3x)
OS: Stock GrapheneOS 7/26/2021 images
Carrier: T-Mobile (SIM card inserted after GrapheneOS was flashed onto devices)
WiFi Calling options: Disabled (in Network Mobile options and GrapheneOS stock dialer app, no T-Mobile apps were ever installed)
Result: personal local network Pi-Hole DNS server showed that all 3 phones attempted to resolve epdg.epc.mncXXX.mccXXX.pub.3gppnetwork.org domain (where XXX was a number that gave away my carrier's MNC and MCC) exactly every 15 minutes

In each case, either OpenVPN or WireGuard VPN tunnels were used for WiFi and mobile data LTE connections, but carrier-based ePDG WiFi calling always used its own IPSec tunnels. That was how ePDG WiFi calling was designed. The problem was that neither Google stock OS nor GrapheneOS could control resolution of ePDG domains over WiFi. On a personal network with Pi-Hole blocking those domains, it was not a problem, but on other WiFi networks, it left a fingerprint of my carrier's MNC and MCC numbers... It was not known to me whether successful resolution of those domains resulted (or would have resulted) in devices actually using IPSec WiFi calling, but sending out packets to resolve such domains was already an information leak.

Was it not within the scope of the OS to fully enable/disable attempts to resolve ePDG IPSec WiFi calling domains?

**Comment by thestinger** [comment]
We're well aware of how Wi-Fi calling/texting features work. GrapheneOS is fully in control of it.

I don't know what you mean by your question asking if it wasn't within the scope of the OS. You seem to be mistaking the current set of features as a complete implementation of what we want to provide.

There are toggles for this available but what's available varies based on the carrier. There are also the debugging controls and the ability to disable app-based components. A higher-level, universal toggle for Wi-Fi based carrier features is welcome as a feature.

I'm going to close this because we aren't going to be changing how this technology fundamentally works. At most we can offer a high-level, universal toggle rather than the current per-carrier configuration and lower-level ways of turning it off.

**Comment by thestinger** [comment]
See https://github.com/GrapheneOS/os-issue-tracker/issues/614 which we do plan to implement. There is no timeline for it. You're welcome to work on implementing it. It likely won't be implemented for in the near future by us. We have to do the migration to Android 12 among many other things that are far higher priority than this.
