### ISSUE TITLE
GrapheneOS NTP Server Synchronization not working

### ISSUE THREAD

**Issue by EntropySmoke** [GrapheneOS/os-issue-tracker#613]
Device: Pixel 4a (3 units)
OS: GrapheneOS 07/26/2021 images
Issue: GrapheneOS NTP time.grapheneos.org server could not be used to synchronize time for any of the phone units, PC's, router's and other devices, even though domain resolution of time.grapheneos.org was always successful.  Stock GrapheneOS result for ADB command "settings get global ntp_server" was "null" and "settings put global ntp_server time.grapheneos.org" command did not resolve the issue. Local DNS server showed that stock GrapheneOS attempted to synchronize time via time.google.com.

**Comment by thestinger** [comment]
time.grapheneos.org isn't an NTP server. Please read https://grapheneos.org/faq#default-connections. GrapheneOS uses this by default and doesn't use either NTP or the carrier as a source of time. Since you've changed settings via ADB, you've changed the behavior from the default. It doesn't appear that there's any problem here. You messed with low-level settings and therefore it makes a connection that it wouldn't usually make. Unless you can replicate any issues after a factory reset, it doesn't appear that there's any issue.

**Comment by thestinger** [comment]
It sounds like you changed the `ntp_mode` setting. GrapheneOS normally doesn't use either the carrier or NTP as time sources. I suggest doing a factory reset and looking at what it does by default.
