### ISSUE TITLE
Firewall profiles / batch editing

### ISSUE THREAD

**Issue by tzugen** [GrapheneOS/os-issue-tracker#615]
In AfWall it is possible to configure different profiles, such as "Home" or "Work", in which certain Apps should be blocked from the internet or not.

Is something like this possible with grapheneos?
Would it be implementable if not?

Or a different way to batch set permissions?

**Comment by thestinger** [comment]
> In AfWall it is possible to configure different profiles, such as "Home" or "Work", in which certain Apps should be blocked from the internet or not.

That app doesn't work because it only filters direct network access via sockets rather than indirect via APIs.

**Comment by thestinger** [comment]
> In AfWall it is possible to configure different profiles, such as "Home" or "Work", in which certain Apps should be blocked from the internet or not.

Those kinds of firewall apps don't really work because they only filter direct network access via sockets rather than also indirect via APIs.

You should really treat every network as equally entirely untrusted. Your own local network is not actually a boundary where stuff inside it is safe. It should be treated just like a Wi-Fi hotspot, and that's what the OS already does. We don't want to add features trusting networks and would recommend against apps doing it. It's a legacy and very problematic approach to security. Authenticated encryption should always be used including for doing things like managing IoT devices rather than them trusting the local network.

**Comment by thestinger** [comment]
You're free to use an app like NetGuard and ask them to provide features you consider missing. Our view is that the approach those are taken is inherently broken due to how it can be bypassed using indirect access via APIs. The fine-grained filtering can also be entirely bypassed through using DNS, which provides a 2-way communication system with arbitrary servers via your DNS provider. You don't make direct connections to arbitrary servers via DNS but regardless it provides arbitrary data transfer to and from them via the provider. Any app that's able to make a DNS query can send data to any party and receive data from any party.

Looking up data_to_exfiltrate.random_token.domain.com will send data_to_exfiltrate to the nameserver chosen by domain.com via your DNS provider without needing to talk to it directly. This technique is *heavily* used not only by malware but also more borderline cases simply trying to mask the data transfer for one reason or another such as bypassing filtering. This can be used on behalf of the user to bypass filtering, but it's generally used against their interests and without their knowledge.

**Comment by tzugen** [comment]
OK, maybe I should be more clear :)

I mostly use those Profiles to restrict access when my data plan is nearly finished.

**Comment by tzugen** [comment]
But thanks a lot for your explanation. That make it much more clear!

**Comment by thestinger** [comment]
Use Settings -> Network & internet -> Data Saver. You can make a list of apps with exceptions and then toggle it on when you need to start conserving data. It won't outright forbid apps from having network access but will take it away when they aren't in the foreground.

**Comment by tzugen** [comment]
Thanks :)
Then it sound like I can do everything I need with Graphene 😊

One last question if I may:
Can I set the Firewall to Whitelist mode? So blocking Internet access by default for new apps, until I have allowed it?

**Comment by thestinger** [comment]
There isn't currently a way to disable our added Sensors and/or Network toggles by default to make them work like standard runtime permissions. It would be possible to add it but it can't be the default for usability reasons due to apps not knowing how to check if they have them and request them when needed. I think we have an issue open about this.

**Comment by thestinger** [comment]
> I think we have an issue open about this.

Might not but it is on our radar as a future possibility even if it's not really decided if we want to do it that way.
