### ISSUE TITLE
Feature Request | Add NLP location providers for faster location discovery

### ISSUE THREAD

**Issue by eggplanting** [GrapheneOS/os-issue-tracker#632]
Currently only GPS is supported for apps requesting location permissions, this results in a long waiting time when navigation apps are started for example.

Would it be possible to support the installation of NLP location providers in future? Multiple providers (like MozillaNLP) could be bundled with GrapheneOS and being selected at the first setup screen, with the possibility to enable and disable them in the location settings menu later. This would make them an optional feature.

MicroG is using an API compatible with NLP providers installed via F-Droid. Would be nice to see a similar implementation for GrapheneOS.

**Comment by eggplanting** [comment]
Didn't see there is already an open issue for my requested feature:
https://github.com/GrapheneOS/os-issue-tracker/issues/24

A seperate app for this feature, allowing to choose a NLP provider or disabling them completely, sounds like the best solution to me. Maybe MozillaNLP is the best one for this.

Closing here, sorry for the inconvenience.

**Comment by thestinger** [comment]
GNSS + A-GPS works fine without Play services. 

GrapheneOS doesn't bundle or integrate proprietary services with special privileges so the Apple, Google and Mozilla location services are off the table for inclusion in the OS. We also don't believe in sending off real time location data to a service. It should be based around a local database. Mozilla chooses not to make most of the data used by their proprietary service available for download.

It also needs to be first party builds of the location services properly enforcing the security model for this rather than allowing trivially faking the location without using the mock location feature.

**Comment by thestinger** [comment]
microG is not going to be considered as a provider for location services. It doesn't make sense for this to be tied to a reimplementation of Play services. Our approach to handling apps using Play services is the sandboxed Play services compatibility layer. There will be no special privileges granted to it or a reimplementation of it and the OS won't use it for anything. Apps using the OS location API won't be impacted by Play services being installed. That's the intended design to avoid downgrading privacy and security and we aren't making deviations from it.

**Comment by pshirshov** [comment]
> It should be based around a local database.

Well, there is DejaVu, fully local service which is used by Calyx.

**Comment by thestinger** [comment]
DejaVu isn't what I mean by using a local database. I don't mean the user having to gather it and then it uses that to detect places they've been. That implementation of this is also insecure and violates the security model for location providers so it won't be used.

In the future, please avoid bringing up a malicious organization/project that's involved in spreading misinformation about GrapheneOS and harassing our developers. They're not a welcome topic in our community.

**Comment by thestinger** [comment]
There's already an open issue for this.
