### ISSUE TITLE
 '' Flash-all  ISSUE ''   -  After clicking flash- all CMD window pop up blank and closes himself instantly.

### ISSUE THREAD

**Issue by GrapheneHelp** [GrapheneOS/os-issue-tracker#650]
Hello community!

I have a big problem and i cant figure out what the issue is. I am a tech noob btw.

All previous install settings worked perfectly. but then..

 '' Flash-all  ISSUE ''   -  After clicking flash- all CMD window pop up blank and closes himself instantly.
 
 
 Thank you for your help!

**Comment by thestinger** [comment]
You're following an inaccurate and unsafe unofficial installation guide. Please stop doing that and remove everything it has had you download and install. Then, reboot the computer, boot the phone back to fastboot mode and use the web installer: https://grapheneos.org/install/web.

The official CLI guide is at https://grapheneos.org/install/cli and is NOT the process that you're following. If you insist on using the CLI installation for technical users rather than using the web installer, please use the official guide.

**Comment by thestinger** [comment]
Please use the Matrix room for support rather than the issue tracker. This doesn't involve bugs.

https://grapheneos.org/contact#community.
