### ISSUE TITLE
Google play store can't get status of installing applications

### ISSUE THREAD

**Issue by zxcvbzxcvb** [GrapheneOS/os-issue-tracker#659]
Google play store can't get status of installing/removing applications.
When you click on "install" or "uninstall" button Google play store hangs in "processing" status.

<details>
           <summary>Screens</summary>

![Screenshot](https://user-images.githubusercontent.com/91009760/133924306-017b179d-2e63-41b6-9ed6-2dc487753ec9.png)
![Screenshot](https://user-images.githubusercontent.com/91009760/133924315-d9f1aacd-a55e-4d5a-9d68-5d4ca9df8c2c.png)
![Screenshot](https://user-images.githubusercontent.com/91009760/133924352-09d11d4d-49e9-47b3-abf6-eb43b505658d.png)
</details>

**Comment by thestinger** [comment]
This is documented at https://grapheneos.org/usage#sandboxed-play-services. You need to force stop it after installing an app since we haven't taught it how to use the result from the user install dialog. We had to teach it how to use the user install dialog. I don't think there's a way to make uninstall work since unprivileged apps can't uninstall other apps.

**Comment by thestinger** [comment]
I guess we could make uninstall open up the app info page for that app for the user to uninstall it, but we couldn't give the Play Store the response from it.

**Comment by thestinger** [comment]
This is now implemented.
