### ISSUE TITLE
Custom CPU/GPU clock speeds.

### ISSUE THREAD

**Issue by TempUser13** [GrapheneOS/os-issue-tracker#667]
It'd be nice to be able to do custom clock speeds for both the CPU and GPU so battery usage can be heavily reduced or performance can be increased.

**Comment by thestinger** [comment]
This isn't within the scope of GrapheneOS and it doesn't work this way. There aren't specific clock speeds. The clocks are adjusted based on load, heat, etc. Lowering the maximum clock speeds will reduce rather than improving battery life by taking longer to get back to idle. The way to improve battery life at the expense of performance or performance at the expense of battery life would be changing complex tunables and algorithms which is not something realistic to expose as a setting beyond a coarse toggle with implementation-defined details specific to devices. Battery life impact from this is not something we're capable of actually reliably testing and therefore we can't do it. We won't ship changes that cannot really be verified/tested. Best to use the highly optimized defaults per AOSP / stock Pixel OS.

**Comment by Zanthed** [comment]
Simply use battery saving mode.
Messing with this kind of stuff only ruins stability and in most cases is snake oil. It's like iOS jailbreak users disabling random "useless" system daemons. It only causes jetsam problems, instability, and has been proven to be snake oil.

**Comment by TempUser13** [comment]
I meant clock ranges originally but thank you for the reply nonetheless.

**Comment by TempUser13** [comment]
> Simply use battery saving mode. Messing with this kind of stuff only ruins stability and in most cases is snake oil. It's like iOS jailbreak users disabling random "useless" system daemons. It only causes jetsam problems, instability, and has been proven to be snake oil.

I did this on my S10+ to lower battery usage and it worked, I used FKM to set the maximum clocks at 1.1/1.2Ghz for the CPU and never had any stability issues. Good to know about disabling iOS daemons though.
