### ISSUE TITLE
Notifications are no longer reliable

### ISSUE THREAD

**Issue by alandiwix** [GrapheneOS/os-issue-tracker#773]
After some very recent OS update GMS notifications no longer function properly and even alarm clock app doesn't always get triggered. Most of other applications (like timer) now are also stop working when I turn the screen off.
Did we have any changes introducing aggressive background task killing recently?

The "very recent" update I mean is not migration to Android 12, that went super smooth actually.

**Comment by thestinger** [comment]
Sounds like you have battery saver or a form of Do Not Disturb mode enabled. There are no recent changes to this.

**Comment by mikegriffin** [comment]
My alarm clock does not go off, whether the screen is off, or I am actively browsing a webpage. I am not in DND or Battery Saver modes and the battery my bramble is well charged. This started just over 48 hours ago after an update and my initial install was already on Android 12 last week without any alarm clock problems.

**Comment by thestinger** [comment]
There are frequent updates so an issue you encounter will always happen shortly after an update. It doesn't mean it was caused by the most recent update. You should try clearing your clock data. We had to downgrade it to AOSP 11 DeskClock code and that may be causing issues if you used the AOSP 12 DeskClock code already.

**Comment by guser303** [comment]
@alandiwix may have a point here. I'm not sure if it's related but sometimes notifications stop making any sound. DND / Battery Saver / Vibrate Only are not enabled. 

When a notification is received (in various apps) the phone does vibrate but no sound. It's intermittent and a reboot fixes it. I do not believe it's an Android 12 issue because it did happen now and then on android 11 albeit it was less common. 

I will try to grab some logs next time I encounter this.

**Comment by thestinger** [comment]
That doesn't sound like the same issue they're reporting above.

**Comment by mikegriffin** [comment]
Thanks for the quick reply. I deleted my alarms and unselected other cities, and creating a new test alarm worked.

I'll note that I have only had GrapheneOS installed for a about a week and the most recent update resulted in no alarm clock. It was my first update, I believe, because I noticed a reboot had occurred and turned off auto-reboot when idle.

**Comment by thestinger** [comment]
There was a specific issue with the Clock app: AOSP 12 clock code was buggy so we rolled it back to AOSP 11 and some users may need to clear data for it to work properly again due to the downgrade not really being supported. We didn't have time to fix the AOSP 12 clock code bugs yet though.

**Comment by thestinger** [comment]
I don't know *which* versions you're talking about but you can see when we rolled back to AOSP 11 Clock app code in our changelog.

**Comment by thestinger** [comment]
This is likely a configuration issue. Cannot be reproduced and we're not getting any reports of it. People are welcome to work on this but generic issues filed about it aren't going to help.
