### ISSUE TITLE
GMS apk not a valid package on subuser

### ISSUE THREAD

**Issue by Jmavd** [GrapheneOS/os-issue-tracker#881]
I am attempting to set up a second account that can work similarly to the first (notifications, apps, etc). I sucessfully installed the GSF apk from GrapheneOS's website, but upon installing GMS, it claimed that the package was invalid. I attempted to redownload it several times, each giving the same error. I would verify if its an issue for the Owner account, but I don't want to risk losing access to notifications there. I am using a Pixel 4a, and on the latest Stable release build.

**Comment by thestinger** [comment]
You have a conflicting app installed. This is how it works for every app and isn't a bug. You can't install an app with the same id that has a different signing key or is older. That's enforced across profiles. You probably updated it and have a newer one in Owner. We're not going to be updating the repository instantly since we need to test first.
