### ISSUE TITLE
Allow the user to specify custom servers for connectivity check

### ISSUE THREAD

**Issue by lbdroid** [GrapheneOS/os-issue-tracker#900]
Current options include "GrapheneOS", "Google", and "Disabled". I would like to be able to specify custom servers.

**Comment by lbdroid** [comment]
To some extent, however chances are that anyone who is running their own server, for whatever reason, is already making connections to that server, so there wouldn't be additional data leaked, whereas using the graphene server would identify that you are running graphene. There are benefits and tradeoffs to every choice that can be made.

A scenario where leaked data may be reduced to zero is where you use the same server for connectivity check *and* VPN. You're going to be connecting to the VPN anyway, so the connectivity check is free.

**Comment by thestinger** [comment]
> To some extent, however chances are that anyone who is running their own server, for whatever reason, is already making connections to that server

Those connections will be routed via their VPN if they're using one, which is implied if you care about this.

> A scenario where leaked data may be reduced to zero is where you use the same server for connectivity check and VPN. You're going to be connecting to the VPN anyway, so the connectivity check is free.

Using a VPN specific to yourself defeats nearly all the privacy advantages. Sites and services can still identify you based on IP and local networks can identify you based on a connection to a unique IP no one else uses.

**Comment by thestinger** [comment]
If you aren't using a VPN, this option doesn't matter much. The only reason we use GrapheneOS connectivity check servers by default is because there are already other connections to GrapheneOS servers by default for update checks, etc. Google mode matching how AOSP and the stock OS on nearly every Android device behave allows blending in with other devices. That's our recommendation when using a VPN.

I don't see the use case for an option beyond GrapheneOS, Google and Disabled. Needing to add support for configuring 4 or more separate URLs requires maintaining a complex addition to the Settings UI and there has to be a compelling reason to do it.

**Comment by thestinger** [comment]
When you're using a VPN, the other connections to GrapheneOS services are routed through the VPN so the GrapheneOS mode doesn't blend in as well as the Google mode. Disabled mode allows people to disable it if the checks are being annoying such as if the servers are down.

I don't really see why someone would want to manually configure 4+ connectivity check URLs to point at their own server in a way that reduces their privacy. They'll still be using GrapheneOS services for OS updates, app updates (via our upcoming app repository), network time updates (cannot be a standard protocol until Android supports NTS) and other things. It just doesn't make sense to expect to avoid needing our services for our OS builds. It's open source and you can make your own OS builds and can easily host your own update server, etc. if you want but we aren't going to add extra complexity which holds back the project without any real reason.

**Comment by lbdroid** [comment]
Let me put it a different way, I'd rather use all my servers than to be tracked by graphene servers. I get that you recognize yourself as trustworthy and non-tracking, but so does google, which you object to.

**Comment by thestinger** [comment]
I don't know what you mean by tracked, and I don't know what you think we object to about using the Google servers for connectivity checks. In fact, I just told you that's our recommendation when using a VPN to blend in with other users. The reason for using our servers by default is because it's already identifiable as a GrapheneOS device until you're using a VPN. We can eventually provide usage guide sections on these things with a simple explanation of how to set it up something like a VPN well for a given purpose.

**Comment by thestinger** [comment]
I suggest reading the documentation explaining how these things work which we have in our FAQ. You don't seem to have read that and don't understand what the connectivity checks provide. They make an HTTP(S) GET request without any data that varies between different users, device models or operating systems. I have no clue how you think it's tracking. You don't seem to understand what it does or how it works, or the connection to privacy.

I'm not going to repeat what was already written above.

**Comment by lbdroid** [comment]
You know perfectly well that you don't need to exchange specific information to be tracked. The connection alone is a trackable point of data.

**Comment by thestinger** [comment]
It's not at all clear what you mean by that. You're going to need to clarify.
