### ISSUE TITLE
[crosshatch] Wifi and bluetooth cut off randomly for maybe hours at a time

### ISSUE THREAD

**Issue by danwdart** [GrapheneOS/os-issue-tracker#909]
Since a couple of releases before 12, maybe September time, I've had the wifi and bluetooth randomly die and not be able to be enabled for hours at a time even across reboots, which is especially dangerous for contact tracing.

What seems to happen is that often, wifi will say that it's disabled, and when it's tried to be enabled, it just won't have the toggle switch turned on, and that when searching for devices the bluetooth will say things like "Will turn on" after it's supposed to have already been on, and its toggle switch will also turn itself off after being turned on. The notification bar will appear to show bluetooth on as well, but when pulled down it's revealed to be off.

Having trouble doing logcats or dmesgs to see if it's somehow an intermittent hardware issue, but given that sometimes it works again after a reboot and sometimes it doesn't, it sounds more like a software issue.

What can I do to help move forward the investigation of this? What logs can I attach?

Using latest beta on crosshatch, SP1A.210812.016.A2.2022011009.

Thanks

**Comment by thestinger** [comment]
It's very unlikely that this is a GrapheneOS issue rather than a hardware issue. I don't think we're going to be able to do anything about it. Every user of GrapheneOS has identical firmware and OS images. If this was a software issue it would presumably be happening for other people. It's not the kind of thing which would happen for just one user.
