### ISSUE TITLE
[Pixel 6][System Settings - All Apps] Last app in apps overview isn't selectable in 2-button-gesture mode

### ISSUE THREAD

**Issue by SHA-NDY** [GrapheneOS/os-issue-tracker#913]
The last app in the all apps overview isn't selectable when fully scrolled up because the navigation bar is overlayed in 2-button-gesture mode.

![Screenshot_20220113-190634](https://user-images.githubusercontent.com/67801045/149385239-0f8a2dfe-aec9-42e7-bdfa-a85fc22a9ef0.png)

**Comment by Zanthed** [comment]
You should consider using 3-button gesture mode. 2-button gesture mode is deprecated in upstream and even has been removed from stock OS and we can't maintain it. We're likely going to remove it entirely.

https://grapheneos.org/usage#2-button-navigation

> 2-button navigation is a legacy mode not supported anymore by Google Android on the Pixel 4 and later. It will likely be removed in a future release of GrapheneOS. You should use [3-button navigation](https://grapheneos.org/usage#3-button-navigation) if you want the traditional button-based navigation.

If this happens with 3-button navigation than we can leave this open, but otherwise this is just the nature of deprecated features.

**Comment by SHA-NDY** [comment]
All good, I switched to non-button navigation and I am completely happy now. Thanks.
