### ISSUE TITLE
Implement toggle for restricting device identifiers sent to non-carrier Google SUPL server

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#915]
This will _break_ the SUPL standard but it seems to work and the user should be warned about potential issues be they current or future.

**Comment by Ryu945** [comment]
> This will _break_ the SUPL standard but it seems to work and the user should be warned about potential issues be they current or future.

This actually doesn't break the standard.   As pointed out in this article, a SUPL request done with a phone that has no IMSI sends an IMSI value of 0.

https://blog.wirelessmoves.com/2014/08/supl-reveals-my-identity-and-location-to-google.html

**Comment by thestinger** [comment]
The identifiers were removed and we also added a toggle for force disabling SUPL regardless of the carrier configuration instead of needing to edit APN types to remove `supl` which doesn't work as expected on Tensor SoC Pixels where SUPL isn't as strongly tied to carrier configuration and can work without a cellular data connection.
