### ISSUE TITLE
Feature request: New lease of per network random and manually set a MAC-address

### ISSUE THREAD

**Issue by ph00lt0** [GrapheneOS/os-issue-tracker#938]
It would be great if:
- We would be able to get a new lease of a per network random MAC-address. To manually reset the MAC-address
- We have the ability to manually configure a spoofed MAC-address instead of using a random one provided by the OS.

**Comment by thestinger** [comment]
We're not going to provide manual configuration. That would be far from being a random MAC.

If I'm understanding you correctly, you want the ability to use a per-network random MAC instead of a per-connection random MAC while still being able to cycle it. It's provided by Android's experimental enhanced MAC randomization developer option for the per-network random MAC (Android's standard approach). In the enhanced mode, it cycles the MAC when the DHCP lease expires and on reboot. It's not clear why they implemented it that way since it's not really persistent enough due to changing on reboot.

I don't really see the reason to pursue this further instead of simply using our default per-connection random MAC. You'll need to better explain what you want and the purpose for it.

**Comment by ph00lt0** [comment]
@thestinger the reason for the request is for networks secured by whitelists with captive portals. If you enable randomization it is impossible to use the network as every-time one needs to log in (happens often because of bad connectivity). However you may still want to cycle the mac-address manually this now is not possible. 

The request for manual config could help f.x. when wanting to use a previously whitelisted mac-address. This to prevent having to enable internet connectivity checks on the phone and use another device to initiate the whitelisting.

**Comment by Zanthed** [comment]
You can just use the per-network MAC randomisation instead of the default per-connection. Having weird manual controls like these doesn't make it random anymore and would be substantially harmful to privacy.

I don't understand what you mean by "This to prevent having to enable internet connectivity checks on the phone and use another device to initiate the whitelisting."

**Comment by ph00lt0** [comment]
@Zanthed the per network randomization will always issue the same mac with the same network, and there are situation in which you want to renew this, in order not to associate a previously obtained account with the current one. 

Let me give an example. For example you are on a cruise boat who has these captive portals on the Wi-Fi and you need to use this to go online. Then you need to use per network randomization. Which will work fine that time, imagine now you traveling again with them or brought an new voucher to go online again. At all costs I would want to associate the same MAC with that trip. That would make it easier to figure out who is the owner of the device as not many people will be on the exact same two trips. The solution to that would be manual cycling the MAC. I think it would perhaps be best to do that when a user 'forgets' the network, currently after reconnecting the same MAC will be generated.

The second is a more limited scope but I prefer having the internet connectivity checks disabled on my main device. If I can set up a authenticated session using a random mac address on another device and then clone this into the other phone I could go online without my main ever having the to touch this captive portal.

**Comment by thestinger** [comment]
Did you try the AOSP 'enhanced randomization' that I suggested?
