### ISSUE TITLE
Unlock phone with YubiKey over NFC or USBC

### ISSUE THREAD

**Issue by sawft99** [GrapheneOS/os-issue-tracker#940]
I believe nfc used to be an option with Android that got removed/discontinued. It also appears that even in the base Android NFC is turned off when locked. As I understand this is not supported for situations such as someone stealing your phone and using the wallet capability. With that in mind I'm sure it would technically lessen security. However, I only use NFC for my YubiKey as is. I have no wallet or other apps with those capabilities. That said I am still not sure if that would constitute a risk just by having it on when locked even if you have no apps or only one that uses the ability. If that is the case and is possible I can see the issues then. Perhaps a warning or something could appear to inform users of the implications if it were in place?
 
Would there be similar concerns of security holes over USBC? 

I noticed issues #816 and #465 which seemed to be related. I am sure those would also be prerequisets before making this a possibility.

Despite not seeing any other issue numbers I can't imagine I'm the only one to think of this and there is something I don't know. Or the other security holes that could potentially be created are of greater concern and this should't even be considered.

**Comment by thestinger** [comment]
Android never supported this. Play services has had smart lock options which are a different thing than the primary and secondary unlock mechanisms supported by the OS. It has never been either a primary or even a normal secondary unlock mechanism, only a smart lock feature.

There are no plans to implement this. Set a random 6 digit PIN and you have highly secure encryption based on the secure element in the phone. The secure element in the phones is far more secure than a YubiKey. It can also be used for FIDO2 rather than needing a separate security key as long as apps support it. You haven't explained the details on how you would want this to work, why you want this, in which threat model it makes sense and what it offers over the existing options.

**Comment by sawft99** [comment]
> Android never supported this. Play services has had smart lock options which are a different thing than the primary and secondary unlock mechanisms supported by the OS. It has never been either a primary or even a normal secondary unlock mechanism, only a smart lock feature.
> 
> There are no plans to implement this. Set a random 6 digit PIN and you have highly secure encryption based on the secure element in the phone. The secure element in the phones is far more secure than a YubiKey. It can also be used for FIDO2 rather than needing a separate security key as long as apps support it. You haven't explained the details on how you would want this to work, why you want this, in which threat model it makes sense and what it offers over the existing options.

My mistake, I thought I had heard it was a feature previously. I also was unfamiliar with the Secure Element component. I don't have an in depth knowledge in this field. I think Secure Element sounds like TPM for phones essentially? In which case can there simply be a challenge or whatever the mecahnism would be exactly to authenticate between the SE and Yubikey?

I just thought that in addition to a pin, or to substitute, it would offer another option as far as security and usability. Just as there are options to use your face or a fingerprint, some of which graphene does, I had thought a key would be an option as well. It takes me just about about as long to put my thumb on as it does to pull out my yubikey.

I would prefer not to use a biometric option though. A pin seems to have no immediate downsides as long as it is a good combination.  If there is a way for FIDO2 to be used on the element isn't that only one standard (OTP, etc)? Versus Yubikeys supporting several. I also use my yubikeys interchangibly with my other devices. Is it even possible to use my phone for a FIDO2 operation on my computer? Even if you could it still sounds like a limitation if it only supports FIDO2.

As far as how, I am not sure as I don't program at this level or have as much of an in depth knowledge of phones. It looks like only [a portion of chipsets](https://developers.google.com/android/security/android-ready-se/supported-chipsets?ENABLE_SIGNIFICATIO=False#nxp) support this. I am not sure if that covers 100% of phones or 5%. I also see that there is documentation on [Secure NFC](https://source.android.com/devices/tech/connect/secure-nfc) and [Card Emulation](https://developer.android.com/guide/topics/connectivity/nfc/hce) which seems to demonstrate using NFC capabilties that interact with Secure Element.

As far as a threat model, it just seems like an additional security feature. If pin and thumbprint is supported, wouldn't a yubikey be in the same realm while also not involving a biometric in one case? If secure NFC works as I understand it, and over FIDO2, does that represent any more of a risk versus just a pin? Could it be better since it eliminates, or it could, the need for a password? Some of the yubikeys primary purposes is to facilitate passwordless login, FIDO2 authentication with a piece of hardware, and in general making secondary authentication with a physical object you rely on, where the token can not be forged/intercepted, or at least far more difficult. It would seem to me this is just moving that same model to a phone.

If I could only unlock my phone with a yubikey wouldn't that be more secure than a simplle pin, if implemented correctly? I understand you could have a 6+ charecter password, but I think that brings up another aspect of yubikeys which can remove the user element of a bad password, other practices, and idiot proofing security a bit more.

Or your pin could be comprimised in some way whether shoulder surfed, guessed, or coerced into giving it over, and the Yubikey was used as a 2fa mechanism, you could potentially mitigate risk. At then end of the day if you're kidnapped or being held by some authorities you can be forced to hand it over, but the same could be said for pin/thumb. In the US at least I have seen a number of times where people are forced to put their thumb on the phone to unlock, rarely do i hear about a pin, and i have never heard about handing over a yubikey.

Pardon me if any of that was completely ignorant because i didnt have a full understanding of a technology. I'm also not trying to argue out of spite, just trying to talk through it if it didnt seem that way. Thank you for all your efforts.

**Comment by thestinger** [comment]
> My mistake, I thought I had heard it was a feature previously. I also was unfamiliar with the Secure Element component. I don't have an in depth knowledge in this field. I think Secure Element sounds like TPM for phones essentially? In which case can there simply be a challenge or whatever the mecahnism would be exactly to authenticate between the SE and Yubikey?

You have this totally backwards. TPM is an ancient API used for x86 secure elements. It's not a good API and most of the implementations are terrible.

> I just thought that in addition to a pin, or to substitute, it would offer another option as far as security and usability. Just as there are options to use your face or a fingerprint, some of which graphene does, I had thought a key would be an option as well. It takes me just about about as long to put my thumb on as it does to pull out my yubikey.

There's a major difference between the primary unlock mechanism and secondary unlock mechanisms. It's really not clear what you're proposing to add. As I said earlier, it's not clear what the goal is that you're aiming to accomplish and a YubiKey is not at all a high quality secure element like the one in the phone.

> I would prefer not to use a biometric option though. A pin seems to have no immediate downsides as long as it is a good combination. If there is a way for FIDO2 to be used on the element isn't that only one standard (OTP, etc)? Versus Yubikeys supporting several. I also use my yubikeys interchangibly with my other devices. Is it even possible to use my phone for a FIDO2 operation on my computer? Even if you could it still sounds like a limitation if it only supports FIDO2.

FIDO2 is the standard for security key authentication. U2F (FIDO1) is deprecated. I don't know why you're talking about stuff like TOTP which is insecure and also not the same class of technology. It's not a security key technology. This is becoming a bunch of support questions and isn't a good fit for the issue tracker.

> As far as how, I am not sure as I don't program at this level or have as much of an in depth knowledge of phones. It looks like only a portion of chipsets support this. I am not sure if that covers 100% of phones or 5%. I also see that there is documentation on Secure NFC and Card Emulation which seems to demonstrate using NFC capabilties that interact with Secure Element.

I don't know what this has to do with GrapheneOS.

I'm not going to go through the rest of your response. You're expecting a lot of time to be invested in answering a ton of different questions. This really isn't a viable way to make a feature request.

**Comment by thestinger** [comment]
If you want to make a feature request, you're going to need to have a good understanding of the area where you're proposing the feature. It's just going to be closed otherwise unless we can interpret it into a proper feature request. It's not something we can do with this and it's not something we have any plans to add in any way.

> As far as how, I am not sure as I don't program at this level or have as much of an in depth knowledge of phones. It looks like only a portion of chipsets support this. I am not sure if that covers 100% of phones or 5%. I also see that there is documentation on Secure NFC and Card Emulation which seems to demonstrate using NFC capabilties that interact with Secure Element.

Also, this is really not what is being talked about.

**Comment by thestinger** [comment]
As a starting point you need to read and understand the relevant portions of https://grapheneos.org/faq#encryption explaining Weaver and insider attack protection. You can also read about those from Google's blog posts but they don't cover Weaver in any detail or explain how the throttling works. They do cover insider attack protection more than we do in some of their posts. There are many more things provided by the secure element including the StrongBox keystore. It's a far better implementation of a secure element than a YubiKey or TPM and offers a far better API which is available to apps via the hardware keystore API.

If you want to propose something that has to do with external security keys then you need to figure out a reasonable request to make based on an understanding of how things work. We can't do anything with this. It needs to be a clear request for a specific design with a clear rationale and threat model. We're not adding security keys as a single factor secondary unlock mechanism and there isn't ever going to be 2-factor authentication for the primary unlock mechanism for important reasons. It's not a valid feature request since it's not clear what is being proposed. There would be valid feature requests which could be made for this but please bear in mind that if you aren't planning to work on it then it's unlikely it is ever going to get done and therefore it's just wasting your time and our time to propose it. Our issue tracker is full of planned features including many high priority ones. There isn't much reason to file additional feature requests unless they're either tiny / easy to implement or something very crucial. An exception is if you plan to get it implemented.

**Comment by robinschwab** [comment]
Unlocking your phone with NFC makes sense if you have a NFC finger ring. While everyone leaves his/her phone unattended for a while this is not the case for a ring (or implant).

This method can be insecure if you would just use UID for unlock. But nowadays one would implement this via FIDO2 U2F so it should be very safe.
