### ISSUE TITLE
Location is broken on Pixel 6 Pro

### ISSUE THREAD

**Issue by iwLain** [GrapheneOS/os-issue-tracker#943]
No app, neither in the work profile, nor the Personal one can get my location even though they have the permission. This is also unaffected by my actual location. On the original ROM everything worked fine.

**Comment by Zanthed** [comment]
Need more details here.

Do you have Google Play installed? If so, duplicate of #635 and we're aware with a fix coming soon. Nothing you can do since apps will try to use the geolocation APIs provided by Google Play.

If not, do you have a SIM card in? 
If you don't have a SIM card in, it's expected that geolocation will be very slow due to no location provider and relying solely on GNSS. And the Pixel 6 / 6 Pro have worse GNSS hardware than previous models using Qualcomm.

Put a SIM card in and you'll use A-GPS + GNSS which will substantially improve it.

Wi-Fi and Bluetooth scanning also do not do anything at the moment for both.

**Comment by iwLain** [comment]
it is indeed a duplicate, sorry for the trouble.
