### ISSUE TITLE
Remove supl.google.com

### ISSUE THREAD

**Issue by condor0765** [GrapheneOS/os-issue-tracker#96]
Not sure if this is being used or alternatives available. As you are de-googling stuff, may be this also?
```
    <!-- Values for GPS configuration -->
    <string-array translatable="false" name="config_gpsParameters">
        <item>SUPL_HOST=supl.google.com</item>
        <item>SUPL_PORT=7275</item>
        <item>SUPL_VER=0x20000</item>
        <item>SUPL_MODE=1</item>
        <item>SUPL_ES=1</item>
        <item>LPP_PROFILE=0</item>
        <item>USE_EMERGENCY_PDN_FOR_EMERGENCY_SUPL=1</item>
        <item>A_GLONASS_POS_PROTOCOL_SELECT=0</item>
        <item>GPS_LOCK=0</item>
    </string-array>
```
Reference:
https://github.com/GrapheneOS/platform_frameworks_base/blob/f6a741d32effbb2dabea63c577932f9d8007242b/core/res/res/values/config.xml#L2823

**Comment by thestinger** [comment]
> Not sure if this is being used or alternatives available.

I'm aware of the Secure User-Plane Location (SUPL) support. I have https://github.com/GrapheneOS/os_issue_tracker/issues/24 as a meta issue about the more general topic of reviewing the supplementary location information support, figuring out what is present or missing and providing alternative implementations.

Simply removing the support for SUPL without understanding if it is used in practice based on the other configuration, when it's used and whether it's required by law isn't an option. The project doesn't make changes without fully understand what it's doing. I also wouldn't see the value in switching to another project just for the sake of doing it rather than because there are tangible benefits.

> As you are de-googling stuff

I don't know what you mean by that. I would not describe anything the project is as that. It implements improvements to privacy and security. The project does not aim to avoid Google services *in particular* but rather privacy issues *in general*. You may be under the wrong impression about what GrapheneOS is all about. It would not be seen as a positive change to switch from Google to another provider for a service simply because they are not Google. The reason for switching the *fallback* DNS servers away from Google Public DNS is because the replacement provider has a slightly better privacy policy and the servers are generally faster too. I can't think of another change like that in the OS. For the most part, the Android Open Source Project doesn't support Google services in the first place.

**Comment by thestinger** [comment]
> Not sure if this is being used or alternatives available.

I'm aware of the Secure User-Plane Location (SUPL) support. I have https://github.com/GrapheneOS/os_issue_tracker/issues/24 as a meta issue about the more general topic of reviewing the supplementary location information support, figuring out what is present or missing and providing alternative implementations.

Simply removing the support for SUPL without understanding if it is used in practice based on the other configuration, when it's used and whether it's required by law isn't an option. The project doesn't make changes without fully understand what it's doing. I also wouldn't see the value in switching to another provider just for the sake of doing it rather than because there are tangible benefits.

Research will need to be done on this before any changes will be made. There aren't currently contributors working on research or implementing features filed in this tracker, so I'd recommend working on something rather than filing issues here. The project has a lot of ideas for things that need to be worked on already, but a lack of people working on them.

> As you are de-googling stuff

I don't know what you mean by that. I would not describe anything the project is as that. It implements improvements to privacy and security. The project does not aim to avoid Google services *in particular* but rather privacy issues *in general*. You may be under the wrong impression about what GrapheneOS is all about. It would not be seen as a positive change to switch from Google to another provider for a service simply because they are not Google. The reason for switching the *fallback* DNS servers away from Google Public DNS is because the replacement provider has a slightly better privacy policy and the servers are generally faster too. I can't think of another change like that in the OS. For the most part, the Android Open Source Project doesn't support Google services in the first place.

**Comment by thestinger** [comment]
> Not sure if this is being used or alternatives available.

I'm aware of the Secure User-Plane Location (SUPL) support. I have https://github.com/GrapheneOS/os_issue_tracker/issues/24 as a meta issue about the more general topic of reviewing the supplementary location information support, figuring out what is present or missing and providing alternative implementations.

Simply removing the support for SUPL without understanding if it is used in practice based on the other configuration, when it's used and whether it's required by law isn't an option. The project doesn't make changes without fully understand what it's doing. I also wouldn't see the value in switching to another provider just for the sake of doing it rather than because there are tangible benefits.

Research will need to be done on this before any changes will be made. There aren't currently contributors working on research or implementing features filed in this tracker, and I'd recommend working on something rather than filing feature requests. The project has a lot of ideas for things that need to be worked on already, but a lack of people working on them.

> As you are de-googling stuff

I don't know what you mean by that. I would not describe anything the project is as that. It implements improvements to privacy and security. The project does not aim to avoid Google services *in particular* but rather privacy issues *in general*. You may be under the wrong impression about what GrapheneOS is all about. It would not be seen as a positive change to switch from Google to another provider for a service simply because they are not Google. The reason for switching the *fallback* DNS servers away from Google Public DNS is because the replacement provider has a slightly better privacy policy and the servers are generally faster too. I can't think of another change like that in the OS. For the most part, the Android Open Source Project doesn't support Google services in the first place.

**Comment by nutts0** [comment]
> whether it's required by law isn't an option.

I couldn't find information about if it is required by law. Also which law are you referring to? Isn't there already some differences based on which country you run your device. For example in Africa emergency call is not needed. 

I'm just reading googles patent. Maybe I will find something interesting.

https://patents.google.com/patent/US20150005006A1/en

**Comment by condor0765** [comment]
> > Not sure if this is being used or alternatives available.
> 
> I'm aware of the Secure User-Plane Location (SUPL) support. I have #24 as a meta issue about the more general topic of reviewing the supplementary location information support, figuring out what is present or missing and providing alternative implementations.
> 
> Simply removing the support for SUPL without understanding if it is used in practice based on the other configuration, when it's used and whether it's required by law isn't an option. The project doesn't make changes without fully understand what it's doing. I also wouldn't see the value in switching to another provider just for the sake of doing it rather than because there are tangible benefits.

I am well aware that you know better about these than myself. That is why I put this like a suggestion.



> > As you are de-googling stuff
> 
> I don't know what you mean by that. I would not describe anything the project is as that. It 

I did not mean de-googling in any negative sense. 

> implements improvements to privacy and security. The project does not aim to avoid Google services _in particular_ but rather privacy issues _in general_. You may be under the wrong 

I did not mean or imply these.

> impression about what GrapheneOS is all about. It would not be seen as a positive change to switch from Google to another provider for a service simply because they are not Google. The reason for switching the _fallback_ DNS servers away from Google Public DNS is because the replacement provider has a slightly better privacy policy and the servers are generally faster too. I can't think of another change like that in the OS. For the most part, the Android Open Source Project doesn't support Google services in the first place.

**Comment by thestinger** [comment]
It can be left open but it's currently an open research question.

**Comment by lazerl0rd** [comment]
> I'm aware of the Secure User-Plane Location (SUPL) support. I have #24 as a meta issue about the more general topic of reviewing the supplementary location information support, figuring out what is present or missing and providing alternative implementations.

There's also the problem that SUPL servers are defined in Device Trees and Vendor Trees across _both_ the **config.xml** and **gps.conf** (I've tried to explain most of the features [here](https://github.com/lazerl0rd/optmizedgpsconf/blob/master/system/etc/gps.conf)). Google isn't the only one used. It seems certain carriers have their own defined too.

> Simply removing the support for SUPL without understanding if it is used in practice based on the other configuration, when it's used and whether it's required by law isn't an option. The project doesn't make changes without fully understand what it's doing. I also wouldn't see the value in switching to another provider just for the sake of doing it rather than because there are tangible benefits.

I've been looking up and can't see why disabling/using a different SUPL server which provides better privacy (let's be honest, are you gonna really think Google aren't gonna take any "stats" out of this?). http://www.openmobilealliance.org/release/SUPL/V3_0-20110920-C/OMA-TS-ULP-V3_0-20110920-C.pdf and some Googling doesn't seem find any laws enforcing the usage of a specific set of servers at all. It'll be interesting to know what iOS uses as I couldn't get further than https://forums.developer.apple.com/thread/46319.

Personally, and I'm sure to a lot of people, location data is quite sensitive and would like to be guarded. It seems though, that there isn't documentation evidencing that SUPL is used only on High Accuracy/Power Saving GPS modes and that it comes into account even on Device Only. This is a privacy concern from some the way I see it and would result in a tangible benefit, no?

> For the most part, the Android Open Source Project doesn't support Google services in the first place.

I'm not sure what you mean by this. GApps (I'm collectively adding Google Play Services with it's framework and core apps here) are literally a set of propitiatory Android applications with GSF and GSM utilising hidden API whitelists and features that do exist in AOSP. I can't see how they are "haxxed" in or not support.

There's quite a few other servers used in the GPS setup, including [NTP](https://github.com/lazerl0rd/optmizedgpsconf/blob/master/system/etc/gps.conf#L48) and [C2K PDE](https://github.com/lazerl0rd/optmizedgpsconf/blob/master/system/etc/gps.conf#L162).

**Comment by thestinger** [comment]
> There's also the problem that SUPL servers are defined in Device Trees and Vendor Trees across both the config.xml and gps.conf (I've tried to explain most of the features here). Google isn't the only one used. It seems certain carriers have their own defined too.

Being defined somewhere doesn't mean it's used at all. So far, no one actually seems to have done the necessary research into this.

> I've been looking up and can't see why disabling/using a different SUPL server which provides better privacy (let's be honest, are you gonna really think Google aren't gonna take any "stats" out of this?). http://www.openmobilealliance.org/release/SUPL/V3_0-20110920-C/OMA-TS-ULP-V3_0-20110920-C.pdf and some Googling doesn't seem find any laws enforcing the usage of a specific set of servers at all. It'll be interesting to know what iOS uses as I couldn't get further than https://forums.developer.apple.com/thread/46319.

Which SUPL server do you think is being used for a given carrier at the moment, if at all, and have you confirmed your hypothesis?

> Personally, and I'm sure to a lot of people, location data is quite sensitive and would like to be guarded. It seems though, that there isn't documentation evidencing that SUPL is used only on High Accuracy/Power Saving GPS modes and that it comes into account even on Device Only. This is a privacy concern from some the way I see it and would result in a tangible benefit, no?

You're making a lot of assumptions and unverified claims.

> I'm not sure what you mean by this. GApps (I'm collectively adding Google Play Services with it's framework and core apps here) are literally a set of propitiatory Android applications with GSF and GSM utilising hidden API whitelists and features that do exist in AOSP. I can't see how they are "haxxed" in or not support.

I don't know what you're talking about and how it could possibly contradict what I said. The Android Open Source Project doesn't contain Google Play Services... and the way it gets integrated doesn't work the way you describe. Other platform / privileged apps can do the same things. It's not something specific to Play Services. The providers it implements can be provided by other apps.

> There's quite a few other servers used in the GPS setup, including NTP and C2K PDE.

You're drawing too many conclusions from reading one of the configuration files for this. You need to do the research and testing before jumping to conclusions.

**Comment by lazerl0rd** [comment]
> > I've been looking up and can't see why disabling/using a different SUPL server which provides better privacy (let's be honest, are you gonna really think Google aren't gonna take any "stats" out of this?). http://www.openmobilealliance.org/release/SUPL/V3_0-20110920-C/OMA-TS-ULP-V3_0-20110920-C.pdf and some Googling doesn't seem find any laws enforcing the usage of a specific set of servers at all. It'll be interesting to know what iOS uses as I couldn't get further than https://forums.developer.apple.com/thread/46319.
> 
> Which SUPL server do you think is being used for a given carrier at the moment, if at all, and have you confirmed your hypothesis?

Sprint for example, defined https://github.com/AOSiP-Devices/device_lge_bullhead/blob/d854480b79d2559d242cc38bf1cacd566d4e48a9/overlay/frameworks/base/core/res/res/values-mcc001-mnc001/config.xml. TELUS Mobility (I've never heard of them before) 
 here https://github.com/AOSiP-Devices/device_lge_bullhead/blob/d854480b79d2559d242cc38bf1cacd566d4e48a9/overlay/frameworks/base/core/res/res/values-mcc302-mnc220/config.xml.

> You're making a lot of assumptions and unverified claims.

To summarise what I meant here is to say that the SUPL server is Google's and they have no statement saying they respect the privacy of the data they receive from this and so we cannot assume it is "secure" by default.

> I don't know what you're talking about and how it could possibly contradict what I said. The Android Open Source Project doesn't contain Google Play Services... and the way it gets integrated doesn't work the way you describe. Other platform / privileged apps can do the same things. It's not something specific to Play Services. The providers it implements can be provided by other apps.

I seem to have misunderstood what you were saying in this part of my reply.

> You're drawing too many conclusions from reading one of the configuration files for this. You need to do the research and testing before jumping to conclusions.

Thanks for the advice.

**Comment by lazerl0rd** [comment]
Something that is bothering is whether SUPL is actually not used until "Google's location network service" is used. I couldn't find out whether this is the case or not but in Android 9 Google seemed to add an option called "Emergency Network location" which seems to sound like it's connected to `USE_EMERGENCY_PDN_FOR_EMERGENCY_SUPL`.

I have looked at more than just a single config file in this matter across a range of devices, but there doesn't seem to be _much_ documentation about any of Qualcomm's internals. If you had anywhere that would be very useful to mind, I'd be grateful if you could share it.

**Comment by dm17** [comment]
Maybe this could be left as modular to make it easier for testers & developers to further de-Google their GOS phones without having to have their own builds? Of course, hiding it in advanced settings or something would be no problem.

**Comment by thestinger** [comment]
Don't know what you mean by that.

**Comment by thestinger** [comment]
You can already verify that the OS makes no connections to supl.google.com. From what I can tell, this is provided to the radio as a fallback for when the carrier doesn't provide the functionality, and they are probably required by law to provide it everywhere. I'm not sure that it's actually ever used. As I said above, further research is required, and it's unhelpful to have people making assumptions about it.

**Comment by dm17** [comment]
> You can already verify that the OS makes no connections to supl.google.com. From what I can tell, this is provided to the radio as a fallback for when the carrier doesn't provide the functionality, and they are probably required by law to provide it everywhere. I'm not sure that it's actually ever used. As I said above, further research is required, and it's unhelpful to have people making assumptions about it.

I see - thanks for the clarification.

**Comment by flawedworld** [comment]
#915 #914

**Comment by thestinger** [comment]
SUPL isn't used during normal operation. Only the carrier layer control plane implementation is used. SUPL is used for emergency calls and the implementation of SUPL varies.
