### ISSUE TITLE
quick settings media player enhancement.

### ISSUE THREAD

**Issue by zee0** [GrapheneOS/os-issue-tracker#978]
the media player in quick settings on my pixel 4a device ends up at the bottom of the list. the buttons in the player are pretty much off the screen, and when tapped, the quick settings closes.

example issue: i'm listening to a podcast and would like to skip the commercials:

i swipe down on my locked device to access quick settings, i tap the button to skip 15 seconds ahead. half the time, my thicc finger that close to the bottom of the screen is not registered as an accurate button tap and the quick settings drawer closes and i have to start over. the other half the time, i accurately hit the button and the podcast skips 15 seconds ahead but the quick settings drawer closes, so if i want to skip further ahead than 15 seconds, i have to reopen the quick settings drawer for each skip (with the same 50/50 chance of an inaccurate tap missing the button).

the result is, i never use the media player in quick settings. every time i want to skip ahead, unlock my device and use the app.

**Comment by thestinger** [comment]
The way the notification appears and whether it's persistent is up to the application. New notifications will always appear at the bottom of the section. Many notifications are minimum or low priority so they appear collapsed in the Silent section below everything else. You're meant to go through and clear away the non-Silent notification and reduce ones you don't want to treat as priorities to lower priority. Minimum priority notifications (collapsed fully enabled in the settings) also don't appear on the lockscreen or status bar.

This sounds like a combination of things working as designed with the app not having a good notification UI.

**Comment by zee0** [comment]
i think you're misunderstanding. it's less the media player, and more the quick settings drawer that is the issue.

**Comment by s00se** [comment]
Here is an example of what @zee0 might be referring to, and while it is how AOSP functions (or rather, doesn't) and should be dealt with upstream, it's an annoying quirk and honestly would be nice to have it _adjusted_ in on daily driver devices, but it's clear it's not a GrapheneOS problem to solve, but it would be nice. Apologies for the huge image.

![snap](https://user-images.githubusercontent.com/95649696/154156170-32945fef-afe2-4320-9cf9-ac46b60da031.png)

When using the default display size (smallest width 392), the notification is pushed down "behind" the gesture bar, in my case this is specifically due to the VPN message indicator, as when it's not there, the notification sits inside the viewport correctly and the controls are usable.

Something like having a toggle for displaying the VPN info might mitigate it in my specific screenshot example, but it's essentially a hacky tweak. 

On previous versions of Android, removing the developer version tag reduced the vertical space when there weren't 2 pages of icons in the quick settings, so no dot indicator was shown -- but this doesn't seem to work on Android 12, there's still a big dead space where that developer version tag is shown.
