### ISSUE TITLE
improve all system app icons

### ISSUE THREAD

**Issue by gosreport** [GrapheneOS/os-issue-tracker#999]
this would improve the user experience and bring a cohesive design to grapheneos

this would be a big visual overhaul and take time to implement, so i would suggest slowly updating the icons with each new release as a side project

here is a mockup on how the icons can be improved with material icons

current app icon

![old.png](https://user-images.githubusercontent.com/99921949/154786707-25f463e4-9b87-49e0-94f8-bde2900e2b8a.png)

improved app icon

![new.png](https://user-images.githubusercontent.com/99921949/154786712-3eed2a55-428b-4f43-ade7-e4189ee6c44c.png)

![screenshot.png](https://user-images.githubusercontent.com/99921949/154786862-3fda701f-359b-42ae-82fe-e5e0b6d40b98.png)

suggestion for an improved grapheneos launcher icon

current app icon

![old.png](https://user-images.githubusercontent.com/99921949/154787268-f52a2f16-423e-45e8-b228-aa82546843e4.png)

improved app icon

![new.png](https://user-images.githubusercontent.com/99921949/154787335-88e746a4-d6e5-43ee-a230-4fea91ac6497.png)

those are examples of what can be improved

every system app icon could be improved slowly with future releases

**Comment by lbdroid** [comment]
I actually wish that the icons would all be left alone (and in cases where they have been changes, reverted back to aosp). The black and white icons are *really ugly*.

**Comment by Zanthed** [comment]
@lbdroid The AOSP icons are legacy bitmaps with no consistent style or adaptive icon support. We're not reverting them or picking a different style.

Please keep discussions relevant to the issue and refrain from unrelated comments.

**Comment by Zanthed** [comment]
@gosreport It's unclear if we want to change system icons, especially if they're non-user facing like these. We only focused on changing the user-facing icons at the moment which are our own apps + things like Settings, Contacts, Messenger, etc.

**Comment by thestinger** [comment]
We changed all the ones with a default enabled launcher icon other than Vanadium which will be done later. The keyboard has an optional launcher icon so that one would make sense, although I doubt many people enable the launcher icon. SIM Toolkit is another example that's sometimes visible. After that it'd make sense to do everything with activities (which includes the keyboard and SIM Toolkit too). I don't really see much point in putting effort into changing icons which technically exist but only ever appear if someone looks through the list of system apps.

**Comment by gosreport** [comment]
i have a better idea on how this can be handled, i will close this issue and open another one
